- docs/nameservers.md
- docs/why-the-dot.md
> minor editing

- docs/writing-providers.md
Adds a little note about vendoring dependencies into the doc for provider authors.
> Note about vendoring dependencies.

- docs/_providers/dnsimple.md
- docs/_providers/gandi.md
- integrationTest/providers.json
- models/dns.go
- providers/gandi/gandiProvider.go
- providers/gandi/protocol.go
> Adding gandi to integration suite. Fixing bugs.

- docs/_providers/cloudflare.md
- providers/cloudflare/cloudflareProvider.go
Also correct other minor typos
> Correct docs to reflect supported values for cloudflare_proxy[_default]

- providers/namecheap/namecheap.go
> namecheap: Sorting nameservers

- README.md
- docs/getting-started.md
- docs/index.md
- docs/migrating.md
- misc/convertzone/README.md
CC: @captncraig @dattas
Craig: is there a better URL to use?
> getting-started.md: Add advice about converting old zones.

- providers/namedotcom/records.go
The warning is no longer needed.
> Name.com now creates NS records for all nameserves created

- docs/_providers/namecheap.md
- providers/namecheap/namecheap.go
> add BaseURL option to namecheap creds to allow setting sandbox endpoint

- providers/providers.go
I just noticed some minor typos in some comments and decided to correct them.
> Fix some typos in comments

- docs/examples.md
I stumbled a bit trying to set NS TTLs. This changes the TTL example to cover NS (apex) records and also to demonstrate DefaultTTL
> NS RR (apex) TTL example

- docs/assets/creds.json-example.txt
- docs/assets/dnsconfig.js-example.txt
- docs/getting-started.md
> Improve the getting started docs

- docs/getting-started.md
tweaking the Getting Started doc for multiple providers.
> updating getting started doc for multiple providers

- providers/cloudflare/cloudflareProvider.go
my try at fixing #7 but only for cloudflare... new to Go, so still learning...
> adding no_purge to cloudflare

- docs/_providers/cloudflare.md
to show how to use proxy and alias. Took me a while to figure this out, though i would update the doc...
> updating cloudflare documentation

- docs/_providers/route53.md
Hi,
As asked in #93 , I update the route 53 documentation with the possible aws credentials configuration.
Thanks
> modify route53 documentation with the aws credentials configuration

- providers/gandi/gandiProvider.go
@captncraig  Recommendation of how to write a test for this?
> Gandi does not support TTLs > 30 days

- providers/namedotcom/records.go
Since this ANAME/ALIAS record is new,
> add the new ANAME record type to the records list

- docs/_providers/cloudflare.md
Hello there! 
* Fix syntax errors.
* Example on how to enable manage_redirects.
PR was tested with `runDocker.sh` and looks good.
Thanks!
> Cloudflare documentation update

- integrationTest/integration_test.go
- providers/cloudflare/cloudflareProvider.go
- providers/cloudflare/rest.go
This PR implements basic support for SRV records in the CloudFlare API.  It works for me but lacks automated tests.  This is my first time writing _anything_ in Go, so..  well, honestly I haven't even tried to figure out how to *run* the unit tests yet.  :)  But I did manually test creation, modification, and deletion of SRV records, with various protocols, priorities, targets, etc.
> Implement SRV support for CloudFlare provider

- pkg/normalize/validate.go
- providers/bind/bindProvider.go
- providers/namecheap/namecheap.go
- providers/providers.go
Fixes https://github.com/StackExchange/dnscontrol/issues/128
> Ban NO_PURGE when using BIND and others.

- models/dns.go
- providers/gandi/gandiProvider.go
- providers/gandi/protocol.go
Adding functionality to allow Gandi to use SRV record types.  I was able to run through the test cases successfully.
> adding functionality to allow Gandi to use SRV record types

- docs/_layouts/default.html
- docs/_providers/activedir.md
- docs/_providers/bind.md
- docs/_providers/cloudflare.md
- docs/_providers/digitalocean.md
- docs/_providers/dnsimple.md
- docs/_providers/gandi.md
- docs/_providers/gcloud.md
- docs/_providers/name.com.md
- docs/_providers/namecheap.md
- docs/_providers/ns1.md
- docs/_providers/softlayer.md
- docs/adding-new-rtypes.md
- docs/alias.md
- docs/css/site.css
- docs/examples.md
- docs/getting-started.md
- docs/index.md
- docs/js.md
- docs/migrating.md
- docs/nameservers.md
- docs/provider-list.md
- docs/release-engineering.md
- docs/toc.md
- docs/unittests.md
- docs/why-the-dot.md
- docs/writing-providers.md
- Beautified CSS
- Added page titles
- Made site work on mobile devices
See #221
> Website fixes (Part 1)

- docs/_providers/cloudflare.md
- Grammar fixes
- Fixed wrong highlighting type
- Formatted markdown better
- Other various fixes
See #221
> Fixed Cloudflare docs (#221)

- docs/_providers/gandi.md
- Markdown formatting improvements
- Other fixes
See #221
> Improve Gandi documentation (#221)

- docs/_providers/gcloud.md
- Markdown formatting improvements
- Added note about newlines in private key
See #221
> Improve Google Cloud DNS docs (#221)

- docs/_providers/ns1.md
> Improve NS1 documentation (#221)

- docs/_providers/bind.md
- Fixed highlighting language
- Improved markdown formatting
- Improved grammar
See #221
> Improved BIND docs (#221)

- docs/_providers/name.com.md
- Improved formatting
- Other fixes
See #221
> Improved Name.com documentation (#221)

- docs/_providers/dnsimple.md
- Grammar improvements
- Markdown formatting improvements
See #221
> Improve DNSimple documentation (#221)

- docs/_providers/digitalocean.md
- Grammar fixes
- Formatting improvements
- Changed a completely wrong statement about route53 (should be about DO)
See #221
> Improved DigitalOcean documentation (#221)

- docs/index.md
- docs/nameservers.md
- docs/release-engineering.md
- docs/toc.md
See the commit list for more info.
#221
> Website fixes (Part 2) (#221)

- docs/getting-started.md
> spelling-mistake

- integrationTest/integration_test.go
- providers/ns1/ns1provider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/269
> NS1 Provider TXT records are split

- docs/_includes/matrix.html
- providers/gandi/gandiProvider.go
- providers/gandi/protocol.go
- vendor/github.com/prasmussen/gandi-api/domain/domain.go
- vendor/github.com/prasmussen/gandi-api/domain/nameservers/nameservers.go
- vendor/github.com/prasmussen/gandi-api/domain/zone/record/record.go
- vendor/vendor.json
Adds support to the existing gandi provider to support changing nameservers.
> GANDI: Registrar support

- docs/_includes/matrix.html
- providers/activedir/activedirProvider.go
- providers/bind/bindProvider.go
- providers/cloudflare/cloudflareProvider.go
- providers/digitalocean/digitaloceanProvider.go
- providers/dnsimple/dnsimpleProvider.go
- providers/gandi/gandiProvider.go
- providers/gcloud/gcloudProvider.go
- providers/linode/linodeProvider.go
- providers/namecheap/namecheapProvider.go
- providers/namedotcom/namedotcomProvider.go
- providers/ovh/ovhProvider.go
- providers/route53/route53Provider.go
- providers/softlayer/softlayerProvider.go
- providers/vultr/vultrProvider.go
* Consolidate all docNotes and capabilities to a features variable.
* Sort and unique capabilities.
> ALL: Reformat all  capabilities

- docs/_includes/matrix.html
- integrationTest/integration_test.go
- providers/namedotcom/namedotcomProvider.go
- providers/namedotcom/records.go
I believe we support the TXTMulti capability, these changes should allow it.
Let me know if the resulting DNS entries don't look right in production.
> add TXTMulti capability to the namedotcom provider

- vendor/github.com/prasmussen/gandi-api/client/client.go
- vendor/vendor.json
This is in preparation for the new LiveDNS support.
> GANDI: Rev github.com/prasmussen/gandi-api

- providers/namedotcom/records.go
fixes https://github.com/StackExchange/dnscontrol/issues/306
> trim trailing '.' from FQDN

- models/record.go
- providers/dnsimple/dnsimpleProvider.go
* Fix https://github.com/StackExchange/dnscontrol/issues/321
> BUGFIX: Refactoring broke DNSimple support for ALIAS

- docs/_includes/matrix.html
- providers/_all/all.go
- providers/opensrs/opensrsProvider.go
- vendor/github.com/philhug/opensrs-go/LICENSE
- vendor/github.com/philhug/opensrs-go/opensrs/authentication.go
- vendor/github.com/philhug/opensrs-go/opensrs/domains.go
- vendor/github.com/philhug/opensrs-go/opensrs/opensrs.go
- vendor/github.com/philhug/opensrs-go/opensrs/structs.go
- vendor/github.com/philhug/opensrs-go/opensrs/xml.go
- vendor/vendor.json
Fetching and updating nameservers work.
Testing required.
> WIP: OpenSRS registrar support

- providers/dnsimple/dnsimpleProvider.go
an attempt to fix travis. (also #377)
> dnsimple: gofmt

- providers/dnsimple/dnsimpleProvider.go
- vendor/github.com/dnsimple/dnsimple-go/LICENSE.txt
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/accounts.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/authentication.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/certificates.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/contacts.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/dnsimple.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/domains.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/domains_collaborators.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/domains_delegation_signer_records.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/domains_dnssec.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/domains_email_forwards.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/domains_pushes.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/oauth.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/registrar.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/registrar_whois_privacy.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/services.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/services_domains.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/templates.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/templates_domains.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/templates_records.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/users.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/vanity_name_server.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/webhooks.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/zones.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/zones_records.go
- vendor/vendor.json
Tests on this won't pass until #413 is merged & this is rebased over it
> Update DNSimple-go to v0.20.0 and fix provider

- docs/adding-new-rtypes.md
- docs/spf-optimizer.md
Hello there!
* Fix `SPF_BUILDER()` naming.
* Fix indentation for `prettier` example.
PR was tested with `runDocker.sh` and looks as intended.
Thanks!
> Documentation

- docs/_providers/cloudflare.md
- providers/cloudflare/cloudflareProvider.go
This fixes #446. I have tested the change and the CF API does handle it as expected.
@tlimoncelli Unfortunately I'm not really sure how the exact documentation update should look like.
> Fixes #446: CF SPF

- providers/cloudflare/cloudflareProvider.go
- providers/cloudflare/rest.go
This adds TLSA and SSHFP support for Cloudflare.
> Cloudflare: Added TLSA and SSHFP support

- integrationTest/integration_test.go
- providers/namedotcom/namedotcomProvider.go
NAMEDOTCOM: TXTMulti is broken. Disable.
CLOUDFLARE: Fix SSHFP tests.
> Fix integration tests

- .travis.yml
- Dockerfile
- azure-pipelines.yml
- build/azure-pipelines/integration.yml
- integrationTest/integration_test.go
Sustained Engineering Work. 
Fixed integration tests that broke with 1.13
> Upgrade go version to 1.13

- docs/_providers/route53.md
My editor fixed some white space too, let me know if thats too much.
> documenting lessons from #548

- docs/_includes/matrix.html
> Regenerate provider support matrix

- providers/namecheap/namecheapProvider.go
Namecheap supports CAA now -- this PR flags it as such.
A small update was also needed in GetDomainCorrections to handle the different record response data. This also fixed an unrelated bug where TXT records for Namecheap were being corrected on every run of  `dnscontrol push` even if nothing actually changed.
> Add Namecheap CAA support

- docs/_functions/domain/DnsProvider.md
- docs/_functions/domain/NAMESERVER.md
- docs/_functions/domain/NS.md
- docs/_functions/global/NewDnsProvider.md
- pkg/nameservers/nameservers.go
Fixes https://github.com/StackExchange/dnscontrol/issues/581
> Explain nameservers better

- commands/getCerts.go
Fixes https://github.com/StackExchange/dnscontrol/issues/468
> Try all cert renewals before returning error.

- providers/azuredns/azureDnsProvider.go
When having multiple zones in the same resource group, the zone references were being switched up and ended up updating the wrong record set
> Fix AzureDNS query updating the wrong Domain

- go.mod
- go.sum
- vendor/github.com/vultr/govultr/CHANGELOG.md
- vendor/github.com/vultr/govultr/govultr.go
- vendor/github.com/vultr/govultr/object_storage.go
- vendor/modules.txt
> Update govultr to v0.2.0

- docs/_includes/matrix.html
- providers/azuredns/azureDnsProvider.go
Refactored Azure DNS to implement GetZone and ListZones 
Actions #628
> Implement Get Zone for Azure DNS

- docs/_includes/matrix.html
- providers/digitalocean/digitaloceanProvider.go
Related #628 
I ran the tests & the new command.
Also included a commit removing unnecessary AddOrigin call mentioned in a fixme comment.
> Do get zones

- docs/_includes/matrix.html
- docs/writing-providers.md
- go.mod
- go.sum
- providers/dnsimple/dnsimpleProvider.go
- vendor/github.com/dnsimple/dnsimple-go/LICENSE.txt
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/dnsimple.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/domains.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/registrar.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/registrar_whois_privacy.go
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/tlds.go
- vendor/modules.txt
- Implement GetZoneRecords Per #628 
- Update go mod & tidy Per #619 
- Update comments and notes
- Implement ListZones per documentation
- Add a missing error checking
- update `go generate` after updating capabilities
> DNSimple: Implement GetZones and ListZones 

- providers/dnsimple/dnsimpleProvider.go
- providers/route53/route53Provider.go
Relates to https://github.com/StackExchange/dnscontrol/issues/628
> ROUTE53: Fully implement get-zones

- providers/activedir/domains.go
Helps with https://github.com/StackExchange/dnscontrol/issues/628
> ACTIVEDIRECTORY: Implement get-zones

- providers/gcloud/gcloudProvider.go
Helps with https://github.com/StackExchange/dnscontrol/issues/628
> GCLOUD: Implement get-zones

- providers/namedotcom/namedotcomProvider.go
- providers/namedotcom/records.go
- providers/namedotcom/zones.go
This implements get-zones (and the "all" feature).  I haven't been able to test this because I use NDC as a registrar, not for DNS service.
> NAMEDOTCOM: Implement get-zones

- providers/softlayer/softlayerProvider.go
Appending record data into TxtStrings array
> Fixed Softlayer TXT Record existence Issue #583

- providers/softlayer/softlayerProvider.go
modifying TTL value to Minimum supported Value by softlayer if found less than it.
> Fixed: Softlayer Lets Encrypt Certificate issue #668

- docs/_includes/matrix.html
- docs/_providers/gandi_v5.md
- providers/gandi_v5/convert.go
- providers/gandi_v5/gandi_v5Provider.go
I can't find a sandbox for Gandi to test with so haven't run integration tests, but I've tested these all with one of my domains (which is how I found the "ALIAS only at apex" restriction).
> GANDI_V5: ALIAS, SSHFP, TLSA

- .travis.yml
- Dockerfile
- build/azure-pipelines/go-env.yaml
- go.mod
- vendor/modules.txt
go mod edit -go=1.14
go mod vendor
Update Dockerfile
Update Azure Pipelines
Ran tests (integration and normal packages)
> upgrade go version to 1.14

- providers/cloudns/cloudnsProvider.go
* #628 get-zones implemented
* #491 convert to models.ToNameservers
> ClouDNS: Get zone records implemented 

- docs/_functions/domain/CF_REDIRECT.md
- docs/_functions/domain/CF_TEMP_REDIRECT.md
- docs/_providers/cloudflare.md
> Correct Cloudflare redirect function documentation

- go.mod
- go.sum
- vendor/github.com/Azure/azure-sdk-for-go/LICENSE
- vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns/recordsets.go
- vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns/resourcereference.go
- vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns/zones.go
- vendor/github.com/Azure/azure-sdk-for-go/version/version.go
- vendor/github.com/Azure/go-autorest/autorest/adal/token.go
- vendor/github.com/Azure/go-autorest/autorest/authorization.go
- vendor/github.com/Azure/go-autorest/autorest/authorization_storage.go
- vendor/github.com/Azure/go-autorest/autorest/azure/async.go
- vendor/github.com/Azure/go-autorest/autorest/client.go
- vendor/github.com/Azure/go-autorest/autorest/go.mod
- vendor/github.com/Azure/go-autorest/autorest/go.sum
- vendor/github.com/Azure/go-autorest/autorest/sender.go
- vendor/github.com/Azure/go-autorest/autorest/utility.go
- vendor/github.com/Azure/go-autorest/autorest/version.go
- vendor/modules.txt
> Update azure sdk for go

- commands/getZones.go
- commands/r53_test.go
- docs/_functions/domain/R53_ALIAS.md
> get-zones: generate R53_ALIAS right

- providers/gcloud/gcloudProvider.go
> GCLOUD: Support SSHFP

- README.md
- docs/_providers/desec.md
- providers/_all/all.go
- providers/desec/convert.go
- providers/desec/desecProvider.go
- providers/desec/protocol.go
> NEW PROVIDER: deSEC

- go.mod
- go.sum
- vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns/version.go
- vendor/github.com/Azure/azure-sdk-for-go/version/version.go
- vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
- vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/service/route53/api.go
- vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
- vendor/modules.txt
*   go: github.com/Azure/azure-sdk-for-go upgrade => v42.0.0+incompatible
*   go: github.com/aws/aws-sdk-go upgrade => v1.30.19
> Update AWS and Azure dependencies

- OWNERS
- docs/provider-list.md
- docs/writing-providers.md
This will resolve the issues mentioned in  #730
> Update docs to resolve  #730

- OWNERS
- README.md
- docs/_includes/matrix.html
- docs/_providers/axfrddns.md
- docs/provider-list.md
- integrationTest/providers.json
- providers/_all/all.go
- providers/axfrddns/axfrddnsProvider.go
This is a tentative implementation for a provider based on AXFR requests and Dynamic DNS updates as suggested in #259.
This is Work-In-Progress---it does not pass all the integration test yet---and this is my first try at go programming, so this MR is mostly for feedbacks.
> New provider: AXFR+DDNS (#259)

- docs/adding-new-rtypes.md
- docs/writing-providers.md
- integrationTest/integration_test.go
General improvements based on the advice I give to new PR submitters.
> Clarify dev docs

- docs/_functions/global/IP.md
Fixes https://github.com/StackExchange/dnscontrol/issues/737
> Document IP() is IPv4 only

- pkg/acme/directoryStorage.go
Fixes https://github.com/StackExchange/dnscontrol/issues/728
> 'get-certs' permissions too open

- docs/notifications.md
- pkg/notifications/slack.go
Added `slack` as a new notification connector
> Added slack notifications

- pkg/diff/diff.go
Fixes https://github.com/StackExchange/dnscontrol/issues/708
> Implement a simple lexicographic sort.

- docs/get-zones.md
apologies, I thought I'd included this in #766
> fix get-zones code block indentation

- providers/ns1/ns1provider.go
#775 Adds support for ALIAS records and enables PTR and TXTMulti.
> NS1: Added support for ALIAS, PTR, and TXTMulti

- providers/ns1/ns1provider.go
#779 Fix for MX records on NS1. NS1 is passing all integration tests now!
Integration test: https://pastebin.com/M4Qn0CKK
> Fixed MX records on NS1

- providers/powerdns/powerdnsProvider.go
I did a mistake when checking if the domain is there or not.
The go powerdns api is raising a error when the domain is not there. I got a nil pointer exception cause the zone isn't there.
Now it is checking the returned error.
> Fixing PowerDNS domain creation

- docs/notifications.md
- pkg/notifications/teams.go
Add support to send notifications to MS Teams
> Notifications: Microsoft Teams

- OWNERS
- README.md
- docs/_includes/matrix.html
- docs/_providers/inwx.md
- docs/provider-list.md
- go.mod
- go.sum
- integrationTest/integration_test.go
- integrationTest/providers.json
- providers/_all/all.go
- providers/capabilities.go
- providers/inwx/inwxProvider.go
Adds registrar and dns provider support for inwx.de. First requested in #254 
ToDo:
> INWX provider

- OWNERS
- docs/provider-list.md
> Cleanup: user geek1011 is now pgaskin

- providers/inwx/inwxProvider.go
see comments in #808 by @tlimoncelli
> fix golint issues in INWX provider

- README.md
Relates to https://github.com/StackExchange/dnscontrol/issues/805
> Docs: Improve install instructions

- providers/azuredns/azureDnsProvider.go
> AZURE: Cleanup: Return Errorf value of Error instead of pure Error

- OWNERS
- README.md
- docs/provider-list.md
@mikenz Hey, I merged that provider without checking a few things.  Can you review these changes.
Thanks!
> Add DNSOVERHTTPS to docs

- cmd/convertzone/main.go
- go.mod
- go.sum
- pkg/prettyzone/prettyzone_test.go
Requires some code changes due to a deprecated API.
> go get -u github.com/miekg/dns v1.1.31

- docs/_includes/matrix.html
- docs/_providers/cscglobal.md
- docs/provider-list.md
- providers/_all/all.go
- providers/cscglobal/api.go
- providers/cscglobal/cscglobalProvider.go
> New Registrar: CSC Global

- go.mod
- go.sum
- providers/powerdns/dnssec.go
- providers/powerdns/powerdnsProvider.go
This PR implements AUTODNSSEC for PowerDNS
> PowerDNS: Implemented AUTODNSSEC

- docs/_providers/inwx.md
> INWX: add additional documentation about 2FA limitations

- pkg/normalize/validate.go
Fixes https://github.com/StackExchange/dnscontrol/issues/864
> NAMESERVER() validity check fixed

- docs/_functions/domain/NAMESERVER.md
- docs/nameservers.md
Fixes https://github.com/StackExchange/dnscontrol/issues/867
> DOCS: Better explain nameserver scenarios

- go.mod
- go.sum
- providers/gandi_v5/convert.go
- providers/gandi_v5/gandi_v5Provider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/878
> GANDI_V5: Use github.com/go-gandi

- integrationTest/integration_test.go
> VULTR: Null MX records are not supported

- providers/vultr/vultrProvider.go
This PR does not change the behaviour of anything. Integration tests will pass after #894 is merged.
see #314
> VULTR: AddOrigin is unnecessary

- docs/_providers/route53.md
See https://github.com/StackExchange/dnscontrol/issues/891
> ROUTE53: Document CNAME bug

- README.md
- main.go
- Add module info to version
- Add warning if built without Go modules
- Update source installation instructions for Go modules
see #890
> Go module build improvements

- README.md
Netcup was added in 3.2 https://stackexchange.github.io/dnscontrol/provider-list
> Update README.md and add Netcup as DNS Provider

- .github/workflows/build.yml
Follow-up to https://github.com/StackExchange/dnscontrol/pull/922
Just the unit tests. Separate PR for integration tests.
Output from test run:
```
> Run go test ./...
go: downloading github.com/hexonet/go-sdk v3.5.0+incompatible
go: downloading github.com/babolivier/go-doh-client v0.0.0-20200723140836-2f86c709ac4a
go: downloading github.com/mittwald/go-powerdns v0.5.2
go: downloading github.com/digitalocean/godo v1.46.0
go: downloading github.com/dnsimple/dnsimple-go v0.62.0
go: downloading github.com/billputer/go-namecheap v0.0.0-20170915210158-0c7adb0710f8
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading golang.org/x/oauth2 v0.0.0-20200902213428-5d25da1a8d43
go: downloading github.com/go-acme/lego v2.7.2+incompatible
go: downloading github.com/google/go-github …
```
> Run unit tests as part of build checks

- .github/workflows/build.yml
Follow-up to https://github.com/StackExchange/dnscontrol/pull/928: add
* Azure DNS
* NAMEDOTCOM
* GCloud
* Cloudflare
([secrets](https://github.com/StackExchange/dnscontrol/settings/secrets))
> Run integration tests for additional DNS providers

- .github/workflows/build.yml
- README.md
Update the "Build Status" badge on the README page to point to the new GH Actions workflow (build & unit tests & integration tests).
Also, run said workflow again on the master branch (after PR merges).
Fixes #602.
> Update build status badge to GH Actions workflow

- .github/workflows/build.yml
- docs/writing-providers.md
Fixes https://github.com/StackExchange/dnscontrol/issues/923
> HEXONET: Add GHA tests. Update docs.

- providers/azuredns/azureDnsProvider.go
- providers/gcloud/gcloudProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/764
> GCLOUD: Don't panic() on unknown domain name

- docs/writing-providers.md
Fixes https://github.com/StackExchange/dnscontrol/issues/906
> DOCS: Fix golint and vendoring notes

- docs/_providers/powerdns.md
Fixed config keys and removed caveats. Second PR, because I deleted the fork too fast ;)
> DOCUMENTATION: Fix powerdns config keys using camel case

- .github/workflows/build.yml
- docs/byo-secrets.md
- docs/index.md
- integrationTest/providers.json
Fixes https://github.com/StackExchange/dnscontrol/issues/980
> Enable Bring-Your-Own-Secrets

- docs/_providers/doh.md
- docs/_providers/internetbs.md
Fixes https://github.com/StackExchange/dnscontrol/issues/1013
> Fix typo: NNAMESERVER

- integrationTest/integration_test.go
- providers/cloudflare/cloudflareProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/1002
> CLOUDFLARE: Now supports PunyCode/IDNA

- .github/workflows/release.yml
Using the fpm github action, this creates and uploads a RPM and DEB for each release
> feature: adding RPM/DEB package creation and upload as asset

- pkg/normalize/validate.go
Fixes https://github.com/StackExchange/dnscontrol/issues/1039
> BUG: Labels that are FQDN should not cause panics

- providers/gandi_v5/auditrecords.go
- providers/gandi_v5/convert.go
- providers/gandi_v5/convert_test.go
- providers/gandi_v5/gandi_v5Provider.go
- providers/gcloud/auditrecords.go
- providers/gcloud/gcloudProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/1060
Fixes https://github.com/StackExchange/dnscontrol/issues/1059
> Make GCLOUD and GANDI_V5 modules consistent

- .github/workflows/build.yml
ClouDNS were kind enough to provide us with test account for CI. But I'm not sure how to provide it to you.... Who may I contact on this topic?
> ClouDNS. Automated testing

- docs/_includes/matrix.html
- models/t_ds.go
- providers/gandiv5/convert.go
- providers/gandiv5/gandi_v5Provider.go
* Simply mark DS as supported, let existing tests handle it.
* Fix trivial typo in diagnostic feedback from model SetTargetDSString()
* The support matrix includes more changes because it was stale.
> GANDI_V5: supports DS records already

- docs/_providers/bind.md
Update docs after reflecting on https://github.com/StackExchange/dnscontrol/issues/1129
CC: @flymia
> DOCS: Improve BIND SOA explanation

- README.md
Fixes https://github.com/StackExchange/dnscontrol/pull/1133
> DOCS: Document how to preview website

- integrationTest/integration_test.go
* Add `-elapsed` flag to integration tests which outputs timing information
* Remove certain tests for NAMEDOTCOM and GANDI_V5 because they are painfully slow.
> MAINT: Speed up integration tests

- docs/_functions/domain/SOA.md
- integrationTest/integration_test.go
- pkg/js/helpers.js
- providers/bind/bindProvider.go
- providers/bind/soa.go
- providers/bind/soa_test.go
This adds integration tests to https://github.com/StackExchange/dnscontrol/pull/1115
> Add integration test for SOA

- providers/namecheap/namecheapProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/1142
> Enable ALIAS support for Namecheap

- OWNERS
- README.md
- docs/_providers/transip.md
- docs/provider-list.md
- go.mod
- go.sum
- integrationTest/providers.json
- providers/_all/all.go
- providers/transip/auditrecords.go
- providers/transip/transipProvider.go
Add functionality to use TransIP DNS
> Transip provider

- providers/namecheap/namecheapProvider.go
I wanted to import some namcheap domains so I needed this, better share it with the rest of you.
> Add namecheap get zone functionality

- providers/desec/convert.go
- providers/desec/desecProvider.go
- providers/desec/protocol.go
This PR will implement pagination for the deSEC provider (#1177), this is needed when ever the api could return over 500 elements.
> deSEC implement pagination

- providers/inwx/inwxProvider.go
Reverts StackExchange/dnscontrol#1221
As discussed at https://github.com/StackExchange/dnscontrol/issues/1218#issuecomment-898711452
> Revert "INWX: fix apex domains"

- main.go
This release includes many features and improvements including new macros for delegating domains elsewhere, more conformant DMARC_BUILDER, the ability to INCLUDE a domain's records in another domain, and SPF-Flatten on non-apex domains.  Route53 users can now specify a R53_ZONE on a domain or record, VULTR users now have better TXT quoting support. And as always, dependencies have been updated.
Breaking changes:
* none
Major features:
* NEW MACROS: DOMAIN_ELSEWHERE and DOMAIN_ELSEWHERE_AUTO (#1237)
* DMARC_BUILDER: specify version, use values when specified (#1236)
* NEW FEATURE: Add INCLUDE statement to include records from other domains (#1219)
* SPF Flatten now works on non apex domains (#1220)
Provider-specific changes:
* ROUTE53: Add R53_ZONE as an domain identifier (#1241)
* INWX: …
> Release v3.12.0

- providers/dnsmadeeasy/restApi.go
- providers/dnsmadeeasy/types.go
Fixed all errors reported by staticcheck in DnsMadeEasy provider.
Resolve #1313.
> DNSMADEEASY: Fix staticcheck errors

- providers/transip/transipProvider.go
> fix issues found by staticcheck

- docs/_providers/cloudflare.md
This was incorrectly documented in #1243
> CLOUDFLARE: Fix documentation for CF_WORKER_ROUTE

- docs/_includes/matrix.html
- providers/ns1/ns1Provider.go
Refactor code to get zones from NS1 API into GetZonesRecords function to
enable get-zones
> NS1: Enable get-zones

- OWNERS
> new maintainer for ns1

- providers/ns1/ns1Provider.go
Enable support for NAPTR support in NS1.
Closes: #1407
> ns1: add support for NAPTR

- providers/bind/bindProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/1410
> BIND: Bug: DefaultNS strips last char

- README.md
Fixes https://github.com/StackExchange/dnscontrol/issues/1344
> DOCS: Update README with GHA and LE news

- providers/cloudflare/cloudflareProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/1436
> CLOUDFLARE: Bug: crash when SRV is missing target

- docs/_providers/cloudflare.md
- integrationTest/integration_test.go
* Document bug in Cloudflare's docs
* Add (but comment out) integration test that will catch this
> CLOUDFLARE: Document ">1000 changes" bug

- go.mod
- go.sum
- providers/gandiv5/gandi_v5Provider.go
`go get: upgraded github.com/go-gandi/go-gandi v0.0.0-20211124085723-a737785a1af0 => v0.1.0`
> GANDI: Bump go-gandi/go-gandi v0.0.0-20211124085723 => v0.1.0

- go.mod
- go.sum
```
go get: upgraded github.com/Azure/azure-sdk-for-go v62.0.0+incompatible => v62.1.0+incompatible
```
> AZURE: Upgrade github.com/Azure/azure-sdk-for-go to v62.1.0+incompatible

- providers/cloudflare/cloudflareProvider.go
- providers/cloudflare/rest.go
Fixes https://github.com/StackExchange/dnscontrol/issues/1451
> CLOUDFLAREAPI: Guard against nil crashes

- providers/dnsimple/dnsimpleProvider.go
The DNSimple provider is rejecting all NS records, on the basis that they can't be changed.  This is bogus: it's only the apex records which can not be changed.  Child domains can have delegation glue NS records.
There's no internal tests for the provider, so I tested with the domain where I encountered the bug.  I got the diffs to disappear with `dnscontrol preview`; then I removed one of the NS records in an rrset and re-ran, and saw the diff, and then `dnscontrol push` successfully reconciled.  `go test -v ./...` passes still.
@aeden FYI
> DNSIMPLE: bug-fix, allow non-apex NS records

- integrationTest/integration_test.go
- models/dns.go
> Eliminate models.StringsToNameservers()

- commands/getZones.go
- commands/previewPush.go
- integrationTest/integration_test.go
- pkg/credsfile/providerConfig.go
- pkg/credsfile/providerConfig_test.go
* Rename providers/config to pkg/credsfile
> Refactor in preparation for v3.16

- OWNERS
- README.md
- docs/provider-list.md
I'm happy to take these two over in addition to EasyName.
> Update maintainers for Route53 and Cloudflare

- docs/creds-json.md
- go.mod
- go.sum
- pkg/credsfile/providerConfig.go
- providers/vultr/auditrecords.go
As mentioned in https://github.com/StackExchange/dnscontrol/pull/1513 here is the PR for it :)
> Add calling a shell command for credentials file

- README.md
Signed-off-by: Riyadh Al Nur <riyadhalnur@verticalaxisbd.com>
> CHORE: update provider maintainer message

- docs/_providers/cscglobal.md
- docs/writing-providers.md
- go.mod
- integrationTest/integration_test.go
- integrationTest/providers.json
- models/provider.go
- models/target.go
- pkg/credsfile/providerConfig.go
- pkg/normalize/validate.go
- providers/cscglobal/api.go
- providers/cscglobal/auditrecords.go
- providers/cscglobal/convert.go
- providers/cscglobal/cscglobalProvider.go
- providers/cscglobal/dns.go
- providers/cscglobal/listzones.go
- providers/cscglobal/registrar.go
- providers/providers.go
CSCGLOBAL is currently supported as a DNS Registrar.  This adds support as a DNS Service Provider.
Fixes https://github.com/StackExchange/dnscontrol/issues/1515
> NEW PROVIDER: CSCGLOBAL as DNS Service Provider

- docs/_providers/gandi_v5.md
Fixes https://github.com/StackExchange/dnscontrol/issues/1540
> GANDI: Document sharing_id errors

- providers/dnsmadeeasy/types.go
This PR fixes parsing TXT records for #1568.
Integration tests are now passing for the DNSMADEEASY provider.
> DNSMADEEASY: fix parsing TXT records

- providers/hostingde/types.go
> HOSTINGDE: Use QuoteEscapedFields for TXT records

- providers/akamaiedgedns/akamaiEdgeDnsService.go
Passes integration tests:
--- PASS: TestDNSProviders (283.64s)
--- PASS: TestDualProviders (1.39s)
PASS
ok  	github.com/StackExchange/dnscontrol/v3/integrationTest	285.621s
> Fix for PopulateFromString issue

- providers/oracle/oracleProvider.go
Hi @kallsyms !
Please run the integration tests and verify I didn't break anything.
Thanks!
Tom
> Update TXT handling for Oracle

- README.md
Fixes https://github.com/StackExchange/dnscontrol/issues/1573
> DOCS: Fix "go install" command

- .circleci/config.yml
Updated the Circle CI multi-arch environment variable.
> Chore: Update Circle CI multi-arch environment

- README.md
Fixes https://github.com/StackExchange/dnscontrol/issues/1619
> Announce OctoDNS decomm.

- providers/cloudflare/rest.go
Fixes https://github.com/StackExchange/dnscontrol/issues/366
> CLOUDFLAREAPI: Clarify source of error in message

- .github/dependabot.yml
> CHORE: Decrease the dependabot docker frequency

- providers/msdns/msdnsProvider.go
> MSDNS: MSDNS disable message is now more accurate

- README.md
- docs/_includes/matrix.html
- docs/_providers/domainnameshop.md
- providers/domainnameshop/domainnameshopProvider.go
Update of documentation for Domainnameshop to better reflect current state according to their team.
> Domainnameshop documentation update

- commands/previewPush.go
- docs/_functions/global/D_EXTEND.md
- docs/_functions/global/getConfiguredDomains.md
- docs/_providers/route53.md
- docs/getting-started.md
- pkg/nameservers/nameservers.go
- pkg/printer/printer.go
Fixes https://github.com/StackExchange/dnscontrol/issues/1720
> Add --verbose flag, default to less verbose output

- README.md
Updated the Install section of the readme to mention MacPorts.
Also did some minor fixups on the formatting of the Install section.
> DOCS: Add MacPorts to Install section

- .goreleaser.yml
- README.md
- docs/release-engineering.md
Fixed typo `depreciation` = `deprecation`.
> Fixed typo deprecation

- docs/_providers/hedns.md
Fix the markdown for the dns.he.net link.
> DOCS: Fix dns.he.net link

- docs/_functions/domain/AKAMAICDN.md
- docs/_functions/domain/AZURE_ALIAS.md
- docs/_functions/domain/CF_REDIRECT.md
- docs/_functions/domain/CF_TEMP_REDIRECT.md
- docs/_functions/domain/CF_WORKER_ROUTE.md
- docs/_functions/domain/R53_ALIAS.md
- docs/_functions/record/DMARC_BUILDER.md
- docs/_functions/record/R53_ZONE.md
- docs/_includes/table-of-contents.md
- docs/css/site.css
- docs/js.md
Fixes #1777
The result of this ~~merge~~ pull request when running Jekyll locally.
> Javascript DSL table of contents (TOC)

- providers/dnsimple/dnsimpleProvider.go
DNSimple has added new name server suffixes and changed the default name server set for new domains.
In order to support this this adds new logic for the new domains.
It also changes the default set by the provider, this will be a change for any domains still using the legacy ns4.
> [DNSimple] Update name server handling

- go.mod
- go.sum
Fixes https://github.com/StackExchange/dnscontrol/issues/1812
Fixes https://github.com/StackExchange/dnscontrol/issues/1695
> Fix ELF crash

- providers/vultr/vultrProvider.go
> VULTR: Use keyed fields for govultr struct literals

- providers/netlify/netlifyProvider.go
> fix(netlify): append . to records which point to hosts

- providers/ovh/ovhProvider.go
This adds support for Diff2 (cf #1854) for the OVH provider.
OVH API deals with records so the new Diff2 based implementations is not very different than the actual Diff1 one.
Integration tests pass in both diff1 and diff2 modes.
> Adapt OVH provider to Diff2

- providers/softlayer/softlayerProvider.go
In reference to replacing pkg/diff with the new pkg/diff2 (https://github.com/StackExchange/dnscontrol/issues/1854)
I've introduced a compatibility mode to pkg/diff2 to make it easier for providers to adopt the new system.  If you do a diff with "hide whitespace", you'll see the changes are minimal.
I've taken the liberty of providing this PR as a starting point.
Please run the integration tests and let me know the result. (If you're getting this, I probably don't have access to an account on this provider)
Please run:
```
go test -v -verbose -provider SOFTLAYER
```
and
```
go test -v -verbose -provider SOFTLAYER -diff2
```
They should both complete with no failures. Please fix any failures or loop me in for help.
If you are interested in porting to the new pkg/diff2/By*() functions, I'd …
> SOFTLAYER: Adopt diff2 in compatibility mode

- .goreleaser.yml
- README.md
- docs/_includes/matrix.html
- docs/provider-list.md
- integrationTest/providers.json
Addition to https://github.com/StackExchange/dnscontrol/pull/1910
> OCTODNS: Remove OctoDNS provider 

- providers/transip/transipProvider.go
Fixes #1919
In the old diff method there is no easy way to observe if a record is part of a multi-record recordset. TransIP is unable to handle modifications for these multi-record recordset. So the only way is to remove the old record and re-add the new record
> TransIP: For modifications always remove and re-add records

- providers/transip/transipProvider.go
> TransIP: Fix quoting of TXT records

- docs/_providers/route53.md
Fixed wrong Route53 Markdown link.
> DOCS: Fixed wrong Route53 Markdown link

- docs/_providers/akamaiedgedns.md
Updated the Akamai URLs.
Found from the work https://github.com/StackExchange/dnscontrol/pull/1809.
> DOCS: Akamai: Updated the Akamai URLs

- docs/adding-new-rtypes.md
See: https://github.com/StackExchange/dnscontrol/actions/runs/3913042186/jobs/6688447274#step:4:561
> Fix GitHub Pages build failure

- .circleci/config.yml
> BUILD SYSTEM: Skip unused integration tests faster

- providers/hostingde/hostingdeProvider.go
While a zone is propagating, the zone cannot be edited. This commit adds an exponential back-off retry mechanism for writes.
> HOSTINGDE: Add simple exponential back-off retry

- docs/release-engineering.md
Fixes https://github.com/StackExchange/dnscontrol/issues/1950
> DOCS: Clarify BYO CCI

- providers/vultr/auditrecords.go
- providers/vultr/vultrProvider.go
see #1902
IDN CNAME Target still hangs
> VULTR: fix failing integration tests

- documentation/providers/cloudflareapi.md
- providers/cloudflare/cloudflareProvider.go
> CLOUDFLARE: sometime ago they bump down the min ttl to 60 second

- documentation/providers.md
Added RRPPRoxy https://github.com/StackExchange/dnscontrol/issues/1656 to the requested providers.
> DOCS: Added RRPPRoxy to the requested providers.

- providers/route53/route53Provider.go
> ROUTE53: (CHORE) Rename variables for clarity

- documentation/providers.md
Added SynergyWholesale https://github.com/StackExchange/dnscontrol/issues/1605 to the requested providers.
> DOCS: Requested provider SynergyWholesale

- documentation/functions/record/SPF_BUILDER.md
Applied the GitBook hint block for the warning message.
> DOCS: SPF_BUILDER GitBook hint block

- documentation/getting-started.md
Changed the Docker run command with the missing `zones` directory and added user to the Docker run command so there are no issues with zone file rights.
Before:
After:
> DOCS: Getting started fixed Docker run command

- documentation/functions/global/require.md
- documentation/functions/global/require_glob.md
Moved the file names to the GitBook code block caption.
> DOCS: [GitBook] Code block caption

- OWNERS
- documentation/providers.md
@KaiSchwarz-cnic https://github.com/StackExchange/dnscontrol/pull/1889#issuecomment-1407472678
> My gh account got renamed to KaiSchwarz-cnic ...
> DOCS: GitHub username updated

- documentation/functions/global/require.md
Typo `dnscontrol` = `DNSControl`.
> DOCS: Typo `dnscontrol` = `DNSControl`

- go.mod
- go.sum
> INWX: Updated nrdcg/goinwx to v0.8.2 to fix inwx provider

- providers/vultr/vultrProvider.go
Tried both
```
go test -v -verbose -provider VULTR
```
and
```
go test -v -verbose -provider VULTR -diff2
```
and both succeed
> VULTR: adopt diff2 in full mode

- .github/pull_request_template.md
Fixes https://github.com/StackExchange/dnscontrol/issues/2020
The origin is copy/paste of comment https://github.com/StackExchange/dnscontrol/pull/2006#discussion_r1090024971
> DOCS: Pull request template: Fixed `go mod tidy` command

- providers/hostingde/api.go
- providers/hostingde/hostingdeProvider.go
- providers/hostingde/types.go
> HOSTINGDE: Implement ListZones (fixes #1975)

- providers/hostingde/api.go
- providers/hostingde/hostingdeProvider.go
- providers/hostingde/types.go
> HOSTINGDE: Implement AutoDNSSEC

- commands/types/dnscontrol.d.ts
- go.sum
> go generate

- providers/hostingde/types.go
> HOSTINGDE: Fix pushing changes when templateValues are set (fixes #2024)

- pkg/diff/diff2compat.go
- pkg/diff2/diff2.go
- pkg/diff2/nopurge.go
- providers/azuredns/azureDnsProvider.go
- providers/gandiv5/gandi_v5Provider.go
- providers/gcore/gcoreProvider.go
- providers/hedns/hednsProvider.go
- providers/ns1/ns1Provider.go
- providers/ovh/ovhProvider.go
- providers/porkbun/porkbunProvider.go
- providers/route53/route53Provider.go
- providers/vultr/vultrProvider.go
> NEW FEATURE: NO_PURGE reports what is not purged (diff2 only)

- integrationTest/integration_test.go
> BUG: Integration test flag -end 0 doesnt stop at 0

- documentation/functions/domain/SOA.md
- pkg/soautil/soautil.go
- pkg/soautil/soautil_test.go
- providers/bind/soa.go
- providers/bind/soa_test.go
As discussed in https://github.com/StackExchange/dnscontrol/pull/2023#issuecomment-1410645574
> Expect SOA mailbox in hostmaster@example.org format instead of hostmaster.example.org

- integrationTest/integration_test.go
Add an integration test to change TTL on an A record.
> TESTING: Add test for TTL change

- integrationTest/providers.json
The tests can be performed by an environment variable `TRANSIP_PRIVATE_KEY` (and therefore `TRANSIP_ACCOUNT_NAME` is also necessary). cc: @blackshadev
My local set-up with [1Password CLI](https://1password.com/downloads/command-line/) integration:
```shell
cd integrationTest/
export TRANSIP_DOMAIN=cafferata.dev
export TRANSIP_ACCOUNT_NAME=`op read "op://jztc36gykxxj4mqvjdnkbzb67u/usrwc7kv4najbkubqrmx5xs3by/username"`
export TRANSIP_PRIVATE_KEY=`op read "op://jztc36gykxxj4mqvjdnkbzb67u/usrwc7kv4najbkubqrmx5xs3by/private-key"`
go test -v -verbose -provider TRANSIP
```
```text
=== RUN   TestDNSProviders/cafferata.dev
=== RUN   TestDNSProviders/cafferata.dev/Clean_Slate:Empty
...
```
> TRANSIP: Performed the integration tests by an TransIP private key.

- providers/hostingde/api.go
- providers/hostingde/types.go
> HOSTINGDE: Fix modify referencing incorrect record id (fixes #2066)

- pkg/normalize/validate.go
(Not removing the function due to #2090)
> Remove value check for removed AUTODNSSEC() function (we now only have AUTODNSSEC_ON and AUTODNSSEC_OFF)

- pkg/diff2/diff2.go
Go fmt [fc3a217d](https://github.com/StackExchange/dnscontrol/commit/fc3a217dc1da17ad2d8d36640393cfdeb546ae11#diff-b1f1b16455348a4d56cb996e477c913a8d600310f7c2fb9f07055b950ca64b25R148).
> CHORE: Go fmt

- integrationTest/integration_test.go
- models/record.go
- pkg/diff2/analyze.go
- pkg/diff2/analyze_test.go
- pkg/diff2/compareconfig.go
- pkg/diff2/compareconfig_test.go
- pkg/diff2/diff2.go
- providers/namedotcom/records.go
> BUG: diff2: ttl changes don't always work

- models/recorddb.go
- pkg/js/js.go
- pkg/normalize/validate.go
- pkg/recorddb/recorddb.go
- pkg/soautil/soautil.go
- providers/bind/bindProvider.go
- providers/gcore/gcoreExtend.go
- providers/hostingde/api.go
- providers/hostingde/hostingdeProvider.go
> CHORE: linting

- providers/cscglobal/convert.go
> CSCGLOBAL: Fix comment typo

- models/record.go
at https://pkg.go.dev/github.com/StackExchange/dnscontrol/
> DOC: Fixed a bit of havoc which appears in go docs

- pkg/diff/diff.go
- pkg/diff2/analyze.go
- pkg/diff2/analyze_test.go
> FEATURE: Colorize output

- commands/previewPush.go
> BUGFIX: REPORT change type always crashes on push

- documentation/opinions.md
- documentation/writing-providers.md
Fixed the incorrect inline anchors links.
> DOCS: Fixed the incorrect inline anchors links

- models/record.go
> DOCS: Fix typo in record.go

- build/generate/featureMatrix.go
- documentation/writing-providers.md
- providers/luadns/luadnsProvider.go
- providers/namedotcom/namedotcomProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/2171
> DOCS: Clarify/fix official and community support

- commands/types/dnscontrol.d.ts
- documentation/adding-new-rtypes.md
- documentation/cli-variables.md
- documentation/code-tricks.md
- documentation/examples.md
- documentation/functions/domain/CF_REDIRECT.md
- documentation/functions/domain/CF_TEMP_REDIRECT.md
- documentation/functions/domain/NAMESERVER.md
- documentation/functions/domain/NO_PURGE.md
- documentation/functions/domain/PTR.md
- documentation/functions/domain/PURGE.md
- documentation/functions/domain/R53_ALIAS.md
- documentation/functions/domain/SOA.md
- documentation/functions/domain/SSHFP.md
- documentation/functions/domain/TLSA.md
- documentation/functions/domain/TXT.md
- documentation/functions/global/DOMAIN_ELSEWHERE.md
- documentation/functions/global/DOMAIN_ELSEWHERE_AUTO.md
- documentation/functions/global/D_EXTEND.md
- documentation/functions/global/REV.md
- documentation/getting-started.md
- documentation/nameservers.md
- documentation/typescript.md
- documentation/why-the-dot.md
> DOCS: Mostly styling and links

- pkg/diff2/verb_string.go
> CHORE: go generate

- integrationTest/providers.json
> TESTING: Add TYPE field to providers.json

- providers/powerdns/diff.go
- providers/powerdns/dns.go
- providers/powerdns/dnssec.go
- providers/powerdns/powerdnsProvider.go
I've implemented the diff2 differ and done some cleanup. Integration test with and without the `-diff2` flag are passing.
> PowerDNS: Implement diff2 differ and some cleanup

- commands/types/dnscontrol.d.ts
- documentation/functions/domain/PTR.md
Reintroduced the missing space cc: https://github.com/StackExchange/dnscontrol/pull/2178 @systemcrash
> DOCS: Reintroduced the missing space

- .github/workflows/release.yml
> CHORE: Disable CGO

- documentation/release-engineering.md
> DOCS: Make version a variable in rel eng doc

- .circleci/config.yml
- documentation/byo-secrets.md
The instructions were wrong.  Correcting the .circleci/config.yml file.
> TESTING: Fix HE.DNS BYO-Secrets

- commands/types/dnscontrol.d.ts
- documentation/functions/domain/LOC.md
- documentation/functions/record/LOC_BUILDER_DD.md
- documentation/functions/record/LOC_BUILDER_DMM_STR.md
- documentation/functions/record/LOC_BUILDER_DMS_STR.md
- documentation/functions/record/LOC_BUILDER_STR.md
> DOCS: Fix number type in typescript 

- integrationTest/integration_test.go
> REFACTOR: Rearrange tests and add comments

- integrationTest/integration_test.go
> TESTING: Add comments for first-timers

- documentation/SUMMARY.md
- documentation/styleguide.md
Fixes https://github.com/StackExchange/dnscontrol/issues/2229
> DOC: Add a styleguide for developers.

- .circleci/config.yml
Enable CI integration tests for TransIP. cc: @blackshadev 
_The TransIP credentials have been sent via https://transfer.secretoverflow.com/u/tlimoncelli_
> TRANSIP: Enable CI integration tests

- documentation/styleguide.md
Added GitBook styling for https://github.com/StackExchange/dnscontrol/pull/2230.
**Before**
**After**
> DOCS: GitBook styling for style guide

- pkg/diff2/diff2.go
- providers/transip/transipProvider.go
Previous changes applied to transip diff2 which didn't seem to have been merged into master
See #2227
> Transip diff2

- .circleci/config.yml
- .github/workflows/release.yml
> BUILD: Fix Linux binary releases

- integrationTest/integration_test.go
Maybe it was a good anchor when searching? :)
> TESTS: comment fix

- integrationTest/integration_test.go
- models/dnsrr.go
- models/record.go
- pkg/normalize/validate.go
No additions or removals, only ordering.
Inserted some `#rtype_variations` tags
> CHORE: Alphabetize various code lists

- pkg/diff2/analyze.go
- pkg/diff2/analyze_test.go
- pkg/diff2/diff2.go
> diff2: Add a "hints" when change is TTL-only

- documentation/providers/axfrddns.md
- integrationTest/integration_test.go
- integrationTest/providers.json
- providers/axfrddns/axfrddnsProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/1913
These are some fixes for the experimental branch `tlim_corrector`. It also includes some minor code improvements and a fix for #1913 .
> AXFRDDNS: Fix integration tests

- providers/ns1/ns1Provider.go
It was discovered in #2217 that, as of recently, NS1 may return nameservers
with a trailing dot. Attempting to fix, we discovered that this creates
another bug, #2254. This is triggered when NS1 returns entries without a dot,
which happens when new zones are created.
Dnscontrol is opinionated and always adds trailing dots to nameservers.
So, instead of picking one out of models.ToNameservers/ToNameserversStripTD()
and breaking one case every time, let's add some code that covers both cases:
* If dots exist, remove them and then submit the clean array to ToNameservers().
* If not, just pass the original nameserver to ToNameservers().
Dnscontrol will then ensure that trailing-dotted versions are configured into
NS1 for all managed domains and remove this inconsistency.
Fixes #2254
> NS1: Handle assigned nameservers better

- providers/namecheap/auditrecords.go
- providers/namecheap/namecheapProvider.go
> Namecheap resolve test issues

- providers/akamaiedgedns/akamaiEdgeDnsProvider.go
% go test -v -verbose -timeout 15m -provider AKAMAIEDGEDNS
--- PASS: TestDNSProviders/svernick-new.com/26:LOC:Single_LOC_record (1.30s)
--- PASS: TestDNSProviders/svernick-new.com/26:LOC:Update_single_LOC_record (1.32s)
--- PASS: TestDNSProviders/svernick-new.com/26:LOC:Multiple_LOC_records-create_a-d_modify_apex (2.53s)
PASS
ok  	github.com/StackExchange/dnscontrol/v3/integrationTest	281.226s
> Can use LOC

- documentation/bug-triage.md
- documentation/providers.md
> Update "provider request" docs

- .circleci/config.yml
enable integration tests to run for NS1 if secrets are configured.
> CI: BYO secrets for NS1

- providers/hetzner/api.go
```
$ golint ./...
providers/hetzner/api.go:240:9: if block ends with a return statement, so drop this else and outdent its block
```
> HETZNER: Clean up lint warning

- providers/ns1/ns1Provider.go
> Fix NS1_URLFWD custom record type handling

- providers/cloudns/cloudnsProvider.go
CC @pragmaton for visibility.
A recent change broke NS1.  CLOUDNS did something similar, so I'm going to make an equivalent change for CLOUDNS.
Can you please test this?
> CLOUDNS: Fix WR type

- integrationTest/integration_test.go
- pkg/diff2/diff2.go
- pkg/zonerecs/zonerecords.go
- providers/route53/route53Provider.go
> Integration tests should test diff2's IGNORE*

- providers/ns1/ns1Provider.go
Previous testing was done with dnscontrol preview only. Lesson learnt.
> NS1: Fix NS1_URLFWD records push

- providers/transip/transipProvider.go
By using the original record for deletions we ensure TransIP will remove the correct record
Fixes #2323
> Fix TransIP record deletion by using original record for deletion

- .github/workflows/build.yml
> Regularlize the env/secrets

- go.mod
- integrationTest/integration_test.go
> CHORE: Move NS test to its own function

- integrationTest/integration_test.go
- models/domain.go
- pkg/diff2/analyze_test.go
- pkg/normalize/validate.go
- pkg/soautil/soautil_test.go
- providers/bind/bindProvider.go
- providers/cloudflare/cloudflareProvider.go
- providers/cscglobal/api.go
- providers/desec/protocol.go
- providers/loopia/types.go
- providers/namedotcom/records.go
- providers/netcup/api.go
- providers/netcup/types.go
- providers/ovh/protocol.go
- providers/rwth/api.go
- providers/vultr/convert_test.go
- staticcheck.conf
Hi! Issue with Staticcheck was fixed (https://github.com/dominikh/go-tools/issues/810),
so I tried to unmask disabled `U1000` check and satisfy Staticcheck
with correcting a couple of names and removing unused code fragments.
Will be glad to make any changes to meet your guidelines :)
> CHORE: Satisfy Staticcheck and remove unused code

- pkg/diff2/compareconfig.go
> verifyCNAMEAssertions should warn, not panic

- build/generate/functionTypes.go
- commands/types/dnscontrol.d.ts
- documentation/functions/domain/CLOUDNS_WR.md
- documentation/functions/domain/NS1_URLFWD.md
They went to the old doc site, but the new one has different URLs (that don’t seem to correspond to anything directly in the source files?)
> Fix doc URLs in .d.ts file

- .github/workflows/release.yml
> Remove bruceadams/get-release

- .github/workflows/build.yml
- .github/workflows/draft_release.yml
- .github/workflows/release.yml
- commands/commands.go
> BUG: "dnscontrol version" not working

- integrationTest/integration_test.go
> TESTING: Mark 'IGNORE_TARGET b2285' as diff2-only

- documentation/code-tricks.md
- documentation/examples.md
Fixes https://github.com/StackExchange/dnscontrol/issues/2339
> DOCS: Document functions that return lists

- documentation/getting-started.md
> DOCS: Improve docker example

- documentation/examples.md
> DOCS: Fix formatting error (missing endcode)

- .goreleaser.yml
> ci: Remove duplicate goreleaser docker build

- .github/workflows/release.yml.DISABLED
> ci: Disable old release process

- providers/axfrddns/axfrddnsProvider.go
> AXFRPROVIDER: Don't count "reports" as a change

- documentation/examples.md
> DOCS: Fix quote and a broken link

- documentation/SUMMARY.md
- documentation/code-tricks.md
Added `M365_BUILDER()` to the menu structure and `Useful code tricks`.
> DOCS: Added `M365_BUILDER()` to menu and code tricks

- documentation/examples.md
@cafferata 
(This time I'll be patient and wait for the review)
> DOCS: More fixes

- providers/inwx/auditrecords.go
> INWX: Enabling TXT with 255 bytes works

- documentation/ci-cd-gitlab.md
- documentation/get-certs.md
- documentation/getting-started.md
- documentation/notifications.md
- documentation/providers/akamaiedgedns.md
- documentation/providers/axfrddns.md
- documentation/providers/azure_dns.md
- documentation/providers/dnsmadeeasy.md
- documentation/providers/hedns.md
- documentation/providers/hexonet.md
- documentation/providers/inwx.md
- documentation/providers/route53.md
Fixed the various `creds.json` examples.
> DOCS: Fixed creds.json example

- go.mod
- go.sum
> CHORE: Update dependencies

- providers/autodns/autoDnsProvider.go
> AUTODNS: Guard against conversion errors

- documentation/providers/bind.md
- providers/bind/bindProvider.go
> BIND: Automatically create the subdirectories leading up to zonefiles

- documentation/styleguide-code.md
> DOCUMENTATION: Add JSDoc info to style guide

- commands/printIR.go
- pkg/js/js.go
- pkg/js/js_test.go
> CHORE: Rename js.Javascript to js.JavaScript

- providers/bind/bindProvider.go
> BIND: reset zonefile for reading records

- models/t_parse.go
- models/t_txt.go
- providers/gcloud/gcloudProvider.go
- providers/hedns/hednsProvider.go
- providers/route53/route53Provider.go
> CHORE: Eliminate SetTargetTXTString()

- .github/workflows/draft_release.yml
- .goreleaser.yml
Reverts StackExchange/dnscontrol#2408
> Revert "Also push container images to github / gcr.io"

- documentation/providers.md
As requested in https://github.com/StackExchange/dnscontrol/issues/1668#issuecomment-1579739374
> INWX: Update providers.md maintainer

- documentation/assets/getting-started/dnsconfig.js
- documentation/functions/domain/A.md
- documentation/functions/domain/AAAA.md
- documentation/functions/domain/ALIAS.md
- documentation/functions/domain/CAA.md
- documentation/functions/domain/CNAME.md
- documentation/functions/domain/DS.md
- documentation/functions/domain/DefaultTTL.md
- documentation/functions/domain/INCLUDE.md
- documentation/functions/domain/MX.md
- documentation/functions/domain/NAMESERVER_TTL.md
- documentation/functions/domain/NAPTR.md
- documentation/functions/domain/NS.md
- documentation/functions/domain/SOA.md
- documentation/functions/domain/SRV.md
- documentation/functions/domain/TLSA.md
- documentation/functions/global/D.md
- documentation/functions/global/DEFAULTS.md
- documentation/functions/global/DOMAIN_ELSEWHERE.md
- documentation/functions/global/FETCH.md
- documentation/functions/global/REV.md
- documentation/functions/global/require.md
- documentation/functions/record/TTL.md
- documentation/getting-started.md
Pull request nr. 3 for https://github.com/StackExchange/dnscontrol/issues/2387.
_Please merge after approval so that no unnecessary conflicts arise._ 🙏
> DOCS: The Javascript code examples are no longer tied to a DNS provider

- integrationTest/integration_test.go
- providers/bind/bindProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/2435
> BUG: BIND not handling long TXT records correctly

- commands/types/dnscontrol.d.ts
- go.mod
- go.sum
- providers/hexonet/error.go
- providers/hexonet/hexonetProvider.go
Fixes https://github.com/StackExchange/dnscontrol/issues/2223
dnscontrol.d.ts file changes are related to "go generate ./..." command
Relates to #2223
> HEXONET: Updated GO-SDK to the latest version

- README.md
> ANNOUNCEMENT: Proposal to no longer generate 32-bit binaries

- build/build.go
- go.sum
- providers/cscglobal/api.go
- FEATURE: Added backoff rate limiting for CSCGlobal
- BUGFIX: Cleaning up typoed Errorf format string
- MAINT: Updating go.mod
- BUGFIX: Adjusting rate limit backoff and maxBackoff down because it is a requests per second limit rather than call rate over time on CSCGlobal
```
******************** Domain: REDACTED
2023/07/31 19:34:33 api.go:667: Delaying 5s due to ratelimit
```
> FOUND-1643: FEATURE: Adding rate limit to CSCGlobal

- .github/workflows/draft_release.yml
- Dockerfile
* Upgrade to alpine:3.18.2
* Fix dockerfile (use individual commands, not "&&")
> CHORE: Fix release automation

- documentation/functions/global/require.md
- documentation/functions/global/require_glob.md
> Improve require() docs

- pkg/diff2/handsoff_test.go
> TESTING: handoff() tests should disable NO_PURGE

- documentation/getting-started.md
Small improvement where the Docker command is aligned.
> DOCS: Align Docker command

- documentation/getting-started.md
- documentation/providers/loopia.md
Small typo `Github` = `GitHub`.
> DOCS: Typo GitHub

- pkg/normalize/validate.go
- providers/cscglobal/api.go
> CSCGLOBAL: Be silent about backoffs less than 10s

- .github/workflows/build.yml
- .github/workflows/draft_release.yml
- .github/workflows/release.yml.DISABLED
> CHORE: Increase minimum Go version to 1.21

- providers/gcore/convert.go
Fix TXT record double quoting reported in #2591
> GCORE: fix TXT record double quoting

- commands/types/dnscontrol.d.ts
> dnscontrol.d.ts: fix DOMAIN_ELSEWHERE_AUTO signature

- providers/gcloud/gcloudProvider.go
> GCLOUD: Remove extra newline

- commands/completion_test.go
> CHORE: lint

- models/dns.go
- models/dnsrr.go
- models/quotes_test.go
- models/record.go
- models/t_txt.go
- models/target.go
- pkg/diff/diff.go
- pkg/diff/diff2compat.go
- pkg/txtutil/txtutil.go
- providers/powerdns/convert.go
> REFACTOR: Add Joined and Segmented accessors to TXT, and other cleanups

- commands/gz_test.go
- documentation/providers/azure_dns.md
- pkg/diff/diff2compat.go
- pkg/diff2/compareconfig.go
- pkg/normalize/validate_test.go
- pkg/rejectif/txt.go
- providers/desec/desecProvider.go
- providers/powerdns/auditrecords.go
- providers/transip/auditrecords.go
> CHORE: More cleanups

- integrationTest/integration_test.go
> RType AAAA: Add integration test for AAAA.

- documentation/adding-new-rtypes.md
- documentation/integration-tests.md
- documentation/providers/cloudflareapi.md
- documentation/providers/hexonet.md
- documentation/writing-providers.md
> DOCS: Warn against common integration test mistake

- documentation/providers.md
Fixed the maintainer of provider `OPENSRS` conform `OWNERS`:
https://github.com/StackExchange/dnscontrol/blob/37e21030a21089b8989786caa0792fb7f349582a/OWNERS#L37
> DOCS: Fixed the maintainer of provider `OPENSRS`

- documentation/providers/msdns.md
Fixes https://github.com/StackExchange/dnscontrol/issues/2621
> MSDNS: Remove pssession from docs (it doesn't work)

- documentation/integration-tests.md
The [Zoo](https://www.npmjs.com/package/zoo) cross-platform environment variables package no longer exists on GitHub: https://github.com/jsonmaur/zoo.
> DOCS: Removed the Zoo cross-platform environment variables package

- pkg/diff2/diff2.go
- pkg/dnsgraph/dependencies.go
- pkg/dnsgraph/dnsgraph.go
- pkg/dnsgraph/graphable.go
- pkg/dnsgraph/testutils/stubrecords.go
- pkg/dnssort/result.go
- pkg/txtutil/txtcode.go
- providers/gcore/gcoreExtend.go
- providers/mythicbeasts/mythicbeastsProvider.go
- providers/porkbun/listzones.go
> CHORE: Fix golint and staticcheck errors/warnings

- commands/previewPush.go
- pkg/diff2/handsoff.go
- pkg/printer/printer.go
> FEATURE: Add experimental --reportmax flag

- pkg/js/helpers.js
Fixes https://github.com/StackExchange/dnscontrol/issues/2457
> BUG: Fix M365 Builder indexOf error

- documentation/providers/ovh.md
Documenting a few caveats for the `ovh` provider.
> DOCS: Updates to `ovh` provider page

- commands/types/dnscontrol.d.ts
- pkg/rejectif/txt.go
- providers/dnsimple/auditrecords.go
- providers/msdns/auditrecords.go
- providers/msdns/msdnsProvider.go
> MSDNS: Fix failing DNS integration tests

- documentation/opinions.md
Small docs update: this section seemed like it was meant to be a list, so I added hyphens to it.
Thank you all for your work on this project! 🙏
> Docs: Use bullet list in opinion 2

- .github/workflows/pr_test.yml
> CICD: External PRs should not fail

- go.mod
Fixes https://github.com/StackExchange/dnscontrol/issues/2765
> CICD: Retract v4.8.0

- .github/workflows/pr_test.yml
- .goreleaser.yml
- OWNERS
- README.md
- documentation/SUMMARY.md
- documentation/providers.md
- documentation/providers/bunny_dns.md
- integrationTest/providers.json
- providers/_all/all.go
- providers/bunnydns/api.go
- providers/bunnydns/auditrecords.go
- providers/bunnydns/bunnydnsProvider.go
- providers/bunnydns/convert.go
- providers/bunnydns/listzones.go
- providers/bunnydns/records.go
Thank you for this great project! I was interested in implementing Bunny DNS for my own needs and also saw that a provider request has been opened a while ago as #2265, so I decided to give this a shot. For a first implementation, I decided to postpone processing any special records, just to keep the scope of this PR somewhat reasonable and to get the basics up and running.
I've read through all the docs and hope that I got things mostly right. I hereby also agree to the expected duties of a maintainer and added myself accordingly to the code owners file. Additionally, I also manually verified proper handling of TXT records as requested in the docs. Let me know what needs changing and thanks in advance for a review.
As a side note, I did read the remarks about not conditionally adding or …
> NEW PROVIDER: Bunny DNS (#2265)

- main.go
> (Though, we should add the word "version" to be like go, git, gh, etc).
_Originally posted by @tlimoncelli in https://github.com/StackExchange/dnscontrol/issues/2766#issuecomment-1879253834_
```shell
go build
```
```text
DNSControl version dev
```
```shell
goreleaser build --snapshot --clean
```
<details>
<summary>GoReleaser output</summary>
```shell
• starting build...
• loading                                          path=.goreleaser.yml
• skipping validate...
• loading environment variables
• getting and validating git state
• git state                                      commit=24b646549284ef88660a37e89be14998d428ba61 branch=cicd/goreleaser-version current_tag=v4.7.4 previous_tag=v4.7.3 dirty=true
• pipe skipped                                   reason=disabled during snapshot …
```
> CICD: GoReleaser version - part 3

- documentation/providers/transip.md
Described the TransIP API limitations noted from https://github.com/StackExchange/dnscontrol/issues/2788#issuecomment-1887513343.
Fixes https://github.com/StackExchange/dnscontrol/issues/2788
> DOCS: TransIP - Described API limitations

- commands/types/dnscontrol.d.ts
- documentation/providers.md
Generated documentation:
* https://github.com/StackExchange/dnscontrol/pull/2802
Generated TypeScript:
* https://github.com/StackExchange/dnscontrol/pull/2790
* https://github.com/StackExchange/dnscontrol/pull/2792
_PS. I'll see if I can port these processes to GitHub actions next week. Saves work/GitHub pull requests._
> CHORE: Missed generated content

- documentation/providers/realtimeregister.md
> DOCS: realtimeregister: Add security advice about creds

- go.mod
- go.sum
> CHORE: Update deps

- go.mod
- go.sum
- pkg/powershell/LICENSE
- pkg/powershell/README.md
- pkg/powershell/backend/local.go
- pkg/powershell/backend/ssh.go
- pkg/powershell/backend/types.go
- pkg/powershell/middleware/session.go
- pkg/powershell/middleware/session_config.go
- pkg/powershell/middleware/types.go
- pkg/powershell/middleware/utf8.go
- pkg/powershell/shell.go
- pkg/powershell/utils/quote.go
- pkg/powershell/utils/quote_test.go
- pkg/powershell/utils/rand.go
- pkg/powershell/utils/rand_test.go
- providers/msdns/powershell.go
go-powershell is no longer supported.  In case it disappears from github, I'm vendoring it.
> CHORE: Vendor go-powershell

- providers/cloudflare/cloudflareProvider.go
* Cloudflare: Allow adding NS records for base domain (Fixes #2863)
> CLOUDFLAREAPI: Permit adding NS records to apex domain

- integrationTest/integration_test.go
> TESTING: Bug: integration tests ignore 'type' in ignoreTarget

- .github/workflows/pr_test.yml
- .github/workflows/release_draft.yml
> DEV: Upgrade to go 1.22.x

- go.mod
- go.sum
> DEV: Adopt go 1.22.1 as minimum compiler version

- documentation/SUMMARY.md
- documentation/preview-push.md
> Add documentation for preview/push

- documentation/preview-push.md
Post-feedback on GitHub pull request https://github.com/StackExchange/dnscontrol/pull/2884
> DOCS: Commands preview/push

- documentation/providers.md
- providers/gcore/gcoreProvider.go
Closes #2889
* GCORE: Allow to add PTR records
> GCORE: Allow PTR records

- documentation/fmt.md
- documentation/globalflags.md
- documentation/preview-push.md
Feedback for GitHub pull request https://github.com/StackExchange/dnscontrol/pull/2886
> DOCS: Feedback missing docs for fmt, global flags, preview-push

- pkg/prettyzone/prettyzone_test.go
> DEV: Fix broken DNAME test

- build/generate/featureMatrix.go
- commands/getZones.go
- commands/types/dnscontrol.d.ts
- documentation/SUMMARY.md
- documentation/adding-new-rtypes.md
- documentation/language-reference/domain-modifiers/DNSKEY.md
- documentation/providers.md
- integrationTest/integration_test.go
- models/dnsrr.go
- models/domain.go
- models/record.go
- models/t_dnskey.go
- models/t_parse.go
- models/target.go
- pkg/js/helpers.js
- pkg/js/parse_tests/048-DNSKEY.js
- pkg/js/parse_tests/048-DNSKEY.json
- pkg/normalize/validate.go
- pkg/prettyzone/prettyzone_test.go
- pkg/prettyzone/sorting.go
- providers/bind/bindProvider.go
- providers/capabilities.go
- providers/capability_string.go
- providers/desec/desecProvider.go
> NEW RECORD TYPE: DNSKEY

- documentation/adding-new-rtypes.md
> DOCS: Remind devs to run go generate

- providers/netlify/netlifyProvider.go
> NETLIFY: add support for listing all zones

- documentation/release-engineering.md
> DOCS: Clarify RE doc

- integrationTest/integration_test.go
> CICD: De-conflate integration test for SVCB and HTTPS

- documentation/examples.md
Removed the double Markdown header syntax.
> DOCS: Removed the double Markdown header syntax.

- models/domain.go
> CHORE: Clean up comments in models/domain.go

- documentation/providers.md
- providers/cloudflare/cloudflareProvider.go
- providers/cloudflare/rest.go
> CLOUDFLAREAPI: Enable DNSKEY, HTTPS, SVCB record types

- documentation/providers.md
- providers/cloudflare/cloudflareProvider.go
> CLOUDFLAREAPI: disable DNSKEY until it is fixed

- commands/types/dnscontrol.d.ts
- commands/types/others.d.ts
- documentation/language-reference/top-level-functions/require.md
- pkg/js/js.go
- pkg/js/parse_tests/049-json5-require.js
- pkg/js/parse_tests/049-json5-require.json
- pkg/js/parse_tests/domain-ip-map.json5
Work based on a PR by @charliez0
> FEATURE: Enable "require()" function to accept json5 files

- .github/workflows/pr_test.yml
- documentation/provider/huaweicloud.md
- integrationTest/providers.json
- providers/huaweicloud/convert.go
- providers/huaweicloud/huaweicloudProvider.go
- providers/huaweicloud/records.go
add support for geodns and weighted routing
> HUAWEICLOUD: add metadata to control Intelligent Resolution

- documentation/SUMMARY.md
- documentation/language-reference/domain-modifiers/CF_SINGLE_REDIRECT.md
Documentation improvements for GitHub pull request https://github.com/StackExchange/dnscontrol/pull/3035
> DOCS: CLOUDFLAREAPI - CF_SINGLE_REDIRECT

- commands/types/dnscontrol.d.ts
- pkg/rtypes/postprocess.go
Fixes https://github.com/StackExchange/dnscontrol/issues/3040
> BUGFIX: Remove debug statement left in by mistake

- pkg/js/helpers.js
> fmt helpers.js

- README.md
- documentation/release-engineering.md
> Gitter - Drop communication channel

- go.mod
- go.sum
> NS1: update ns1-go to 2.12.0

- documentation/language-reference/domain-modifiers/NS1_URLFWD.md
> DOCS: add docs for NS1_URLFWD

- .github/workflows/pr_test.yml
This PR adds SAKURACLOUD to automated tests.
Credentials previously sent can be used.
> SAKURACLOUD: Add SAKURACLOUD to automated tests

- .gitignore
- commands/types/dnscontrol.d.ts
- documentation/language-reference/domain-modifiers/NAMESERVER.md
> DOCS: Minor clarifications on NAMESERVER()

- documentation/providers.md
- providers/cloudns/api.go
- providers/cloudns/cloudnsProvider.go
This change adds AUTODNSSEC support for ClouDNS.
> CLOUDNS: implement AutoDNSSEC (#747)

- providers/oracle/oracleProvider.go
> ORACLE: BUGFIX: Support accounts with > 50 zones

- .github/workflows/pr_test.yml
- OWNERS
- README.md
- documentation/provider/cnr.md
- documentation/providers.md
- go.mod
- go.sum
- integrationTest/providers.json
- providers/_all/all.go
- providers/cnr/auditrecords.go
- providers/cnr/cnrProvider.go
- providers/cnr/domains.go
- providers/cnr/error.go
- providers/cnr/nameservers.go
- providers/cnr/records.go
> NEW PROVIDER: CentralNic Reseller (CNR) - formerly RRPProxy

- commands/getZones.go
- commands/test_data/apex.com.zone.js
- commands/test_data/ds.com.zone.js
- commands/test_data/example.org.zone.js
- commands/test_data/simple.com.zone.js
Fixes https://github.com/StackExchange/dnscontrol/issues/3251
> ENHANCEMENT: get-zones: No longer generate END tokens

- documentation/test-a-branch.md
The feedback from https://github.com/StackExchange/dnscontrol/pull/3264#issuecomment-2555559469 in a new GitHub pull request ☺️
> DOCS: How to test a branch (feedback)

- .github/workflows/pr_build.yml
- .github/workflows/pr_integration_tests.yml
- .github/workflows/release_draft.yml
Issue:
When viewing the ACTIONS page (https://github.com/StackExchange/dnscontrol/actions) my eyes don't easily pick out which test is being run.
Resolution:
UPPERCASE key words in the workflow names.
> CI/CD: Make titles easier to read

- .github/workflows/pr_integration_tests.yml
- providers/mythicbeasts/auditrecords.go
Here's the PR part of https://github.com/StackExchange/dnscontrol/issues/3276.
> MYTHICBEASTS: Add MYTHICBEASTS to automated tests

- providers/mythicbeasts/auditrecords.go
Issue:
providers/mythicbeasts/auditrecords.go wasn't run through gofmt
Resolution:
gofmt providers/mythicbeasts/auditrecords.go
> MYTHICBEASTS: CHORE: fix code formatting

- integrationTest/integration_test.go
> CHORE: Remove debug statements

- integrationTest/integration_test.go
- integrationTest/profiles.json
Minor fixes in the AXFRDDNS integration tests.
> TESTING:  Improve AXFRDDNS integration tests

- models/cloudflare_types.go
- models/rawrecords.go
- models/t_mx.go
- models/t_parse.go
- models/t_srv.go
- models/target.go
- models/typeregister.go
- models/types.go
- providers/msdns/powershell_test.go
- PopulateARaw() -> PopulateFromRawA()
- PopulateAFields() -> PopulateFieldsA()
- MakeFromRawA() -> NewFromRawA()
(and similar for other types)
> REFACTOR: rename based on new standard

- providers/transip/transipProvider.go
- This will update the whole zone at once instead of pushing record by record. This is possible due to new features in the diff2 package. Fixes #3343 
- I also fixed how Nameservers on the domain are registered and filters them from the records to push. Fixes #3361 
I did not run the integration tests, not because I am lazy, but because I am this confident in the DNSControll code. ;) I did test it manually with my own TransIP domains and some fabricated records. As you can see from the diff most manual work has been removed and now we mostly rely on DNSControl to do all the heavy lifting, which is a-ma-zing.
> TRANSIP: Change to zone-based updates to dramatically improve speed of updates

- providers/inwx/inwxProvider.go
INWX permits SRV records to have "." but requires updates to other code to enable.
Fix as needed
> INWX: Enable SRV to have "." target (rubgfx's fix)

- integrationTest/integration_test.go
> GCLOUD: remove (irrelevant) slow test

- integrationTest/integration_test.go
> CICD: Make pager tests more visible

- documentation/provider/index.md
> DOCS: fix link to writing-providers.md

- build/autotype/autotype.go
- build/autotype/catalog.go
- build/autotype/hints.go
- build/autotype/makers.go
- build/autotype/tags.go
- models/generated_types.go
- models/rawrecords.go
> generate ImportFromLegacy()

- build/autotype/autotype.go
- build/autotype/catalog.go
- build/autotype/hints.go
- build/autotype/makers.go
- models/generated_types.go
- models/types.go
- providers/cloudflare/customtypes/structs.go
> automate Seal()

- build/autotype/hints.go
- build/autotype/makers.go
- integrationTest/generated_helpers.go
- integrationTest/helpers_integration_test.go
- models/generated_types.go
- models/t_naptr.go
- pkg/fieldtypes/fieldtypes.go
- pkg/js/helpers-types.js
- pkg/js/parse_tests/035-naptr.js
- pkg/js/parse_tests/035-naptr.json
- pkg/js/parse_tests/035-naptr/foo.com.zone
> automate NAPTR

- commands/types/dnscontrol.d.ts
- models/record.go
> BUG: fix panic message

- bin/generate-all.sh
- documentation/release-engineering.md
The number of steps to rebuild, reformat, etc various files was growing
Move it to a shell script.
> BUILD: Move regen steps to a script

- commands/types/dnscontrol.d.ts
- documentation/language-reference/domain-modifiers/CF_SINGLE_REDIRECT.md
- providers/cloudflare/rtypes/cfsingleredirect/cfsingleredirect.go
CF_SINGLE_REDIRECT's 2nd argument should be any of the redirect codes, not just 301/302.
Permit other codes.
> feat(cloudflare) SINGLE_REDIRECT permits more than 301/302 redirects

- documentation/provider/index.md
Added Netim https://github.com/StackExchange/dnscontrol/issues/3511 to the list of requested providers.
> DOCS: Added requested providers Netim

- providers/inwx/inwxProvider.go
This adds special handling of MX records for INWX. The API rejects record updates that violate RFC 7505: if a Null MX RR is present in the zone, new regular MX records are rejected. The inverse is also rejected - if MX records exist in the zone, a Null MX record can not be added.
Separately from the Null MX issue, changes to MX preference from non-zero to zero are accepted by the API but not applied, leading to inconsistent state between the dnscontrol configuration and the published zone.
Related to #2800
> INWX: Fix Null MX handling

- providers/desec/convert.go
- providers/desec/desecProvider.go
This pull request makes some adjustments to the deSEC provider to properly handle unicode domains by encoding them as punycode when necessary.
> DESEC: Properly support punycode domains

- README.md
- documentation/provider/porkbun.md
> DOCS: Add Porkbun as supported registrar and update usage examples

- documentation/provider/index.md
Added Sav.com #3633 to the list of requested providers.
> DOCS: Added requested provider Sav.com

- providers/dnsimple/dnsimpleProvider.go
While updating the docs on what CanConcur means, I realised that the
`.accountID` field in `dnsimpleProvider` is a cache and subject to races.  It
will always be assigned the same value, and a `-race` build didn't catch it,
but it wasn't strictly correct to just declare this provider to be
concurrency-safe.
So use `sync.Once` to properly protect the account ID field update.
> DNSIMPLE: pedantic correctness fix for concurrency

- documentation/provider/index.md
- integrationTest/integration_test.go
- providers/capabilities.go
- providers/loopia/auditrecords.go
- providers/loopia/loopiaProvider.go
Updated feature compatibility matrix
Threw in some spell fixes in separate commit. Can split out if needed.
> Loopia: feature updates

- documentation/getting-started/getting-started.md
- documentation/language-reference/top-level-functions/D.md
This PR addresses feedback and resolves issues identified in https://github.com/StackExchange/dnscontrol/pull/3691.
**Before**
_https://docs.dnscontrol.org/getting-started/getting-started#id-7.-use-your-own-domains_
**After**
_https://docs.dnscontrol.org/~/revisions/dmy8wDZdCApklSflB4X0/getting-started/getting-started#id-7.-use-your-own-domains_
> DOCS: Getting started get-zones (feedback)

- docs/index.md
There are no links to the test-a-branch page
Add a link on the homepage.
> DOCS: Add link on homepage to test-a-branch

- providers/axfrddns/axfrddnsProvider.go
> AXFRDDNS: Fix spurious AUTODNSSEC warnings

- documentation/provider/adguardhome.md
@ishanjain28 I’ve left some small feedback and suggested a few minor improvements for your merged PR: https://github.com/StackExchange/dnscontrol/pull/3638
You can preview these changes here: https://docs.dnscontrol.org/~/revisions/XevZdp91OtBwnATDQIUx/provider/adguardhome
Let me know what you think.
> DOCS: AdGuardHome feedback

- providers/realtimeregister/api.go
- providers/realtimeregister/realtimeregisterProvider.go
> REALTIMEREGISTER: Allow 0 prio for MX records

- documentation/provider/index.md
Added Yandex Cloud DNS #3737 to the list of requested providers.
> DOCS: Added requested provider Yandex Cloud DNS

- providers/namecheap/namecheapProvider.go
resolves #3685 
Thankfully this was a copy paste job from another provider and did not require updating the library.
I couldn't see if there was a test for this but I built and ran against my sandbox user and it worked without any issues so I think this is all that was required.
> NAMECHEAP: Enable get-zones
