StackExchange/dnscontrol

main.go

Changed multiple fmt.Println("") commands to one using backticks

Redundant use of multiple fmt.Println commands

---

docs/_providers/bind.md
docs/getting-started.md
integrationTest/providers.json
integrationTest/zones/example.com.zone
main.go
providers/bind/bindProvider.go
providers/config/providerConfig.go
providers/providers.go

Relaxes a few things to make getting started easier.
1. Don't strictly need a `creds.json`. I it is not there, or a provider not in it, it is up to the provider to complain it does no thave the config it needs.
2. "bind" is no longer a default skipped provider. We need to update our own scripts to work around this.
3. Getting started now runs a simple bind domain.

Update bind docs and Getting Started

---

docs/getting-started.md

This appears to be the only one.  Manual audit with (zsh):
pcregrep -o1 '}}/([^\)]+)\)' **/*(.)
yielded all the site-based URLs and I eye-compared them to the names of
existing docs.

Fix broken doc-link from getting-started

---

docs/_providers/cloudflare.md
docs/_providers/gandi.md

- Clarify what "apiuser" is in Cloudflare docs. Confusingly it is the email address associated with the account, not the username.
- Remove Gandi registrar, because it doesn't actually exist.

Docs fixes

---

misc/convertzone/main.go
providers/bind/bindProvider.go
providers/bind/prettyzone.go
providers/bind/prettyzone_test.go

The `$TTL` value should be automatically selected. 
This fixes https://github.com/StackExchange/dnscontrol/issues/80

BIND Provider: Pick default TTL automatically for zonefiles

---

providers/activedir/domains.go
providers/cloudflare/cloudflareProvider.go
providers/diff/diff.go
providers/diff/diff_test.go

Turns out this was a little tricky. We want to ignore record sets that exist in the provider but not in our config. At the same time, if we go from 2 A records to 1, we want to be able to do that. Tests should cover it.

NO_PURGE honored globally

---

docs/js.md

Typo: 'consturct' --> 'construct'.

Fix small typo in Javascript DSL document

---

vendor/github.com/billputer/go-namecheap/Makefile
vendor/github.com/billputer/go-namecheap/dns.go
vendor/vendor.json

upstream fix applied via https://github.com/billputer/go-namecheap/pull/6

fix go-namecheap vendor, already applied upstream

---

docs/_providers/name.com.md
docs/_providers/namecheap.md
docs/_providers/route53.md

There were several doc files that were using ROUTE53 as a raw token instead of string.  This commit is just adding double quotes to make the documentation consistent.

Update docs to properly use ROUTE53 in examples

---

pkg/normalize/validate.go

_amazonses record is used by [Amazon SES to verify domain](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/dns-txt-records.html).
This currently generate a warning "`WARNING: label _amazonses.example.com contains an underscore`"

Added _amazonses to list of allowed name with underscore

---

main.go

This allows dnscontrol to be able to be used with other tools that
support outputting to it's intermediate JSON format.
Closes #73

Support passing the JSON as a parameter

---

providers/route53/route53Provider.go

Fixes #150.
Correction messages are tracked in different variables between UPSERTs and DELETEs. Formerly, this lead to the wrong correction message (or a blank correction message) being printed when performing DELETEs.
I don't know if this is the correct idiomatic solution, but it does print the right messages now.

Route53 provider: Pass the right correction message based on action

---

providers/namedotcom/namedotcomProvider.go
providers/namedotcom/records.go

Name.com just implemented ALIAS records, which we are calling ANAME records to match with the current draft https://tools.ietf.org/html/draft-ietf-dnsop-aname-00.

add ALIAS support for Name.com provider

---

main.go

I found this was useful to avoid hitting overzealous rate limits.  I'm open to other approaches.

add delay option to work around rate limits

---

providers/bind/prettyzone.go
providers/bind/prettyzone_test.go

When one DNS name map to several PTR records, dnscontrol will crash with
```
CREATING ZONEFILE: zones/128_27.18.20.172.in-addr.arpa.zone
panic: zoneGenData Less: unimplemented rtype PTR
goroutine 1 [running]:
github.com/StackExchange/dnscontrol/providers/bind.(*zoneGenData).Less(0xc420598c90, 0x1, 0x0, 0x11)
/home/whs/build/go/src/github.com/StackExchange/dnscontrol/providers/bind/prettyzone.go:84 +0x921
sort.doPivot(0xf3ac20, 0xc420598c90, 0x0, 0x22, 0x30, 0xffffffffffffffff)
/usr/lib/go/src/sort/sort.go:119 +0xe9
sort.quickSort(0xf3ac20, 0xc420598c90, 0x0, 0x22, 0xc)
/usr/lib/go/src/sort/sort.go:192 +0x80
sort.Sort(0xf3ac20, 0xc420598c90)
/usr/lib/go/src/sort/sort.go:220 +0x79
github.com/StackExchange/dnscontrol/providers/bind.(*zoneGenData).generateZoneFileHelper(0xc420598c90, …
```

Added PTR record support for prettyzone

---

providers/route53/route53Provider.go

Two weeks ago, Amazon [announced](https://aws.amazon.com/about-aws/whats-new/2017/08/amazon-route-53-now-supports-caa-records/) support for the CAA record type to Route 53.
Fortunately, support for CAA was already addd to `dnscontrol` in https://github.com/StackExchange/dnscontrol/pull/161, which means it's just a matter of opting-in Route 53 to CAA using the CanUseCAA` flag.
I tested both adding, modifying, and removing records ( including record with the different types, e.g. `issue`, `issuewild`, `iodef`), and it all seems to work fine.

Opt-in Amazon Route 53 to CAA

---

docs/_providers/gcloud.md

Google now calls the required role "DNS Administrator" rather than "App Engine Admin"

gcloud provider doc update

---

docs/_functions/domain/CAA.md

I failed to update the docs in #193.

Update documentation to reflect that Route 53 supports the CAA record type

---

docs/_providers/activedir.md
docs/_providers/bind.md
docs/_providers/cloudflare.md
docs/_providers/digitalocean.md
docs/_providers/dnsimple.md
docs/_providers/gandi.md
docs/_providers/gcloud.md
docs/_providers/namecheap.md
docs/_providers/ns1.md
docs/_providers/route53.md
docs/_providers/softlayer.md

- Fixed indentation
- Use same naming scheme for all examples
(i.e. all caps for provider, REG prefix for registrar)
- Use REG_NONE as registrar when provider does not provide it
- Use example.tld for example domain
- Use 1.2.3.1/24 IP range for examples
- A few spelling fixes

Improved consistency of provider documentation

---

docs/_providers/activedir.md

- Grammar fixes
- Formatting fixes
See #221

Fixed Active Directory docs (#221)

---

docs/_providers/softlayer.md

- Add note that using the creds.json file is the preferred method of authentication
- Improve formatting
See #221

Improve softlayer documentation (#221)

---

README.md
docs/_includes/matrix.html
docs/_providers/vultr.md
docs/provider-list.md
integrationTest/providers.json
providers/_all/all.go
providers/vultr/convert_test.go
providers/vultr/vultr.go
vendor/github.com/JamesClonk/vultr/LICENSE
vendor/github.com/JamesClonk/vultr/lib/account_info.go
vendor/github.com/JamesClonk/vultr/lib/applications.go
vendor/github.com/JamesClonk/vultr/lib/block_storage.go
vendor/github.com/JamesClonk/vultr/lib/client.go
vendor/github.com/JamesClonk/vultr/lib/dns.go
vendor/github.com/JamesClonk/vultr/lib/firewall.go
vendor/github.com/JamesClonk/vultr/lib/ip.go
vendor/github.com/JamesClonk/vultr/lib/iso.go
vendor/github.com/JamesClonk/vultr/lib/os.go
vendor/github.com/JamesClonk/vultr/lib/plans.go
vendor/github.com/JamesClonk/vultr/lib/regions.go
vendor/github.com/JamesClonk/vultr/lib/reservedip.go
vendor/github.com/JamesClonk/vultr/lib/scripts.go
vendor/github.com/JamesClonk/vultr/lib/servers.go
vendor/github.com/JamesClonk/vultr/lib/snapshots.go
vendor/github.com/JamesClonk/vultr/lib/sshkeys.go
vendor/github.com/juju/ratelimit/LICENSE
vendor/github.com/juju/ratelimit/README.md
vendor/github.com/juju/ratelimit/ratelimit.go
vendor/github.com/juju/ratelimit/reader.go
vendor/vendor.json

I have added the Vultr provider. This PR includes full support for all supported features from Vultr (SRV, CAA, CreateDomains).
I have tested this with both the integration tests, and my own domain.
See issue #217

Added Vultr provider (#217)

---

docs/_providers/route53.md

- Grammar fixes
- Formatting improvements
- Don't encourage using environment vars instead of the credentials file
See #221

Improve Route53 documentation (#221)

---

OWNERS
README.md
docs/_includes/matrix.html
docs/_providers/ovh.md
docs/provider-list.md
integrationTest/integration_test.go
integrationTest/providers.json
providers/_all/all.go
providers/ovh/ovhProvider.go
providers/ovh/protocol.go
vendor/github.com/xlucas/go-ovh/LICENSE
vendor/github.com/xlucas/go-ovh/ovh/client.go
vendor/github.com/xlucas/go-ovh/ovh/doc.go
vendor/vendor.json

This adds the OVH provider along with its documentation:
A few comments:
* the provider unfortunately can't use `CanUsePTR` because OVH supports only setting PTR with a target in the arpa zone. This makes the integration tests 31 and 32 fail horribly (can we make those use the arpa zone?)
* OVH now supports setting apex NS records, so dual providers scenario can be accomplished 
* OVH doesn't support CAA (I'm going to ask them when they plan to support those).

OVH DNS Provider (#143)

---

pkg/normalize/validate.go

I am using [acme-dns](https://github.com/joohoi/acme-dns) which requires me to add a CNAME record on `_acme-challenge` to another domain name. This pull request removes the warning created when doing that.

Add _acme-challenge as an allowed record name

---

pkg/normalize/validate.go
pkg/normalize/validate_test.go

Prevents accidentally creating `foo.example.com.example.com` records. If you really really want to do that, you can still do:
`A('foo.example.com', '1.2.3.4', {skip_fqdn_check:"true"})`

validate: Check for fqdn labels

---

docs/_includes/matrix.html
models/dns.go
providers/cloudflare/cloudflareProvider.go
providers/cloudflare/rest.go
providers/vultr/vultrProvider.go

* If you add an CAA record in the web UI, then add the right CAA() statement in dnsconfig.js, things will work.
* dnscontrol push can not create new (or fix existing) CAA records.

CLOUDFLARE: Support CAA rtype

---

cmd/convertzone/main.go

* Handle TXT records with multiple strings in "dsl mode"
* Check for the right number of command line args.

convertzone: Handle TXT records with multiple strings

---

providers/route53/route53Provider.go

Apparently I've forgot to register the R53_ALIAS custom record
type, thus preventing to use R53_ALIAS in a js file.
The integration still worked fine because they probably don't run
the validation.
I'm very sorry for the trouble.

Fix #310 R53_ALIAS not being registered as custom type

---

providers/diff/diff.go

the `differ.matchIgnored` function was comparing only with the `Name`
field of `RecordConfig`.
Most providers don't set `RecordConfig.Name`, only `RecordConfig.NameFQDN`
and for those `IGNORE` doesn't work at all.
This patch converts `IGNORE` to use `NameFQDN` instead since it seems
all providers provides it.

Make IGNORE work with all providers

---

providers/namedotcom/records.go
providers/namedotcom/records_test.go

This fixes the tests. The integration tests work now too.
There were some small omissions and a double encoding at one point.
I also always forget about raw string literals, so I changed the strings to be more readable as well.
Also, I'll add this to our documentation on Monday, but for single TXT records, we don't require the double quotes at the beginning and end, and in that case it is a raw string so double quotes can exist anywhere inside the string on their own. For multiTXTs we surround them by double quotes and escape any double quotes inside with a backslash.

encode and decode name.com txt records

---

providers/diff/diff.go

As discussed in #312, after the refactor to generalize the use of `GetLabel`, this change makes IGNORE also use `GetLabel`.
Tested on provider OVH and Route 53.

Fix #312 - rewrite IGNORE to use GetLabel

---

integrationTest/providers.json
providers/linode/linodeProvider.go

In response to #323.
I've tested it with the Linode provider, and due to commit https://github.com/StackExchange/dnscontrol/commit/19ca7600726ba8251e4038bc6c94e004e55697de, the order of the integration tests have changed. So, the failing test's number has changed from 25 to 27 in `providers.json`.
Moreover, the integration test for TXT records does not pass anymore because fixTxt has been removed (https://github.com/StackExchange/dnscontrol/commit/de4455942bf38dc6b49e03b56748b00be5c062cf#diff-cbc2e007a10f561a01f36d383d88aa80R259), which the provider relied on.
All other integration tests pass.
This fixes all those problems, but I haven't been able to test whether `fixTxt` breaks other providers.

Fix Linode provider

---

providers/ovh/ovhProvider.go

OVH uses special SPF and DKIM invalid types for records added with the web ui (or default zone records).
The ovh provider didn't correctly handle those invalid record types and was panic'ing.
This change prevents the panic by converting such records to TXT (which is what they are in fact), but also auto-corrects any SPF or DKIM records to TXT ones so that next `push` will see no modifications.

Fix #339 prevent the ovh provider to panic on SPF and DKIM record types

---

pkg/normalize/validate.go

This just puts back the code as it was before until a correct and better fix is found :)

Fix #341 do not erase all records labels

---

commands/getCerts.go
docs/lets-encrypt.md
models/dns.go
pkg/acme/acme.go
pkg/acme/checkDns.go
pkg/acme/registration.go

More info to follow.
Current known needs:

Let's Encrypt Certificate Generation

---

.gitignore
pkg/normalize/validate.go
providers/activedir/domains.go

Transformed records were not given the correct fqdn.
For our transform to `.internal`, and src record `foo.stackexchange.com`, the transformed record is not getting the `.internal` added onto the end, so the fqdn is not inside the same zone.
This PR:
1. Fixes the bug in inport transform that creates the wrong fqdn.
2. Makes the AD provider use the standard diff messages that include fqdn.
3. Add a validation pass to make sure EVERY record has an fqdn that ends i the correct domain name.

fix names for internal transformed records

---

pkg/spflib/parse.go
pkg/spflib/parse_test.go

Hi,
Related to issues #355, I suspect it would only take a simple change of the handling for the ```exists:``` element to work, however I could be very wrong (and totally happy for you to tell me so).

Include support for exists element in SPF.

---

providers/cloudflare/cloudflareProvider.go

This fixes #367 by making `cfRecord` use a `json.Number` (to allow numbers to be parsed from strings) when parsing the Cloudflare API response.

Cloudflare: Fix parsing of priority field in record (fixes #367)

---

providers/dnsimple/dnsimpleProvider.go

The API isn't sorting the name servers so even when they match they would report being different. 
This will prevent it trying to update them every time
I tested this locally on my configuations

sort returned nameservers

---

providers/route53/route53Provider.go

While test-driving the Route 53 ALIAS record type, I noticed a little bug that prevents one from using multiple ALIAS records for the same record set name. For example, two ALIAS records for the record set name `www` with record set types `A` and `AAAA`, respectively.
```javascript
D("foo.bar", REGISTRAR, DnsProvider("ROUTE53"),
R53_ALIAS("www", "AAAA", "foo.cloudfront.net.", R53_ZONE("BAZ")),
R53_ALIAS("www", "A", "foo.cloudfront.net.", R53_ZONE("BAZ"))
);
```
If one would deploy this configuration, then only an ALIAS record set for `www` with record set type `A` would have been created. The first one (`www` with record set type `AAAA`) would have been skipped.
This is caused by the way the `updates` map in the example below is populated. The key (a struct) contains both a 'Name' (e.g. …

Fix bug in Route 53 ALIAS record

---

providers/cloudflare/cloudflareProvider.go

This fixes #371 and builds upon #368 and removes the casting error when the MX priority specified from CloudFlare is an empty string (```""```).
We might need to consider similar logic for SRV record priorities too.

Add support for MX priorities of "" (0)

---

pkg/spflib/parse.go
pkg/spflib/parse_test.go

SPF builder doesn't support PTR types.
I think PTR counts as a DNS lookup, but happy for more opinions on the matter.

Include PTR types in SPF Builder

---

docs/_providers/gandi.md

The `GANDI` provider also seems to be unable to see new domains (the
ones bought through the new interface), but I didn't mention that as
it may be a bug that could be solves at some point.

doc: update documentation for Gandi to mention the LiveDNS provider

---

pkg/acme/acme.go
pkg/acme/registration.go

`get-certs` currently fails with a permission denied after it creates new directories because MkdirAll is using 0644 instead of 0755. This PR resolves that.

Create directories with execute permissions so they can be opened

---

OWNERS
README.md
docs/_includes/matrix.html
docs/_providers/hexonet.md
integrationTest/providers.json
providers/_all/all.go
providers/hexonet/domains.go
providers/hexonet/error.go
providers/hexonet/hexonetProvider.go
providers/hexonet/nameservers.go
providers/hexonet/records.go
providers/hexonet/records_test.go
vendor/github.com/hexonet/go-sdk/CONTRIBUTING.md
vendor/github.com/hexonet/go-sdk/HISTORY.md
vendor/github.com/hexonet/go-sdk/LICENSE
vendor/github.com/hexonet/go-sdk/README.md
vendor/github.com/hexonet/go-sdk/apiconnector.go
vendor/github.com/hexonet/go-sdk/client/client.go
vendor/github.com/hexonet/go-sdk/client/socketcfg/socketcfg.go
vendor/github.com/hexonet/go-sdk/response/hashresponse/hashresponse.go
vendor/github.com/hexonet/go-sdk/response/hashresponse/templates.go
vendor/github.com/hexonet/go-sdk/response/listresponse/listresponse.go
vendor/github.com/hexonet/go-sdk/scripts/changelog.sh
vendor/github.com/hexonet/go-sdk/scripts/test-go.sh
vendor/github.com/hexonet/go-sdk/scripts/validate-go.sh
vendor/vendor.json

Ready to merge to get 1st release out :)

New Provider HEXONET

---

docs/provider-list.md

@captncraig 
just a minor fix, as we are missing in "Maintainers of contributed providers" list.
TIA!

Review Maintainers of contributed providers

---

models/record.go
models/record_test.go
providers/diff/diff.go
providers/route53/route53Provider.go

This mirrors logic in the R53 provider, and deals with spurious corrections in
the case that aliases exist for both A and AAAA records, which is common.
This also centralizes logic around keys to the models package and adds tests.

Correctly group R53_ALIAS records during IncrementalDiff.

---

Dockerfile
README.md

Can not build by go version under 1.9.
because using the strings.Builder by library.
https://github.com/StackExchange/dnscontrol/blob/36228949e9b6192f517708ea99d06481e7b18513/vendor/github.com/hexonet/go-sdk/client/socketcfg/socketcfg.go#L62
So update to 1.10 of docker image and README.md.

update go version to 1.10

---

commands/commands.go
commands/getCerts.go
commands/previewPush.go
pkg/js/js.go
pkg/printer/printer.go
pkg/printer/printer_test.go
providers/activedir/domains.go
providers/cloudflare/cloudflareProvider.go
providers/diff/diff.go
providers/gandi/gandiProvider.go
providers/gandi/livedns.go
providers/namecheap/namecheapProvider.go

This:
* adds a global -v flag for verbosity
* refactors the "printer" package to have a DefaultPrinter and package
functions that call it, similar to net/http's DefaultServeMux
* adds printer tests
* moves current users of Debugf to Printf
* moves most users of the "log" package to use "printer"
* demotes noticably noisy log messages to "Debugf", like "IGNORE"-
and "NO_PURGE"-related messages

Verbose debug logging via the ConsolePrinter and printer package.

---

integrationTest/providers.json
providers/dnsimple/dnsimpleProvider.go

This was broken when commenting out the MergeToTarget.
This gets us back to tests passing.
Fixes: #408

Fix DNSimple SRV and MX records

---

docs/_includes/matrix.html
providers/ovh/ovhProvider.go

We were caching the zones in GetNameservers which wasn’t a good idea, because this one might not be called if not name servers are selected for this ovh domain. 
In this case, GetDomainCorrections would fail with an unknown domain.
Instead the idea is to populate the zones cache as soon as the provider is initialized.

Populate ovh zones cache as early as possible (#412)

---

providers/config/providerConfig.go

This should help users with situations like https://github.com/StackExchange/dnscontrol/issues/423

Warn user if creds.json file does not exist

---

docs/_providers/cloudflare.md
providers/cloudflare/cloudflareProvider.go
providers/cloudflare/rest.go

This pull request adds two settings that can be set in the creds.json that allow you to specify the account where new domains should be added to. If the fields are left empty (the current situation) new domains end up in the account of the user the credentials belong to.
We bumped into this because the user that dnscontrol uses to push changes has access to multiple Cloudflare accounts and new domains we pushed ended up in the wrong account.

Added Cloudflare options for target account

---

docs/_providers/ovh.md

This fixes the URL to OVH's First Step Using The API guide, ~as well as a fix for the failing build on master~.

OVH url fix + green build

---

commands/previewPush.go

We want to offer a return-code oriented interface to detect changes
pending to be applied. The preview command, by default, returns 0
regardless of pending changes.
We add a flag, `--expect-no-changes`, that will return non-zero if
there are changes pending application, and 0 if there are none.
Fixes: #447

Add --expect-no-changes flag to preview

---

docs/_providers/gcloud.md
docs/_providers/route53.md
providers/gcloud/gcloudProvider.go
providers/route53/route53Provider.go

- Support DelegationSet for Route53 (create-domains only)
- Retry Route53 operations which fail for rate limits under large numbers of domains
- Support for name_server_set for GCloud (create-domains only)
- Docs for both

Delegation Sets and retries

---

providers/ovh/ovhProvider.go

Using CAA seems to work properly with the current implementation. Tested it using the CAA examples from the documentation just without any further issues:
```
CAA("@", "iodef", "mailto:test@example.com", CAA_CRITICAL),
CAA("@", "issue", "letsencrypt.org"),
CAA("@", "issuewild", ";"),
```

OVH does support CAA (and already works)

---

providers/digitalocean/digitaloceanProvider.go

My understanding is that SOA record is managed by Digitalocean automatically, so there is no reason to handle it here? And currently this is broken because code in `toRR` can't parse the target field.

Fix #479: Filter SOA records from Digitalocean

---

providers/ovh/ovhProvider.go

`SSHFP` also works fine for OVH. Tested.

OVH: Certify SSHFP support

---

providers/cloudflare/cloudflareProvider.go

As per [CF-API documentation](https://api.cloudflare.com/#dns-records-for-a-zone-properties) records where CLOUDFLARE_PROXY is enabled, records are always forced to have a TTL of 1. (meaning "Managed by Cloudflare" in the UI) When not forcing this property change, dnscontrol tries to update the TTL on each preview/push. But as the TTL is hardcoded, this simply ends up changing nothing at the end and dnscontrol is never happy.
**Without that change:**
```text
******************** Domain: domain.tld
----- Getting nameservers from: cf
----- DNS Provider: cf...1 correction
#1: MODIFY CNAME sub.domain.tld: (proxy.domain2.tld. ttl=1 proxy=true) -> (proxy.domain2.tld. ttl=43200 proxy=true)
SUCCESS!
Done. 1 corrections.
```
Even stating "success", it will be never changed on the CF-end.
**After …

CLOUDFLARE: Fix CF trying to update non-changeable TTL

---

docs/_functions/domain/CAA.md
docs/_functions/domain/NS.md
docs/_functions/domain/SSHFP.md
docs/_functions/global/IP.md
docs/_includes/matrix.html
docs/_providers/cloudflare.md
docs/caa-builder.md
docs/examples.md
docs/index.md
docs/provider-list.md

* Basic `IP()` explanation
* Mentioning that OVH also works with `CAA` records
* Mentioning the use of cloudflare proxy mode with `DEFAULTS()` (IMHO good to know)
* Fixed "URL" at `iodef` at `CAA` docs
* Small changed example of having default TTL
* Fixed `CAA_BUILDER` link on home site
* Fixed that PRs/issues where displayed under the wrong headlines on providers page

General docs improvements

---

providers/ovh/ovhProvider.go
providers/ovh/protocol.go

This PR addresses a wrong behavior when the domain takes use of the additional OVH anycast service (Anycast can be ordered separately for a yearly fee). If used, `fetchNS()` will return back *all* nameservers referenced with a domain, whenever in use or not - so in case of anycast-enabled domains: 2x normal dns server, 2x anycast dns servers. This causes non-anycast nameservers being always added.
If anycast is enabled, IMHO it does not really make sense to add non-anycast nameservers. This PR uses `fetchRegistrarNS()` to get the **currently in-use** registrar nameserver. This way it works as intended.
(Regarding changes in file `protocol.go`: This is simply a line-switch-change to be consistent with the order as OVH returns back the data from their API.)

OVH: Fixed registrar ns correction

---

docs/spf-optimizer.md
pkg/spflib/parse.go
pkg/spflib/parse_test.go

SPF has `include:` and `redirect:` directives.
We only implement the easiest edge-case of redirect, which is when it is the last item in the SPF record. In this situation it is equivalent to `include:`.

Add redirect support to SPF

---

models/target.go

* Fix GetTargetCombined() for R53_ALIAS

Multiple R53_ALIAS on the same label should be permitted when differerent

---

integrationTest/integration_test.go
providers/route53/route53Provider.go

Added integration tests (for r53 only because of the massive size), that add, modify, and remove 600 and 1200 A records. This was enough to demonstrate the failure in all operations.
When creating corrections, use batches of 1000 for deletes, and batches of 500 for upserts, since they often count as a deletion and creation in one.
Further optimization could do more precise counting of batches for upserts to identify new adds vs updates, but we have not previously cared about that distinction, and the slightly worse atomicity is most likely to have an impact only one time when initially importing a large zone. In my opinion not worth the refactoring required to pack slightly more into batches that are pure additions.
Fixes #508 and #493

Respect max batch size for r53

---

docs/_includes/matrix.html
providers/vultr/vultrProvider.go

Vultr now supports SSHFP records.
Note: I'll rebase this and mark it as ready once #529 is merged.

Added support for Vultr SSHFP records

---

providers/diff/diff.go
providers/diff/diff_test.go

Fixes #552 
Scenario is when you have multiple records that share a Type/Name/Target, but have other fields that differ. In this case, ordering matters and sometimes you get never-ending changes.
Adds a first pass to find perfect matches before trying to make pairs based on target.

Fix inconsistent matching in diff

---

docs/_providers/cloudflare.md
docs/getting-started.md
providers/cloudflare/cloudflareProvider.go
providers/cloudflare/rest.go

Cloudflare API tokens are a new way to authenticate to Cloudflare API.
Unlike the Global API key, tokens can be given specific permissions to
only access parts of the API. See [1] for details.
[1] https://blog.cloudflare.com/api-tokens-general-availability/
This commit introduces a new credential for cloudflare called
`apitoken`, which is mutually exclusive with `apiuser` and `apikey`.
In order for DNSControl to work with this token, it should have the
right to read DNS zones and edit DNS records.
Closes #534

Support Cloudflare API tokens

---

docs/_providers/cloudflare.md

Remove trailing "rather" at the end of a sentence, introduced in #555.

Fix small typo in Cloudflare API tokens documentation

---

providers/azuredns/azureDnsProvider.go

https://stackexchange.github.io/dnscontrol/provider-list indicates that Azure supports dual host.
Azure permits _adding_ new NS records at the apex, but it does not support modifying or deleting the default NS records for the zone.
I think this means that Dual Host compatibility is partial and should be reflected as such in the docs.
Also `gofmt` rearranged the imports, sorry.

Adding note about existing Azure DNS dual host support being limited

---

docs/_includes/matrix.html
integrationTest/integration_test.go
models/t_srv.go
providers/cloudflare/cloudflareProvider.go
providers/cloudflare/rest.go
providers/digitalocean/digitaloceanProvider.go
providers/dnsimple/dnsimpleProvider.go
providers/namedotcom/namedotcomProvider.go
providers/namedotcom/records.go

SRV records with empty (".") targets are now returned as false by the API, which breaks Unmarshaling it into a string.
fixes #561

Fix decoding empty Cloudflare SRV target (plus fixes for a few other providers)

---

vendor/github.com/vultr/govultr/CHANGELOG.md
vendor/github.com/vultr/govultr/go.mod
vendor/github.com/vultr/govultr/go.sum
vendor/github.com/vultr/govultr/govultr.go
vendor/vendor.json

v0.1.7 adds retries when requests exceed the rate limit.

vendor: Update govultr to v0.1.7

---

commands/getCerts.go

validateCertificateList error message has valid spelled wrong.

Fix typo in invalid cert name error message

---

docs/_providers/route53.md
providers/route53/route53Provider.go

This will allow users to specify credentials via AWS_PROFILE.
The following variables need to be exported.
```
AWS_SDK_LOAD_CONFIG=1 
AWS_PROFILE=<wanted profile>
```

Add AWS_PROFILE functionality for Route53 provider

---

integrationTest/integration_test.go

But works fine for any "real" domain like ns1.example.com

ClouDNS do not allow you to create NS for ns1.otherdomain.tld

---

OWNERS
README.md
docs/_providers/cloudns.md
docs/provider-list.md
integrationTest/providers.json
providers/_all/all.go
providers/cloudns/api.go
providers/cloudns/cloudnsProvider.go

Fix #114  This is my first experience with Go, so any feedback will be valuable :)
Linode provider was used as base.
The tests pass. But TestDualProviders doesn't work with ClouDNS. ClouDNS do not allow you to create NS for ns1.otherdomain.tld But work fine for any "real" domain like ns1.otherdomain.com Can we change domain in test to COM ? If yes, should I make separate PR?

NEW PROVIDER: ClouDNS

---

docs/_providers/digitalocean.md
integrationTest/integration_test.go
providers/digitalocean/digitaloceanProvider.go

Change the tests to skip test case with CAA `;` value for Digitalocean,
because that specific feature isn't supported.
Closes #588

Digitalocean CAA-support

---

docs/_providers/internetbs.md

Rather than listing a GCLOUD, @captncraig reminded me that we can just list 0 dns providers and it would work.
CC: @pragmaton @captncraig

DOC: Improve internetbs doc

---

pkg/acme/registration.go
providers/cloudflare/cloudflareProvider.go
providers/route53/route53Provider.go

* CloudFlare provider is missing quotes on a JSON struct tag.
* ACME package has a unnecessary JSON struct tag.
* Route53 provider has an unreachable return.

Fix issues from go vet

---

integrationTest/integration_test.go

* All tests start with an "empty", not end.
* "empty" formatted the same way for all tests.

Integration testing: Standardize "empty" usage

---

pkg/normalize/validate.go

Although `_mta-sts` is normally used with a `TXT` record it can also be used with a `CNAME` record to delegate the authority.
See sections 3.1 and 8.2 of [RFC8461](https://www.rfc-editor.org/rfc/rfc8461.txt) for details.

Add _mta-sts to labels allowed to have an underscore

---

providers/azuredns/azureDnsProvider.go

Azure has a Custom ALIAS Record type that works on A, AAAA, CNAME records.
This broke our parsing logic and was giving NRE when configured in the portal. I'm working on a Implementation for AZURE ALIAS Record but need to fix the existing bug while the implementation is in progress

AZURE: Bug: Alias Records breaks DNSControl

---

go.mod
go.sum
integrationTest/integration_test.go
providers/azuredns/azureDnsProvider.go
vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns/client.go
vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns/recordsets.go
vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns/resourcereference.go
vendor/github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2018-05-01/dns/zones.go
vendor/github.com/Azure/azure-sdk-for-go/version/version.go
vendor/modules.txt

Actions #619 
Upgraded Azure SDK to 39.1.0
Empty string not accepted using default API Call. Changed for that particular case
Some other fixes for #616 #615 
go get -u github.com/Azure/azure-sdk-for-go
go mod tidy

 Upgraded Azure SDK to 39.1.0

---

commands/commands.go
docs/_includes/matrix.html
providers/dnsimple/dnsimpleProvider.go

The default logic for encoding SSHFP records was dropping the key and
hash algorithms and just posting the content, the `Can` check didn't
stop attempts to use SSHFP.  So, implement SSHFP support.
DNSimple support multiple DNS strings in a TXT record, by representing
the payload as quoted strings already.  This doesn't appear to be
documented, but it does actually work.

dnsimple: bug-fix SSHFP, add multi TXT support

---

commands/getZones.go
docs/get-zones.md

--format=nameonly -- Don't get the zone records, just list the zone names
--format=tsv and tsvfqdn are combined. Now the columns include the FQDN and the shortname.

get-zones: new output format nameonly; remove tsvfqdn

---

commands/getZones.go
docs/_includes/matrix.html
pkg/prettyzone/prettyzone.go
pkg/prettyzone/prettyzone_test.go
pkg/prettyzone/sorting.go
providers/bind/bindProvider.go

There's a philosophy issue here around what is the Bind output meant to do.  Since AFAIK we're not integrating into Bind's catalog zones or the like, we're just targeting the zonefiles, we're not in a position to do _anything_ relating to registrar options such as setting up DS glue.
So at one level, enabling AutoDNSSEC for Bind is a lie. But without this, folks can't target a Bind zone as a secondary provider for their domain, to get debug dumps of the zone output, because the checks for "Can" block it.  So I think this commit achieves a happy compromise: we write a comment into the Bind zonefile, indicating that DNSSEC was requested.
Actually: we add support for arbitrary zone comments to be written into a zonefile via a slightly ugly "can be `nil`" parameter.  We then write in a …

BIND: Implement AutoDNSSEC

---

docs/adding-new-rtypes.md
pkg/normalize/capabilities_test.go
pkg/normalize/validate.go

Adds test: `TestCapabilitiesAreFiltered`
We have a number of records and pseudo-records which in theory can only be used with a given provider if that provider indicates support.  In practice, we've been missing the checks for that support and have been passing the records down anyway.  The advice comment in the providers/capabilities.go file to edit `checkProviderCapabilities()` has not been reliably followed.
We need an internal self-consistency test.  The constants are not directly exported or enumerable based solely on the package interfaces at run-time, but with source access for a test suite, we can use the `go/ast` and related interfaces to examine the code, extract all the constants from a given package, figure out which ones we want to be handled, and then insist that they're …

Tests: ensure provider capabilities are checked

---

commands/getZones.go
pkg/prettyzone/prettyzone.go

If a provider considers ttl=0 to be magic, the output of get-zones makes more sense now.

get-zones: Improve TTL handling when provider has magic TTLs

---

integrationTest/providers.json
providers/ovh/ovhProvider.go

Commit 87ad01d added the very useful `get-zones` command, whichrequires providers to implement a new method `GetZoneRecords` (tracked in #628).
This changes make the OVH provider support this new feature.

(#628) Add get-zones to the OVH provider

---

models/t_naptr.go
providers/dnsimple/dnsimpleProvider.go

Fix the model to strip quotes from all the string parts; BIND integration tests still pass.  DNSIMPLE integration tests pass.

DNSIMPLE: support NAPTR

---

providers/ovh/ovhProvider.go

As requested in #491, as OVH doesn't return dot-suffixed NS, therefore we can use `models.ToNameservers` in this provider (which incidentally this PR does).

(#491) convert the OVH provider to models.ToNameservers

---

providers/gandi_v5/gandi_v5Provider.go

Encountered this while trying to push a long TXT record with GANDI_V5.  The provider accepts it but reformats it into a compatible multi-TXT record.  Unfortunately, this results in every subsequent `dnscontrol preview` to indicate that the TXT record does not match.  `dnscontrol push` will also update this record with every call.
With this patch, I'm able to push the TXT record as expected, and preview after push indicates no more changes as expected.
`cd integrationTest && go test` passes

Add CanUseTXTMulti to GANDI_V5 provider

---

integrationTest/integration_test.go
providers/cloudflare/cloudflareProvider.go

When the CloudFlare provider syncs, it adds an extraneous `.` to the retrieved record's target, if the target is just a `.` (e.g. for an RFC 7505 null MX of `MX('@', 0, '.')`).  This PR ensures that the `.` is only added to targets that don't already have one.

Fix #702: Spurious null MX changes on CloudFlare

---

providers/octodns/octoyaml/read.go

This fixes Issue #736 and was build tested with Go 1.14.2 on
- FreeBSD 12.1/i386
- FreeBSD 12.1/amd64
- FreeBSD 11.3/i386
- FreeBSD 11.3/amd64
https://ports.bluelife.at/builds/20200507-09:37:34.38360/

Fix octodns: constant 4294967295 overflows int (Issue #736)

---

providers/capabilities.go
providers/gcloud/gcloudProvider.go

The gcloud provider seems to behave correctly with DS resource records,
and is able to read and write them properly. I've enabled this in the
provider options.
Please let me know of any special tests or actions you'd like me to take to
enable this to be merged. Thanks.

Add support to GCLOUD provider for DS records

---

providers/capabilities.go
providers/gcloud/gcloudProvider.go

Reverts StackExchange/dnscontrol#760
Sadly I spoke too soon. I'm seeing errors when I run this test:
```
$ go test -v -verbose -provider GCLOUD -start 24 -end 24 -run TestDNSProviders
=== RUN   TestDNSProviders/dnscontroltest-gcloud.com
=== RUN   TestDNSProviders/dnscontroltest-gcloud.com/Clean_Slate:Empty
TestDNSProviders/dnscontroltest-gcloud.com/Clean_Slate:Empty: integration_test.go:179: DELETE NS dnscontroltest-gcloud.com ns1.example.com. ttl=300
DELETE NS dnscontroltest-gcloud.com ns2.example.com. ttl=300
=== RUN   TestDNSProviders/dnscontroltest-gcloud.com/24:DS:create_DS
TestDNSProviders/dnscontroltest-gcloud.com/24:DS:create_DS: integration_test.go:179: CREATE DS dnscontroltest-gcloud.com 1 13 1 ADIGEST ttl=300 …
```

Revert "Add support to GCLOUD provider for DS records"

---

commands/getZones.go
docs/get-zones.md
docs/migrating.md

The documentation and help refers to some options using a single-dash; these seem to work but are inconsistent with the rest of the documentation. Along with these fixes I've fixed a couple of grammatical errors, line lengths and inconsistent capitalisation. I also added an explanation of what "disco commas" are.

get-zone documentation and help fixes

---

integrationTest/integration_test.go
pkg/normalize/capabilities_test.go
pkg/normalize/validate.go
pkg/normalize/validate_test.go
providers/capabilities.go
providers/capability_string.go
providers/gcloud/gcloudProvider.go

This functionality is required by the GCLOUD provider, which supports
recordsets of type DS but only for child records of the zone, to enable
further delegation. It does not support them at the apex of the zone (@)
because Google Cloud DNS is not itself a registrar which needs to model
this information.
A related change (14ff68b151b5db1f24bcdaccb30b6fa95897940a, #760) was
previously introduced to enable DS support in Google, which broke
integration tests with this provider.
To cleanly support this, we introduce a new provider capability
CanUseDSForChildren and appropriate integration tests. Further, it is no
longer possible to verify a provider has the proper capabilities for a
zone simply by existence of particular records; we adapt the capability
checks to enable inspection of the …

Provider support for DS records as children only

---

providers/ns1/ns1provider.go

#775 Reverted support for TXTMulti due to NS1 automatically converting TXTMulti records back to TXT

NS1: Revert enabling TXTMulti

---

providers/route53/route53Provider.go

Much like OVH Route53 when queried returns SPF records as their own
type. This small change transcribes the SPF type to TXT
See: https://github.com/StackExchange/dnscontrol/issues/446
See: https://github.com/StackExchange/dnscontrol/blob/644ba70e87bf21997d9d2f020216f90b3876359d/providers/ovh/ovhProvider.go#L169-L172

Route53 uses a custom record type for SPF

---

providers/azuredns/azureDnsProvider.go

Resolves #770 
Issue: https://github.com/StackExchange/dnscontrol/issues/770
No code changes and default version of github.com/Azure/azure-sdk-for-go v43.3.0+incompatible. dnscontrol is trying to add the same set of domains (pagination doesn't work):
```
$ ./dnscontrol-Darwin preview
******************** Domain: companydomain123456.com
----- Getting nameservers from: azuredns
----- DNS Provider: azuredns...13 corrections
#1: CREATE CNAME record-cname-499.companydomain123456.com apple.com. ttl=300
#2: CREATE CNAME record-cname-500.companydomain123456.com apple.com. ttl=300
#3: CREATE CNAME record-cname-501.companydomain123456.com apple.com. ttl=300
#4: CREATE CNAME record-cname-502.companydomain123456.com apple.com. ttl=300
#5: CREATE CNAME record-cname-503.companydomain123456.com …
```

Fix for incomplete results from Azure DNS in fetchRecordSets #770

---

providers/desec/desecProvider.go

Enable PTR support for `deSEC` provider
I looked at the definition of the provider and also at the API and couldn't see why it wouldn't work properly, then I built `dnscontrol` with the `providers.Can()` flag for `CanUsePTR` and it worked out of box.
* Creation
```
$ ./dnscontrol-test push
******************** Domain: 1.2.3.4.5.6.7.8.9.a.b.c.ip6.arpa
----- Getting nameservers from: desec
----- DNS Provider: desec...1 correction
#1: Changes:
CREATE PTR 0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.1.2.3.4.5.6.7.8.9.a.b.c.ip6.arpa fr-par01.bb.example.com. ttl=3600
CREATE PTR 0.3.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.1.2.3.4.5.6.7.8.9.a.b.c.ip6.arpa de-dus01.bb.example.com. ttl=3600
CREATE PTR 0.f.3.9.9.4.e.f.f.f.2.3.1.1.2.0.a.0.b.0.1.2.3.4.5.6.7.8.9.a.b.c.ip6.arpa md.example.com. ttl=3600
CREATE …
```

deSEC: Supports PTR records

---

integrationTest/integration_test.go

I'm currently trying to implement support for inwx.de and was surprised to see a SRV integration test fail when I hadn't added CanUseSRV yet.
I'm not sure when an empty SRV record is useful and it's not supported by inwx.de anyway, but I still think that the test should only run when the provider claims to support SRV records.

fix: only run SRV null target integration test when CanUseSRV is set

---

.gitignore
providers/azuredns/azureDnsProvider.go

Resolves #792
Before changes (all domains were created previously by running `dnscontrol create-domains`):
```text
******************** Domain: zone-100-7930ba393bb96a6fb30f62e75d593f46.com
----- Getting nameservers from: azuredns
----- DNS Provider: azuredns...1 correction
#1: CREATE A record-001.zone-100-7930ba393bb96a6fb30f62e75d593f46.com 1.1.1.1 ttl=300
SUCCESS!
----- Registrar: none...0 corrections
******************** Domain: zone-101-469eb2223790512426e52607b9029f93.com
----- Getting nameservers from: azuredns
Domain zone-101-469eb2223790512426e52607b9029f93.com not found in you Azure account
```
After (first run):
```
******************** Domain: zone-199-7b34b3adb50bac550114bb963a1bac88.com
----- Getting nameservers from: azuredns
----- DNS Provider: azuredns...1 correction
#1: …
```

Fix for Azure DNS Provider with >100 Zones

---

providers/bind/bindProvider.go
providers/bind/soa.go
providers/bind/soa_test.go

I've been working on adding an SOA record type to BIND, but I saw #802 and figured I can pull that work out and see if it works as I did it.
Let me know if there's anything I missed or need to do different.
I've tested on my own with changing `DEFAULTS(DefaultTTL())` and it has properly caught changes.

Add TTL to BIND SoaInfo struct

---

providers/cloudflare/cloudflareProvider.go

As discussed in #809, the TTL always came back as `1` in the `dnscontrol preview` command, but it's always being "set" to `120`. This resulted in there _always_ being a difference:
```
******************** Domain: example.net
----- Getting nameservers from: cloudflare
----- DNS Provider: cloudflare...1 correction
#1: MODIFY PAGE_RULE example.net: (*example.net/*,https://example.com,1,301 ttl=1) -> (*example.net/*,https://example.com,1,301 ttl=120)
----- Registrar: none...0 corrections
Done. 1 correction.
```
This PR fixes that transgression, and makes sure there's no differences  in the page rules if they haven't been edited:
```
******************** Domain: example.net
----- Getting nameservers from: cloudflare
----- DNS Provider: cloudflare...0 corrections
----- Registrar: none...0 …
```

Set TTL to 1 for Cloudflare page rules

---

commands/printIR.go

currently, any validation warnings are printed to stdout, which means commands like `dnscontrol print-ir | jq` fails because the output isn't valid JSON.
by writing these to stderr instead (by using `log.Printf` instead of `fmt.Printf`), the errors are still printed, but won't cause JSON parsing of stdout to fail.

print-ir: print validation warnings/errors to stderr

---

docs/_includes/matrix.html
docs/_providers/doh.md
go.mod
go.sum
providers/_all/all.go
providers/doh/api.go
providers/doh/dohProvider.go

Okay, so this might be a "just me" problem, but I have a bunch of domains stuck with registrars without APIs. 
While I could just use `NewRegistrar('none', 'NONE');` and manage them manually, I'd like to ensure the nameservers are still correct.
This provider is my solution to this problem, it uses DNS-over-HTTPS to query the NS records for the domain and ensure they matched the expected servers. It returns an error if it is asked to push NS changes (eg `FAILURE! DNS-over-HTTPS 'Registrar' is read only, changes must be applied to example.com manually`). You can configure the DOH provider - tested with Quad9, Cloudflare, Google Public DNS.
I'm not sure if there's interest in this being merged, if not I'm happy to keen it in our own fork.

Read-only 'Registrar' provider that does an NS lookup to validate the expected NS records

---

providers/inwx/inwxProvider.go

ns4 and ns5 are being deprecated, therefore removing them, see: https://www.inwx.de/en/news/604/important-nameserver-changes

Remove default inwx nameservers due to deprecation

---

docs/_includes/matrix.html
providers/inwx/inwxProvider.go

This adds support of `create-domains` for INWX.
INWX has two ways for "adding" domains:
- Adding domain to INWX as registrar
- Adding domain to INWX as only nameserver. (While INWX prohibits using their nameserver for external domains, it's technically still possible)
This implementation checks and adds domains to the nameserver only and does not register/order domains in this approach.

INWX: Support creating domains

---

pkg/js/js.go

This is probably the easiest way to display the real file where the error occurred, without rewriting large parts of `ExecuteJavascript`. Function `throw()` expects an error as a string as second argument, where we can state in which file the error occurred in. In `relFile` there's always the filename what was about being run.
Output:
```text
executing dnsconfig.js: Error: File domain.tld.js: (anonymous): Line 13:1 Unexpected token ) (and 1 more errors)
```
(Tested with file which is being require'ed using `require_glob()`)
Edit: I'm aware I've opened the PR against branch `requirename`

Display file where error occurred

---

providers/cloudns/api.go

This patch resolves the regression reported in #849. Go's `json.Unmarshal` would return a `json.UnmarshalTypeError` error when attempting to unmarshal successful responses to `cloudns.errorResponse`. I changed the behaviour to only return an error to the caller when this unmarshal operation does not fail, but I'm happy to revise this if another approach is preferred.

ClouDNS: Return API error only when body unmarshals to errorResponse

---

docs/_providers/netcup.md

According usage example jsId should be all uppercase

DOCS: fix jsId for Netcup Provider

---

OWNERS
README.md
docs/_includes/matrix.html
docs/_providers/hetzner.md
docs/provider-list.md
integrationTest/integration_test.go
integrationTest/providers.json
providers/_all/all.go
providers/hetzner/api.go
providers/hetzner/hetznerProvider.go
providers/hetzner/types.go

This PR is implementing the first revision of the Provider for the Hetzner DNS Console service.
https://www.hetzner.com/dns-console
API schema: https://dns.hetzner.com/api-docs
Supported/Non-supported records are listed here https://docs.hetzner.com/dns-console/dns/general/supported-dns-record-types (they are also listed in the API schema https://dns.hetzner.com/api-docs#operation/CreateRecord)
It was pretty straight forward to implement (for a non-gopher), thanks for the detailed instructions.
Their API supports bulk creation and updating, but not bulk deletion. A follow-up PR could group corrections, but I am afraid this will add a lot of complexity, considering that we probably have to chunk them too.
Some record types are currently marked as not supported, incl. SOA records for which …

HETZNER: implement the provider for Hetzner DNS Console

---

providers/activedir/activedirProvider.go
providers/activedir/domains.go
providers/activedir/domains_test.go
providers/activedir/getzones_other.go
providers/azuredns/azureDnsProvider.go
providers/cloudflare/cloudflareProvider.go
providers/cloudflare/preprocess_test.go
providers/cloudflare/rest.go
providers/digitalocean/digitaloceanProvider.go
providers/dnsimple/dnsimpleProvider.go
providers/gandi_v5/gandi_v5Provider.go
providers/gcloud/gcloudProvider.go
providers/linode/api.go
providers/linode/linodeProvider.go
providers/namecheap/namecheapProvider.go
providers/namedotcom/namedotcomProvider.go
providers/namedotcom/nameservers.go
providers/namedotcom/records.go
providers/namedotcom/zones.go
providers/opensrs/opensrsProvider.go
providers/route53/route53Provider.go

```
git co .
git co master
git br -D tlim_rename
git co -b tlim_rename
gorename -v -from '"github.com/StackExchange/dnscontrol/v3/providers/activedir".adProvider' -to 'activedirAPI'
gorename -v -from '"github.com/StackExchange/dnscontrol/v3/providers/route53".route53Provider' -to 'route53API'
gorename -v -from '"github.com/StackExchange/dnscontrol/v3/providers/gcloud".gcloud' -to 'gcloudAPI'
gorename -v -from '"github.com/StackExchange/dnscontrol/v3/providers/namedotcom".NameCom' -to 'namedotcomAPI'
gorename -v -from '"github.com/StackExchange/dnscontrol/v3/providers/cloudflare".api' -to 'cloudflareAPI'
gorename -v -from '"github.com/StackExchange/dnscontrol/v3/providers/digitalocean".DoAPI' -to 'digitaloceanAPI'
gorename -v -from …
```

Be more consistent in API handle variable names

---

providers/activedir/getzones_windows.go

Build broke at https://github.com/StackExchange/dnscontrol/pull/914 for Windows and we didn't notice.

Fix broken Windows build

---

.github/workflows/build.yml

As a precursor to [automating the entire release process](https://github.com/StackExchange/dnscontrol/pull/789), this simple workflow will just run all the builds for all PRs targeting the master branch.
Simultaneously, let's add a "Require status checks to pass before merging" [branch protection rule](https://github.com/StackExchange/dnscontrol/settings/branch_protection_rules/new).
This will prevent PRs from getting merged to `master` if they [break any of the builds](https://github.com/StackExchange/dnscontrol/commit/bb6aecc9ada34488f3d69ad1bcd5648f5d273bee).

Run builds on PRs targeting master branch

---

providers/hetzner/api.go
providers/hetzner/hetznerProvider.go
providers/hetzner/types.go

Followup for #904 
The Hetzner DNS Console API supports bulk creation and modification of records. Unfortunately they do not support bulk deletion yet. 
https://dns.hetzner.com/api-docs#operation/BulkCreateRecords
https://dns.hetzner.com/api-docs#operation/BulkUpdateRecords
This PR is implementing the api wrapper and refactoring the creation/modification of records to use the new methods.
Shall I remove the old, now unused methods and types in this PR as well?
<details>
<summary> preview </summary>
```
******************** Domain: testing1.dev
----- Getting nameservers from: HETZNER
----- DNS Provider: HETZNER...2 corrections
#1: Batch creation of records:
CREATE A new.testing1.dev 1.2.3.4 ttl=300
CREATE A new1.testing1.dev 1.2.3.4 ttl=300
CREATE A new2.testing1.dev 1.2.3.4 ttl=300
#2: …
```

HETZNER: create and modify multiple records in batches

---

providers/hetzner/api.go

Followup for #904 
Previously for any retry the request body was already consumed and
the server received an empty body.
Which in turn results in a response with a status code of 400 for the retied request.
This is best reviewed with white-space changes ignored: https://github.com/StackExchange/dnscontrol/pull/926/files?diff=unified&w=1

HETZNER: fix retry of POST/PUT requests -- rebuild request body

---

.github/workflows/build.yml

Following up on https://github.com/StackExchange/dnscontrol/pull/922 and https://github.com/StackExchange/dnscontrol/pull/927, this also runs a set of integration tests as part of build checks.
Branch protection of `master` is in place, i.e. changes which break any of the integration tests can't be merged.
[Repo secrets](https://github.com/StackExchange/dnscontrol/settings/secrets) added as necessary.

Run integration tests as part of build checks

---

.github/workflows/build.yml

Follow-up to https://github.com/StackExchange/dnscontrol/pull/930: adding additional integration tests for contributor-supported DNS providers:
* DIGITALOCEAN   (there's a ratelimit that makes this fail occasionally- note that integration tests aren't blocking release)
* GANDI_V5
(separate PR coming for [HEXONET](https://stackexchange.github.io/dnscontrol/providers/hexonet))

Integration tests: add Digital Ocean, Gandi V5

---

commands/getZones.go
docs/get-zones.md
pkg/prettyzone/prettyzone.go
providers/cloudflare/cloudflareProvider.go

Fixes https://github.com/StackExchange/dnscontrol/issues/629
NOTE: The branch name refers to the wrong bugid.

CLOUDFLARE: get-zones now outputs "orange cloud" status

---

integrationTest/integration_test.go
providers/inwx/inwxProvider.go

Fixes #954 by splitting out the single-quote TXT integration test and by adding an additional check to the INWX provider to fail if there are TXT records with single-quotes.

INWX: Guard against single-quote TXT targets and split the integration test

---

providers/hetzner/hetznerProvider.go

**Issue**
The Hetzner provider doesn't allow TXTMulti. Hence, creating DKIM TXT records with >255 bytes fails. 
**Solution**
In that PR I just enabled TXTMulti. For testing purposes I've successfully created, updated and verified a DKIM record against the Hetzner DNS API. Even the verification with a DKIM record checker succeeded. Therefore, I propose to enable TXTMulti for the provider.

Allow TXTMulti for provider Hetzner

---

.github/workflows/build.yml
integrationTest/providers.json

Secrets are not propagated to an Action if the PR is from a forked repo.  The good news is that this prevents an outsiders from logging secrets.  The bad news it that outsiders always see their tests as failing.
With this change, every provider is tested but the tests abort early if the action doesn't have access to the secrets.  More specifically, the value "true" must be found in an env named `${PROVIDER}__CAN_SECRET` (for example `BIND__CAN_SECRET` or `HEXONET__CAN_SECRET`)
In this PR we:
* List the matrix of providers one-per-line to make it easier to add/remove provider names; as well as add comments.
* For each provider in the matrix, set an env named `${PROVIDER}__CAN_SECRET` to true if tests are to run.
* Add a step that determines if future steps should be skipped
You can see …

Gracefully skip tests if the secrets are not available

---

docs/_includes/matrix.html
go.mod
go.sum
providers/inwx/inwxProvider.go

INWX supports multi-TXT records now. I enabled the capability, ran `go generate` to update the docs, verified that the MultiTXT integration tests for INWX work and manually verified with dig that the NS servers reply correctly.

INWX: enable multi txt support

---

providers/cloudns/api.go
providers/cloudns/cloudnsProvider.go

I updated the Provider Cloudns to supprt auhtentification with "sub-auth-id". for security reason it is good to work just with subuser in order to avoid the contrl of DNS-management. I modified the files : cloudnssudo Provider.go and api.go

update cloudns to support request from subuser (sub-auth-id)

---

integrationTest/integration_test.go
providers/ovh/ovhProvider.go

In fact OVH natively supports multi TXT, so there's really nothing to do here :)
I also excluded OVH from the Null MX integration test, because this provider doesn't yet support this RFC.

(#1003) Make OVH TXTMulti capable

---

providers/gcloud/gcloudProvider.go

@Knight1 noticed that TLSA support wasn't enabled, but should be. Fixing.

Add TLSA Support for gcloud Provider

---

.github/workflows/build.yml
integrationTest/providers.json
pkg/diff/diff.go
providers/powerdns/powerdnsProvider.go

This PR has some minor fixes for ALIAS, NAPTR, TXTMulti and RRType changes.
For a RRType change, i needed to create a function "ChangedGroupsDeleteFirst" to ensure that delete actions occur first before the new RR with type is created. Besides i renamed `delete` to `toDelete` in diff.go, as it may conflicts with the Go `delete` function.
This PR also enables automatic integration testing for PowerDNS.

POWERDNS: Some minor fixes for ALIAS and TXTMulti and integration testing

---

providers/hetzner/auditrecords.go
providers/hetzner/types.go

The TXT handling of HETZNER seems to buggy, server-side.
I came up with workarounds client-side, but IMHO they should be fixed upstream. I will email them and see how that goes before marking this as read-for-review.
I do not think that a rewrite of the TXT handling will have an impact for these bugs as they seem to be server-side.
Bugs and workarounds:
- send empty string as `""` instead of sending an empty string as value
- send `strings.Repeat("A", 254)` as `AA...A` instead of `"AA..A"`
- send `strings.Repeat("A", 255)` as `AA...A` instead of `"AA..A"`
- receive `"AA...A" "BB...B" "CC...C" ` (trailing space), trim the space
Actions:
- Make use of new default handling of TXTs for de-serializing.
- Empty value is represented as quoted empty string now, which the
HETZNER validation …

HETZNER: fix edge cases in TXT handling

---

providers/cloudns/api.go
providers/cloudns/auditrecords.go
providers/cloudns/cloudnsProvider.go

The following two points have been fixed.
- Fixed that "ClouDNS" was changed to "CloDNS" in the source code.
- Added a description to Audit Records that does not allow double quotes in TXT records.
I am new to Go language.
Therefore, there may be something strange.

typo fix and Audit Records update for ClouDNS

---

providers/cloudns/auditrecords.go
providers/cloudns/cloudnsProvider.go

Better handling of TXT records. ClouDNS NOT allow multiple TXT records with same name but allow values longer the 255
Now TXT tests - pass
> go test -v -verbose -provider CLOUDNS -start 9 -end 13
> ...
>PASS

[ClouDNS] Fix for TXT records. 

---

integrationTest/integration_test.go

Looks like SRV was marked as "not test" by mistake - it's working fine. On the other hand, PTR working in general, but can not be tested on the same domain.
```
➜  integrationTest git:(cloudns-test-fix) ✗ go test -provider CLOUDNS  
PASS
ok      github.com/StackExchange/dnscontrol/v3/integrationTest  129.464s
```

ClouDNS. tests fix

---

providers/cloudns/api.go
providers/cloudns/cloudnsProvider.go

Fetch ClouDNS allowed TTL values from API.
Fix the problem of # 1078.

Fetch ClouDNS allowed TTL values from API. #1078

---

providers/hexonet/auditrecords.go

The test case of "recordaudit.TxtNoLongStrings(records)" no longer needed for the provider HEXONET

AuditRecord: removed one successful case

---

providers/gandiv5/gandi_v5Provider.go
providers/ovh/ovhProvider.go

Hi!
It appears that those two providers I use, can implement the `ZoneLister` interface.
For OVH, as it already fetches the zones when creating the `DNSServiceProvider`, I choose to return them instead of doing the request again (as the code already makes the assumption this list doesn't change).

GANDI_V5 & OVH: Implement ZoneLister

---

providers/config/providerConfig.go

Makes the creds file executable as requested in #1116. It checks the unix file permissions for the executable bit or it can be marked as executable with a "!" as in front of the file name.

Make creds file executable

---

docs/_functions/domain/R53_ALIAS.md

After helping with https://github.com/StackExchange/dnscontrol/issues/1128 I noticed that the examples don't include a "." at the end of FQDNs.  I think that lead to the confusion.
Here's a PR with corrected (I hope) examples.  Are they more correct?
CC @masterzen

ROUTE53: Docs should specify FQDN with dot.

---

providers/ns1/ns1provider.go

A bug was introduced in a2042c2eda, which stoped ALIAS records
from setting their record type correctly (it was set to nil).
Specifically, case "ALIAS" doesn't fall through to any of the other cases
below, leading ALIAS records to set their type to nil.
To fix that, readd the code that got absorbed by the URLFWD in a2042c2eda.

ns1: fix ALIAS handling

---

docs/_providers/cloudns.md
providers/cloudns/cloudnsProvider.go

I modified the ClouDNS documentation a bit.
- Changed the URL of the ClouDNS document from "asia.cloudns.net" to "www.cloudns.net".
- A little addition about TTL.

Updated ClouDNS documentation

---

integrationTest/providers.json
providers/desec/desecProvider.go
providers/desec/protocol.go

According to [AUTODNSSEC_ON.md](https://github.com/StackExchange/dnscontrol/blob/ce6006cce7b6877bc56dfb6c9df969e47e7cbb86/docs/_functions/domain/AUTODNSSEC_ON.md), AutoDNSSEC means that the provider automatically signs records, taking care of all of the signing configuration.
deSEC automatically signs all domains, so the AutoDNSSEC flag should be `"on"`. This PR makes this change. Also, when trying to turn off DNSSEC, we now tell the user that deSEC domains are always signed.
(The PR also improves the phrasing of some other messages shown to the user.)
If this is merged, will the AutoDNSSEC field in the provider matrix update automatically (https://stackexchange.github.io/dnscontrol/provider-list)? If not, please let me know what else I should be changing.

DESEC: clarify supported capabilities

---

providers/cloudns/cloudnsProvider.go

This change removes part of commit 9949cba.
ClouDNS does not support changing the NAPTR in the API, so I need to disable this change.
I apologize for any inconvenience caused.

Disable ClouDNS NAPTR support

---

providers/axfrddns/axfrddnsProvider.go

Hi!
The AXFRDDNS doesn't implement the `ListZones` function, but advertises `providers.CanGetZones: providers.Can()`.
If I understand correctly the `providers.CanGetZones` capability, it relies only on `ListZones` function/`ZoneLister` interface, so this PR just indicates in the doc that this provider doesn't support it.
AFAIK, you can't ask authoritative servers for domains they serve: so it can't be implemented.

AXFRDDNS: fix doc: false advertisement of Get-Zones capability

---

providers/dnsmadeeasy/types.go

In my (very limited) experience with DNS Made Easy, the system nameserver
TTL is always 86400 and is not able to be altered.
Without this change, if you specify any TTL (other than 300) via
NAMESERVER_TTL() dnscontrol detects a difference and attempts to update
DNS Made Easy with the new value, which fails because the system
nameservers cannot be altered.
With this change in place the same thing will obviously still happen, if
you use NAMESERVER_TTL() with any TTL other than 86400, but that will be
a bit less confusing since the 86400 value appears in the DNS Made Easy
UI at least.

Correct hard coded DNS Made Easy system nameserver TTL

---

providers/msdns/powershell.go
providers/msdns/powershell_test.go

* Zone dump was 90M.  By moving from UTF16 to UTF8 we saved 50%
* Zone dump was capturing stdout, which is slow for big files. Now we write to a tmp file.
* Zone dump was outputting a lot of `Cim*` crap which we didn't need. File size now reduced 90%

MSDNS: Improve reliability of zone dump

---

models/dnsrr.go
pkg/prettyzone/prettyzone.go
pkg/prettyzone/prettyzone_test.go
providers/axfrddns/axfrddnsProvider.go
providers/bind/bindProvider.go

Hi!
Today I came across a domain containing an unknown RR type and `dnscontrol` stopped early.
Here is a proposal to avoid `log.Fatal` and `panic` when calling RRtoRC. Most of the code base already support returning error, so there is not so much changes left.
In my case, it changes the output for unknown record from:
```
******************** Domain: yyyyyy.zzz
----- Getting nameservers from: xxx
----- DNS Provider: xxx...
2021/07/03 00:03:44 dnsrr.go:94: rrToRecord: Unimplemented zone record type=OPENPGPKEY (xxxxx...)
```
to:
```
******************** Domain: yyyyyy.zzz
----- Getting nameservers from: xxx
----- DNS Provider: xxx...
ERROR
Error getting corrections: rrToRecord: Unimplemented zone record type=OPENPGPKEY (xxxxxx....)
completed with errors
```
What do you …

Return error instead of panic when converting RR to RC

---

.github/dependabot.yml

AWS and Azure dependencies seem to have daily updates that usually don't affect this project.  Changing the dependabot settings so that security issues are reported immediately but other changes are reported monthly or weekly.

Less frequently Dependabot runs

---

.github/codeql/codeql-config.yml
.github/workflows/codeql-analysis.yml

Added exception for flattener.js as requested. It turns out that an external config file for CodeQL is needed. 
Docs are here https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning

Re-enable CodeQL for Javascript

---

providers/inwx/inwxProvider.go

INWX has changed their API to use an empty string () instead of
the common @. Fix that by converting between the two.
Fixes #1218

INWX: fix apex domains

---

models/record.go
pkg/normalize/flatten.go

SPF Flatten for non apex domains. Fixes #785.
The fix was relatively easy. Instead of only considering the TXT of the Apex, let's consider all TXT records in a domain.

SPF Flatten for non apex domains

---

docs/_functions/domain/INCLUDE.md
docs/_includes/matrix.html
pkg/js/helpers.js
pkg/js/parse_tests/039-include.js
pkg/js/parse_tests/039-include.json

Add the ability to include records from other domain.  This can be very handy for working with split horizon where you want to overwrite your public domain for an internal one, while still having (some) of these external records.
Example:
```
D("example.com!external", REGISTRAR, DnsProvider(R53),
A("test", "8.8.8.8")
);
D("example.com!internal", REGISTRAR, DnsProvider(R53),
INCLUDE("example.com!external"),
A("home", "127.0.0.1")
);
```

Add INCLUDE statement to include records from other domains

---

docs/_functions/record/DMARC_BUILDER.md
pkg/js/helpers.js

This makes two tiny changes, which makes sense in my opinion:
1. It allows specifying a DMARC version, if required in the future. The only option, and the default, is `DMARC1`. If a new version is ever introduced, it allows specifying without needing to update dnscontrol.
2. When `percent`=100 or `failureFormat`=afrf, the option are not added to the TXT record at all. While they might be indeed the default in RFCs, the default might change in the future. When those values are clearly specified when using `DMARC_BUILDER()`, they should be added to the TXT record - being default or not.

DMARC_BUILDER: specify version, use values when specified

---

integrationTest/integration_test.go
providers/vultr/auditrecords.go
providers/vultr/vultrProvider.go

* VULTR TXT records must be a single string
* VULTR TXT records may not include the double-quote char
* VULTR's API's line protocol requires TXT strings to be surrounded by double-quotes
* VULTR's API syntax-checks TXT records that start with v=spf1

VULTR: Fix TXT quoting issue

---

docs/_functions/record/R53_ZONE.md
pkg/js/helpers.js
pkg/js/parse_tests/040-r53-zone.js
pkg/js/parse_tests/040-r53-zone.json
providers/route53/route53Provider.go

Using R53_ZONE allows you to differentiate between split horizon domains across zones.
Well, imagine you have a hosted public zone called enrise.com and a private zone for enrise.com specific to a VPC. different enrise.com zones across different VPCs. In these examples DNSControl doesn't allow you to specify the zone by ID. This MR addresses this by using the `R53_ZONE` directive inside the `D` directive

Add R53_ZONE as an domain identifier

---

docs/_providers/route53.md

Specifically that creds.json is now required for versions >3.8.0 when using named profiles, as well as the environment variables.
fixes #1261

docs: add clarity around named profiles

---

.github/workflows/build.yml

This should prevent builds from interacting with each other thereby keeping builds from failing when 2 provider tests happen at the same time.
@tlimoncelli I think this should do the trick, but having some problems getting it to work on my fork.

Implement job concurrency on build

---

docs/_providers/cloudflare.md
providers/cloudflare/cloudflareProvider.go
providers/cloudflare/rest.go

There is no API call I've found that requires it, only the accountID.  Also, we now set the cfClient.AccountID similar to b55278140f63e0f95a3418bcd61b810c731ae08f (h/t @fdcastel) and no longer store duplicate information in the cfClient and api objects.
Fixes #1275

CLOUDFLARE: Stop requiring accountname

---

providers/desec/convert.go
providers/gandiv5/convert.go

When having multiple RR in a RRset, only a few of them may be applied.
In my case, when I have two A records, only one of them makes its way
to Gandi.
In `convert.go`, we had:
```go
var zrs []livedns.DomainRecord
// [...]
zrs = append(zrs, zr)
keys[key] = &zrs[len(zrs)-1]
```
If the slice needs to be extended when appending, the reference we got
in `keys[key]` may be outdated because the new slice contains a copy
of the old one. We either need to store references to domain records
in the slice or we need to stop keeping reference of items in the
slice.
I have fixed this with the second solution as I think the order of the
RRsets is not important.

GANDI_V5 & DESEC: correctly handle multiple RR in a RRset

---

pkg/js/parse_tests/029-dextendsub.js
pkg/js/parse_tests/029-dextendsub.json
pkg/js/parse_tests/029-dextendsub/düsseldorf.example.net.zone
pkg/js/parse_tests/029-dextendsub/example.com.zone
pkg/js/parse_tests/029-dextendsub/ü.example.net.zone

Added test cases for every permutation of IDN domains I could think of.
Tests pass with current master (866aa798e2a3acbb3b595afdbbe20ee74b0604c5) but fail with `v3.12.0`.
P.S. Recreated IR JSON file, had to set the `CNAME` tests (760ee8dc46f74f48e216bcaeb82f87f133ca4e16 `029-extendsub.js` lines 138 and 139) to be relative manually to get the tests to pass.

Add test cases for IDN domains

---

providers/oracle/oracleProvider.go

Fixes #1305 Am not 100% sure if changing ToNameserver to ToNameserversStripTD is the correct way to fix the issue but seem to resolved the issue I was having.

Fixes Oracle provider code leaves trailing dot on nameserver

---

pkg/recordaudit/txt.go
providers/cloudns/auditrecords.go
providers/msdns/auditrecords.go
providers/vultr/auditrecords.go

Fix issue [#1139].
All functions in should test for only one condition. There already is a
function that tests for long TXT records: `TxtNoLongStrings`.
Add calls to `TxtNoLongStrings` in all providers that use
`TxtNoMultipleStrings`, to keep functionality, except for NS1 and ClouDNS,
which allow for any TXT record length, but not for multiple strings per
TXT.

CLOUDNS: More accurate TXT record checking (remove length check)

---

providers/hostingde/api.go

Currently, it is not possible to use the Hosting.de provider as a registrar only and use something else for DNS. It fails with the following error message:
```
******************** Domain: <some_domain>
----- DNS Provider: <some_other_provider>...
0 corrections
----- Registrar: hosting.de...
ERROR
Error getting corrections: error getting nameservers: error getting domain config: error getting zone config: zone not found
```
I'm pretty sure the problem is here:
https://github.com/StackExchange/dnscontrol/blob/3405757271b66c7e679b78af74810bedd3e7b50b/providers/hostingde/api.go#L23-L26
For getting the domain config, this always does a `getZoneConfig()` call. However, the [corresponding API call](https://www.hosting.de/api/#list-zoneconfigs) is part of the DNS section of the API. It only …

Hosting.de: Allow using as registrar only

---

docs/_providers/ovh.md
providers/ovh/ovhProvider.go
providers/ovh/protocol.go

OVH now supports managing/creating only a zone (provided this one has been created in the control panel beforehand).
The provider was relying on the registrar NS instead of the zone NS preventing to manage the zone if the domain wasn't
registered to OVH.
These changes fix this behavior by getting the zone NS if the domain is not registered at OVH.
This also allows now to use OVH in all dual providers scenario.

Fix #1338 - OVH provider should work when domain is not registered 

---

providers/packetframe/api.go
providers/packetframe/packetframeProvider.go

This change is in response to the issue presented by @natesales here https://github.com/StackExchange/dnscontrol/pull/1347#issuecomment-1005250670, and following the practices done in the linodeProvider as a way to avoid the issue. It also changes the messages given from corrections to be the DNSControl supplied correction messages. Attached below is the integration test, go vet, and golint results.
```
➜  packetframe git:(packetframe-nameservers) ✗ go vet ./...
➜  packetframe git:(packetframe-nameservers) ✗ golint ./...
```
```
=== RUN   TestDNSProviders/packetframe-dnscontrol.hammy.network
=== RUN   TestDNSProviders/packetframe-dnscontrol.hammy.network/Clean_Slate:Empty
=== RUN   TestDNSProviders/packetframe-dnscontrol.hammy.network/00:GeneralACD:Create_an_A_re …
```

BUG: Packetframe always include default nameservers

---

providers/hetzner/api.go

Fixes https://github.com/StackExchange/dnscontrol/issues/1370
Based on the Hetzner DNS API docs, the listing of zones should not return a 404: https://dns.hetzner.com/api-docs/#operation/GetZones
I'll let them know about this. In the meantime, this workaround should do.
I do not have an empty account at hand for testing the initial creation of a zone. The integration tests pass.

HETZNER: handle a 404 from listing zones gracefully

---

integrationTest/integration_test.go
models/quotes.go
models/quotes_test.go
models/t_caa.go

Fixes #1374
Providers such as Cloudflare return quoted data in the API protocol.  The code had assumed simple space-separated data.
For example, a CAA record might return this data:
0 issue "letsencrypt.org; validationmethods=dns-01; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/1234"
Doing a simple strings.Fields() was not sufficient for parsing this.

CAA records may include quoted spaces (#1374)

---

OWNERS
models/record.go
pkg/acme/acme.go
pkg/js/js.go
pkg/normalize/validate.go
providers/cloudflare/cloudflareProvider.go
providers/cscglobal/api.go
providers/cscglobal/cscglobalProvider.go
providers/easyname/api.go
providers/easyname/provider.go
providers/hexonet/domains.go
providers/opensrs/opensrsProvider.go
providers/route53/route53Provider.go
providers/transip/transipProvider.go

I fixed many, many, lint and staticcheck warnings and errors.  Sorry for the mega-PR but its the fastest way to get them all done.
CC @tresni @papakai @blackshadev @mikenz @philhug @tlimoncelli 
Note: I haven't used the checklist feature before. Let's see if this works.  I've made a checklist of the files in this PR.  We'll check them off as people confirm them.  I may check off some myself if they are just comments.)

MAINT: Linting

---

providers/ns1/ns1Provider.go

Introducing better multivalue support for the CAA entry broke CAA support for ns1, failing the relevant test.
Failing case:
```
=== RUN   TestDNSProviders/example.com/25:Issue_1374:CAA_spaces
```
This is was happening because provider's CAA handling was splitting fields on spaces, which trashed answers containing  spaces in the 3rd field (ie. splitting the 3rd field into multiple fields)
While dnscontrol has support to handle such cases of fields containing spaces via `ParseQuotedFields`, ns1's client isn't enclosing such fields in quotes and `ParseQuotedFields()` can't work its magic.
So to fix this issue, rework ns1's CAA handling a bit to not use `string.Split(str, " ")` anymore.
While there, clear up panics in the provider and surface errors to be picked and handled as needed.

ns1: fix multivalue CAA handling

---

docs/_providers/hostingde.md
providers/hostingde/api.go
providers/hostingde/hostingdeProvider.go

The hosting.de provider can be used with http.net's offerings too, but http.net uses different nameservers.
This PR adds documentation on how to change the nameservers used and on how to simplify using them, including an example.
Note: Furthermore, it switches to  `fenced_code_blocks` in an effort to improve the legibility when using Markdown preview. If this poses problems, feel free to remove the commit.

Documentation: Customizing nameservers for hosting.de provider

---

providers/azuredns/azureDnsProvider.go
providers/bind/bindProvider.go

Make it easier to debug creds issue by reporting the subscription id.

AZURE_DNS: GetZones error should report subscription id

---

providers/ns1/ns1Provider.go

NS1's API has support for enabling or disabling DNSSEC on zones under
DNSSEC-enabled accounts.
This commit enables support for detecting a zone's DNSSEC state and,
given the autoDNSSEC setting, pushing the right domain corrections
to our corrections stack.
Fixes #1444

ns1: enable autoDNSSEC capability

---

providers/cloudns/cloudnsProvider.go

Let me start by saying thanks for this awesome project - it's exactly what I've been looking for to manage a larger amount of ClouDNS zones with templating support, which I would have almost started implementing myself at a smaller scale if I didn't happen to stumble across DNSControl.
When setting up new ClouDNS zones I've noticed that the error mentioned in issue #1263 occurs due to the API limitation of not supporting a trailing dot for NS records which point to a host within the same zone. The previously merged PR #1303 introduced a fix, but the workaround was only added for modify corrections.
This PR introduces the same workaround when creating new NS records and should therefor fully fix issue #1263. I tested these changes myself and was able to confirm that both create and modify …

CLOUDNS: Fix creation of intra-zone NS records

---

docs/_providers/autodns.md

Fix autodns documentation example javascript.
The provider name was "HETZNER" instead of "AUTODNS".

Fix autodns documentation

---

docs/_includes/matrix.html
integrationTest/integration_test.go

Gandi was failing any DS tests that involved Digest Type 1 (SHA1). I've changed them to type 4 (SHA384).
SHA1 is no longer considered secure.  I assume that Gandi is rejecting it for that reason.  I assume others will make a similar decision eventually.

GANDI_V5: Fix DS test

---

pkg/normalize/validate.go

Fixes 1507
* Skip AuditRecords when running dnscontrol check

dnscontrol check fails when new provider type syntax used

---

Dockerfile

This change makes sure dnscontrol can connect to the providers over https when the Docker image is used.

docker: Add CA certificates to Docker image

---

commands/previewPush.go
go.mod
go.sum
providers/powerdns/powerdnsProvider.go

Proposal which fixes https://github.com/StackExchange/dnscontrol/issues/1369.
It checks with `ListZones()`during preview if the zone already exists, if not, a warning is issued. During push it is ensured that the domain exists. But I'm not quite happy with the flag name, do you have a suggestion?

Create non-existing zones while push or print warning while preview

---

commands/createDomains.go

As we now auto-populate (#1528) domains at the DSP with the `push` command, this PR adds a deprecation notice when running the `create-domains` command.

Add deprecation notice to create-domains command

---

providers/cloudflare/rest.go

This PR prevents segfaults when the Cloudflare API limit (1.2k req per 5mins) is reached and should be handled correctly. 
This PR partially fix #1440, DNSControl will no longer panic and provide a meaningful error message to the user.

FIX: Preventing segfault when Cloudflare API limit is reached

---

Dockerfile

My first attempt to solve the Docker imbroglio. 😅 
Based on the great work from @jauderho 👍 
Fix https://github.com/StackExchange/dnscontrol/issues/1459

New Dockerfile (fix #1459)

---

.circleci/config.yml
pkg/normalize/validate_test.go
providers/autodns/api.go
providers/autodns/autoDnsProvider.go
providers/autodns/types.go
providers/ns1/ns1Provider.go

I would like to suggest that the code must be formatted with `go fmt ./...`, which is checked and enforced by CircleCI.
This results in consistent formatting and has proven to work well in our company.

MAINT: Enforcing formatted code

---

docs/assets/creds.json.tpl-example.txt
docs/creds-json.md

This resolves #1551, adding a mention of how to use the newly added shell command execution, as well as an example template creds.json from my personal DNS repo. Thanks for getting this added!

Add creds.json.tpl file to documentation

---

providers/powerdns/convert.go
providers/powerdns/convert_test.go

The PowerDNS API is quite strange. It accepts long TXTs without requiring to split them and returning them as they came in.
e.g. `"averylooooooo[...]oooooongstring"` or `"string" "string"`
Splitting on DNS level will be done on the fly.

POWERDNS: Cleanup and fix parsing of TXT records

---

README.md

Github no longer supports the unsecured git protocol, so use HTTPS instead.

Use HTTPS for git endpoint for cloning

---

docs/_providers/hetzner.md
integrationTest/integration_test.go

As of 2022-06-23, the Hetzner DNS API is still responding with a 422
when a CAA record contains a quoted value with spaces.
```
format: number of fields does not match record type, expecting 3
```
Their support acknowledged my bug report a few weeks back and suggested
the removal of spaces to get past the limitation.
Spaces in CAA records are not common. Let's just skip the test and put
a notice in the docs.
Signed-off-by: Jakob Ackermann <das7pad@outlook.com>

HETZNER: do not support spaces in CAA records

---

providers/hetzner/hetznerProvider.go
providers/hetzner/types.go

This PR Is updating the handling of TXT/SPF records for https://github.com/StackExchange/dnscontrol/issues/1568.
Together with https://github.com/StackExchange/dnscontrol/pull/1577 the integration tests are passing for the HETZNER provider.
Signed-off-by: Jakob Ackermann <das7pad@outlook.com>

HETZNER: catch up with handling of TXT records

---

providers/transip/transipProvider.go

As requested by tlim, the PopulateFromString has changed and thus
some providers need to handle TXT records differently. See issue
linked below for more information
https://github.com/StackExchange/dnscontrol/issues/1568

Fix population of txt records from TransIP

---

go.mod
go.sum

This updates the software dependency "go-sdk" from v3.5.3 to v3.5.4.
It just adds the output of the HEXONET API endpoint url we use for connecting and communicating when being in debug mode.

chore(hexonet): upgrade dependency go-sdk to v3.5.4

---

docs/_providers/ovh.md
providers/ovh/auditrecords.go
providers/ovh/ovhProvider.go
providers/ovh/protocol.go

OVH only supports arbitrary long string even though it is possible to put more than
one quoted string in a TXT target with the API.
Consequently, the best solution for OVH is to:
* quote the string before emitting to OVH
* unquote if needed when getting the string from OVH
* let dnscontrol know OVH doesn't support multiple TXT strings

Fix handling of TXT for the OVH provider

---

OWNERS
docs/provider-list.md

Anthony delegates all tasks relating to our DNSControl DNSimple integration to me. It would be more efficient to set me as the code owner.
I am an employee of DNSimple and use DNSControl's DNSimple integration in my other projects as well.
CC @aeden in case he needs to sign off.

DNSIMPLE: Change code owner/maintainer

---

commands/getZones.go
commands/test_data/example.org.zone.js
commands/test_data/simple.com.zone.js

* Adopt new single-argument `NewDnsProvider()` syntax.
* Make a `DSP_` variable that is all uppercase.
OLD:
```
$ dnscontrol get-zone --format js providercredkey - stackoverflow.co.il 
var providercredkey = NewDnsProvider("providercredkey", "-");
var REG_CHANGEME = NewRegistrar("ThirdParty", "NONE");
D("stackoverflow.co.il", REG_CHANGEME,
DnsProvider(providercredkey),
DefaultTTL(14400),
A('www', '165.160.15.20'),
...
...
...
//NAMESERVER('dns1.cscdns.net.'),
//NAMESERVER('dns2.cscdns.net.')
)
```
NEW:
```
$ dnscontrol get-zone --format js providercredkey - stackoverflow.co.il
var DSP_PROVIDERCREDKEY = NewDnsProvider("providercredkey");
var REG_CHANGEME = NewRegistrar("none");
D("stackoverflow.co.il", REG_CHANGEME,
DnsProvider(DSP_PROVIDERCREDKEY),
DefaultTTL(14400),
A('www', …
```

get-zones "js" format should generate better DSP variable

---

providers/transip/transipProvider.go

You can use the ALIAS-record with TransIP since September 2021.
- https://www.transip.nl/nieuws/alias-records/

Update TransIP CanUseAlias

---

docs/testing-txt-records.md
pkg/prettyzone/prettyzone_test.go
providers/cloudflare/cloudflareProvider.go
providers/cscglobal/api.go

Due to a stale (empty) cache, we got a number of bugs:
In this example, the provider thinks the zone needs to be added to the account (it doesn't), and the lack of nameservers (they do exist).
```
******************** Domain: collectivesonstackoverflow.co
Added zone for collectivesonstackoverflow.co to Cloudflare account: 
WARNING: Error creating domain: collectivesonstackoverflow.co already exists (1061)
----- Registrar: cscglobal_ltom215...
WARNING: No nameservers declared; skipping registrar. Add {no_ns:'true'} to force.
```

CLOUDFLARE: Fix domain list cache error

---

providers/ns1/ns1Provider.go

NS1 api returns a different message these days, which breaks error handling.
Until a fix is merged upstream, work around the issue by attempting to match the
stray error ourselves.
relates to #1667.
integration & manual tests seem to pass.

ns1: workaround an issue with ns1 API

---

.circleci/config.yml

Make the Docker image build version DOCKER_IMAGE_VERSION aware of the configured version in main.go.
Fixes #1687

CHORE: Docker image - Build version

---

docs/_layouts/default.html

In https://github.com/StackExchange/dnscontrol/pull/1637 jquery was updated to a version not supported by bootstrap version used.
This causes the docs to throw an exception and example expand elements not to work.

Revert jquery update to version supported by bootstrap

---

.goreleaser.yml

Fixes #1709 
Releases are marked Draft now and if you tag with a semver suffix, you'll get a prerelease tagged Release.

CHORE: Define Release parameters

---

providers/desec/protocol.go

Hi all!
I want to use restricted tokens to manage the RRSets of a single domain from a specific server (i.e., this server shouldn't be able to modify other domains in my account). I've noted that while I can use `curl` to modify the domain, dnscontrol failed with `authentication failure`.
According to the [official documentation](https://desec.readthedocs.io/en/latest/auth/tokens.html#token-scoping-domain-policies): "Tokens with at least one policy are considered restricted, with their scope explicitly limited to DNS record management. They can perform neither [Retrieve Account Information](https://desec.readthedocs.io/en/latest/auth/account.html#retrieve-account-information) nor [Domain Management](https://desec.readthedocs.io/en/latest/dns/domains.html#domain-management) (such as domain …

DESEC: Check authentication via domains API

---

go.mod
go.sum
providers/cloudflare/rest.go

We also need to update providers/cloudflare/rest.go to use the new WorkerScriptParams

Bump cloudflare/cloudflare-go from 0.46 to 0.49

---

providers/digitalocean/auditrecords.go
providers/digitalocean/digitaloceanProvider.go

This appears to be a change as it is supported in the interface and in the API. Verified with my own personal domains (e.g. brianandjenny.net)

chore(DigitalOcean): Support semicolon as CAA target

---

go.mod
go.sum
integrationTest/providers.json
providers/exoscale/auditrecords.go
providers/exoscale/exoscaleProvider.go

This PR reworks exoscale provider to use v2 API.
Also fixes https://github.com/StackExchange/dnscontrol/issues/1612
One test case (`07:complex_TXT:TXT_with_1_double-quotes`) fails, however it is not a regression (provider from master also stumbles on it).
Test suite:
```
$ go test -v -verbose -provider EXOSCALE -timeout 30m
...
--- FAIL: TestDNSProviders (1388.06s)                                                                                                                                                                                                [33/1840]
--- FAIL: TestDNSProviders/example.net (1388.06s)                                                                  
--- PASS: TestDNSProviders/example.net/Clean_Slate:Empty (2.88s)                                      
--- PASS: …
```

Exoscale provider: migration to v2 API

---

README.md

The docker image sets the entrypoint to `/usr/local/bin/dnscontrol`

docs: fix docker usage in README

---

docs/getting-started.md

The docker image sets the entrypoint to /usr/local/bin/dnscontrol (same issue as fixed with https://github.com/StackExchange/dnscontrol/pull/1751)

DOCS: fix docker usage in "Getting Started"

---

go.mod
go.sum
providers/vultr/convert_test.go
providers/vultr/vultrProvider.go

Vultr v1 API has been deprecated and govultr has been upgraded to v2.
I've adapted VULTR code to use v2 API instead of v1.
I've tried to test on my side but if someone can confirm changes works that be awesome.

VULTR: use API v2

---

docs/examples.md

Split the Google Workspace (formerly Apps) example. The CNAME DNS records are optional and are sporadically applied within @jcid. Hope it helps others.
**Before**
**After**

DOC: Split the Google Workspace example

---

providers/cloudflare/rest.go

This import https://github.com/StackExchange/dnscontrol/commit/6b9bcd73399a653dfea8b5160c067fba4d078fe6#diff-ec08db23820e61a251ffbe513a350bb25b6fc4c6e2249fe41b07ccb39b6f1636L10 is automatically removed by the GoLand IDE clean-up functionality. Anyway, this PR brings back the missing import.
Fixes failing [CircleCI pipeline - unit tests](https://app.circleci.com/pipelines/github/StackExchange/dnscontrol/1525/workflows/25a81b5c-49fe-4167-9fe2-49a92d125403/jobs/11166).

BUG: Re-introducing the `cloudflare/cloudflare-go` import

---

docs/_providers/transip.md

- Added an split between the two possible authentications `Key Pairs` versus `Access tokens`.
- Added deeplinks to the TransIP control panel.
- Added highlight for the configuration values.
**Before**
**After**

DOCS: Provider TransIP improvements

---

README.md

Added link to the alternative Github action to install the DNSContron inside GitHub workflow.
Previous PR: https://github.com/StackExchange/dnscontrol/pull/1781

Added link to the alternative GitHub action

---

README.md
docs/getting-started.md

The installation section within `README.md` and [Getting started](https://stackexchange.github.io/dnscontrol/getting-started#via-packages) has been aligned/improved in terms of 'package manager'.
**Before**
**After**

DOCS: Aligned/improved installation section package manager

---

README.md
docs/writing-providers.md

It's better to always link to the latest version of the [Go Package](https://pkg.go.dev/github.com/StackExchange/dnscontrol/v3) instead of the [current outdated URL](https://pkg.go.dev/github.com/StackExchange/dnscontrol) with version `v0.2.8` as of `Dec 19, 2018`.
**Before**
https://pkg.go.dev/github.com/StackExchange/dnscontrol
**After**
https://pkg.go.dev/github.com/StackExchange/dnscontrol/v3

DOCS: Updated Go Package URL's to latest version

---

docs/index.md

The number of providers increased from `10+` to `35+` based on the current [Service Providers](https://stackexchange.github.io/dnscontrol/provider-list).

DOCS: Increase provider number

---

docs/_functions/domain/IGNORE_NAME.md
go.sum
integrationTest/integration_test.go
models/dns.go
models/domain.go
pkg/diff/diff.go
pkg/diff/diff_test.go
pkg/js/helpers.js
pkg/js/js.go
pkg/js/parse_tests/005-ignored-records.js
pkg/js/parse_tests/005-ignored-records.json
pkg/js/parse_tests/023-ignored-glob-records.json
providers/dnsimple/dnsimpleProvider.go

Adds record type restrictions to IGNORE_NAME. Useful when only specific records are controlled externally, e.g. a dynamic DNS client manages the `A` record but the rest of the records are managed by `dnscontrol`.
```js
D("example.com",
IGNORE_NAME("foo"), // ignore all record types for name foo
IGNORE_NAME("baz", "*"), // ignore all record types for name baz
IGNORE_NAME("bar", "A,MX"), // ignore only A and MX records for name bar
CNAME("bar", "www"), // CNAME is not ignored
A("baz", "1.2.3.4")
);
```
Fixes #1757

Add rTypes restrictions to IGNORE_NAME

---

OWNERS
README.md
docs/_includes/matrix.html
docs/_providers/gcore.md
docs/provider-list.md
go.mod
go.sum
integrationTest/providers.json
providers/_all/all.go
providers/gcore/auditrecords.go
providers/gcore/convert.go
providers/gcore/gcoreProvider.go

This PR adds support for Gcore DNS (https://gcore.com/dns) using their [Golang SDK](https://github.com/G-Core/gcore-dns-sdk-go).
Code is based on deSEC provider, since Gcore performs incremental-label-type updates.
Passes all integration tests, and tested on my own domain.

NEW PROVIDER: Gcore DNS

---

providers/vultr/convert_test.go
providers/vultr/vultrProvider.go

RecordConfig.Original was set with a pointer that was being reused.
This caused the wrong record to be modified/removed in some cases.

VULTR: Fix setting RecordConfig Original

---

docs/_providers/rwth.md

Hi,
While testing the RWTH provider, I found a mistake in the documentation.
The provider takes `api_token` and not an `api_key`: https://github.com/StackExchange/dnscontrol/blob/master/providers/rwth/rwthProvider.go#L44

RWTH: Fix expected key in documentation

---

OWNERS
README.md
docs/_includes/matrix.html
docs/_providers/porkbun.md
integrationTest/providers.json
providers/_all/all.go
providers/porkbun/api.go
providers/porkbun/auditrecords.go
providers/porkbun/porkbunProvider.go

This PR adds support for Porkbun using their API, close #1295 
Code is mostly based on ClouDNS provider
I have to say Porkbun DNS system is very weird.
1. The web dashboard doesn't show any NS records for the base domain, but API does
2. We can add/modify/delete the default NS records for the base domain, but nothing will change
3. CAA record works well for subdomain, but for the base domain, no matter what you configure, it always becomes,
```
;; ANSWER SECTION:
example.com.            600     IN      CAA     0 issue "comodoca.com"
example.com.            600     IN      CAA     0 issue "digicert.com; cansignhttpexchanges=yes"
example.com.            600     IN      CAA     0 issue "goog.pki"
example.com.            600     IN      CAA     0 issue "letsencrypt.org"
example.com. …
```

PORKBUN: provider init

---

pkg/prettyzone/prettyzone.go

PrettySort doesn't call sort!  Luckily the only code that calls this is the "get-zones" subcommand, and nobody noticed that the output isn't sorted.
By making this change, people using "get-zones" to make their initial dnsconfig.js file will find that their draft D() code is a little prettier.

BUGFIX: PrettySort helper doesn't sort

---

providers/gandiv5/auditrecords.go

Fixes https://github.com/StackExchange/dnscontrol/pull/1846
I have no issues setting an MX to `.`.
```
filosottile.info.	1800	IN	MX	0 .
filosottile.info.	10800	IN	NS	ns-189-c.gandi.net.
filosottile.info.	10800	IN	NS	ns-232-a.gandi.net.
filosottile.info.	10800	IN	NS	ns-92-b.gandi.net.
```

gandiv5: drop null MX rejection

---

pkg/normalize/flatten.go

Every time the SPF optimizer splits an SPF record it doesn't it slightly differently even given the same input. The output is always correct, just different.  This makes it difficult to test the code, since every run is slightly different.
With this change the output is always the same given the same inputs.
Fixes https://github.com/StackExchange/dnscontrol/issues/1863

BUG: SPF split doesn't produce consistent output

---

providers/gcore/convert.go
providers/gcore/gcoreExtend.go
providers/gcore/gcoreProvider.go

- Implement diff2 method, tested with `go test -v -verbose -provider GCORE -diff2`
- Use a hidden API only documented in Gcore's OctoDNS provider (`https://api.gcorelabs.com/dns/v2/zones/example.com/rrsets?all=true`, documented at <https://github.com/octodns/octodns-gcore/blob/main/octodns_gcore/__init__.py#L105>), to get all record sets in one HTTP request instead of many requests. This greatly improves performance handling large zones.

GCORE: Implement diff2 and greatly improve performance for getting record sets

---

docs/_providers/axfrddns.md
providers/axfrddns/axfrddnsProvider.go
providers/axfrddns/md5Provider.go

Go officially does not support MD5 for TSIG. Sadly we have a provider that requires the usage of MD5. This PR adds the missing support ;-)

Add missing MD5 support

---

providers/oracle/oracleProvider.go

When testing #1897, I found that the `TypeChange:Change_to_A_record` test was failing. This PR fixes that and cleans up the corrections code.
This branch is based on top of the changes in #1897.

oracle: resolve "change to A" test fail

---

docs/_providers/inwx.md

Small typo in the name `Cloudflare`.
```diff
-CloudFlare
+Cloudflare
```
_https://www.cloudflare.com/en-gb/#:~:text=Cloudflare_

DOCS: Typo `CloudFlare`

---

OWNERS

Corrected the wrong directory name in `OWNERS` for `GandiV5`.
```diff
-providers/gandi_v5 @TomOnTime
+providers/gandiv5 @TomOnTime
```
_https://github.com/StackExchange/dnscontrol/tree/master/providers/gandiv5_

gandiv5: Wrong directory name in OWNERS

---

providers/netcup/types.go

This should fix #1362 and address the concerns there

NETCUP: Handle CNAMEs with a single @ as destination correctly

---

providers/hostingde/types.go

hosting.de expects PTR records to not have a trailing dot.

HOSTINGDE: Fix PTR records

---

providers/netlify/auditrecords.go
providers/netlify/netlifyProvider.go

Netlify no longer splits TXT records into multiple, and cannot handle empty TXT records
Tests: All integration tests pass on `diff` and `diff2`

NETLIFY: Fix TXT record handling

---

documentation/functions/global/DOMAIN_ELSEWHERE.md
documentation/functions/global/DOMAIN_ELSEWHERE_AUTO.md

Added the TypeScript typing missing parameter `name` for `DOMAIN_ELSEWHERE` and `DOMAIN_ELSEWHERE_AUTO`.
cc: @j-f1

TypeScript typing: missing parameter

---

documentation/functions/domain/CAA.md
documentation/functions/record/CAA_BUILDER.md

- Remove the supported disclaimer, `CAA()` is [supported by almost all DNSControl providers](https://docs.dnscontrol.org/service-providers/providers#:~:text=CAA).
- Added code highlights.
- Applied number list.
- Crosslink to `CAA_BUILDER()` and  `CAA()`.

DOCS: [CAA] General improvements

---

providers/transip/transipProvider.go

```shell
~/dnscontrol/ dnscontrol get-zones transip - all
```
```text
$ORIGIN cafferata.dev.
$TTL 86400
@                IN MX    10 ASPMX.l.google.com.
IN MX    20 alt1.ASPMX.l.google.com.
IN MX    30 alt2.ASPMX.l.google.com.
IN MX    40 ASPMX2.googlemail.com.
IN MX    50 ASPMX3.googlemail.com.
IN MX    60 ASPMX4.googlemail.com.
IN MX    70 ASPMX5.googlemail.com.
IN TXT   "v=spf1 -all"
```
cc: @blackshadev

TRANSIP: Implementation get-zones all

---

commands/commands.go
commands/commands_test.go
documentation/functions/global/D.md

The `preview` and `push` commands accept a flag `--domains` which restricts which domains are processed.  Currently they are exact matches.  This PR permits a wildcard at the start of the string.  In other words `--domains foo.com,*.10.in-addr.arpa` will match `foo.com`, `0.0.0.10.in-arpa.com`, but not `0.0.0.6.in-addr.arpa.com`.
The goal here isn't to add a complete glob match. We can add that later.

Domains flag should accept simple wildcards

---

providers/transip/transipProvider.go

The SRV record content must be in the format "priority weight port target".
```shell
cd integrationTest
go test -v -verbose -provider TRANSIP
```
**Before**
```text
=== RUN   TestDNSProviders/cafferata.dev/21:SRV:SRV_record
integration_test.go:223: CREATE SRV _sip._tcp.cafferata.dev 5 6 7 foo.com. ttl=300
integration_test.go:227: the SRV record content must be in the format "priority weight port target": _sip._tcp 300 SRV 6 7 foo.com.
```
**After**
```text
=== RUN   TestDNSProviders/cafferata.dev/00:SRV:SRV_record
integration_test.go:223: CREATE SRV _sip._tcp.cafferata.dev 5 6 7 foo.com. ttl=300
=== RUN   TestDNSProviders/cafferata.dev/00:SRV:Second_SRV_record,_same_prio
integration_test.go:223: CREATE SRV _sip._tcp.cafferata.dev 5 60 70 foo2.com. ttl=300
=== RUN …
```

BUG: TRANSIP: Wrong SRV record content

---

documentation/providers.md

Remove the superfluous anchor from the Markdown header.

DOCS: Providers remove anchor

---

documentation/providers/axfrddns.md

Fixed the broken GitHub link on the [AXFR+DDNS page](https://docs.dnscontrol.org/service-providers/providers/axfrddns#fyi-md5-support:~:text=the%20used%20DNS-,Go%20package%20by%20miekg,-has%20deprecated%20supporting).

DOCS: [AXFR+DDNS] Fixed broken GitHub link.

---

documentation/functions/domain/NAMESERVER_TTL.md

The wrong domain-modifiers name was applied for `NAMESERVER_TTL()`.

DOCS: NAMESERVER_TTL wrong domain-modifiers name

---

providers/transip/auditrecords.go

Checked the Audit records through the [TransIP API](https://api.transip.nl/rest/docs.html#domains-dns-post).
`POST /v6/domains/cafferata.dev/dns`
**Request**
```json
{
"dnsEntry": {
"name": "@",
"expire": 86400,
"type": "MX",
"content": ""
}
}
```
**Response**
```json
{
"error": "the content of an MX record must be in the format \"priority target\": @ 86400 MX \nrecord content cannot be empty: @ 86400 MX "
}
```
```json
{
"dnsEntry": {
"name": "@",
"expire": 86400,
"type": "TXT",
"content": "`"
}
}
```
**Response**
```json
{
"error": "the content of a TXT record cannot contain invalid characters: @ 86400 TXT `"
}
```
```json
{
"dnsEntry": {
"name": "@",
"expire": 86400,
"type": "TXT",
"content": "ms=123456 "
}
}
```
**Response**
```json
{
"error": "whitespace at the end or start of the …
```

TRANSIP: Audit records

---

.goreleaser.yml
README.md
commands/getZones.go
commands/previewPush.go
dnscontrol.nuspec
pkg/normalize/validate.go
providers/bind/bindProvider.go

Replace `stackexchange.github.io` with `docs.dnscontrol.org` for the homepage and pages.

DOCS: Replace stackexchange.github.io

---

README.md

Fixed the [Changelog v3.16.0](https://docs.dnscontrol.org/release/v316) URL in the [README](https://github.com/StackExchange/dnscontrol#:~:text=get%2Dzones%20syntax%20changes%20in%20v3.16).

DOCS: [README] Fixed Changelog v3.16.0 URL

---

documentation/functions/global/DOMAIN_ELSEWHERE.md
documentation/functions/global/DOMAIN_ELSEWHERE_AUTO.md

I've split the two comparison [`DOMAIN_ELSEWHERE()`](https://docs.dnscontrol.org/language-reference/top-level-functions/domain_elsewhere) and [`DOMAIN_ELSEWHERE_AUTO()`](https://docs.dnscontrol.org/language-reference/top-level-functions/domain_elsewhere_auto) code blocks for better readability and copy/paste development.

DOCS: [GitBook] Code block syntax

---

integrationTest/integration_test.go
pkg/normalize/validate.go
pkg/normalize/validate_test.go
providers/ns1/ns1Provider.go

This changeset improves handling for NS1_URLFWD inside dnscontrol's code:
* Adds integration tests for the record, confined to NS1.
* Replaces `strings.Split()` with `strings.Fields()` in URLFWD's case. While there, other occurrences of it in MX and SRV code are replaced for the same reasons.
* Adds code under `pkg/normalize/validate.go` and relevant tests to ensure record's format is always validated on parsing time.

NS1: Improve NS1_URLFWD handling

---

.github/pull_request_template.md

@tlimoncelli https://github.com/StackExchange/dnscontrol/pull/1996#issuecomment-1407388782
>Internally we're discussing moving to a new build pipeline. Until that decision is made, I don't want to invest too much in the pipeline. However adding it to the docs is fine.
The Go format and Go mod tidy commands listed within the GitHub pull request template.
See [GitHub docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).

DOCS: GitHub pull request template

---

providers/hostingde/api.go
providers/hostingde/hostingdeProvider.go

Fixes #1974
Note: This includes the changes from #2019, because subaccount filtering is meant for the listing all zones feature.

HOSTINGDE: Implement subaccount filtering feature (fixes #1974)

---

build/generate/functionTypes.go
commands/types/dnscontrol.d.ts

While looking at https://github.com/StackExchange/dnscontrol/pull/2029, I noticed that some template tags had made it into the generated doc comments.

Remove all template tag lines from the .d.ts file

---

providers/hostingde/hostingdeProvider.go

This fixes an dnssec error resulting from non-go-conformant comparison of three values (introduced due to my limited go experience :-))

HOSTINGDE: Fix dnssec error resulting from non-go-conformant comparison of three values

---

.gitignore

The directory `docs/_site` no longer exists.

CHORE: Removed docs/_site from .gitignore

---

providers/msdns/auditrecords.go
providers/msdns/convert.go
providers/msdns/powershell.go

* BUGFIX: TXT records were not being created properly.  SetTargetTXTfromRFC1035Quoted was used when SetTargetTXT() was needed.
* FEATURE: When a PowerShell command has an error, output the PowerShell code to assist in debugging.

MSDNS: Fix TXT records handling. Make debugging easier by outputting PS code on error

---

providers/hostingde/api.go
providers/hostingde/hostingdeProvider.go
providers/hostingde/types.go

I noticed an issue where if you enable autodnssec, and then disable it, the DS key is left at the domain, resulting in the zone not being able to be used anymore. (Because it's not signed anymore)
This PR fixes that.

HOSTINGDE: Remove dnssec key from domain upon autodnssec disable

---

commands/createDomains.go
commands/previewPush.go
providers/akamaiedgedns/akamaiEdgeDnsProvider.go
providers/azuredns/azureDnsProvider.go
providers/cloudflare/cloudflareProvider.go
providers/cloudns/cloudnsProvider.go
providers/desec/desecProvider.go
providers/digitalocean/digitaloceanProvider.go
providers/dnsmadeeasy/dnsMadeEasyProvider.go
providers/exoscale/exoscaleProvider.go
providers/gcloud/gcloudProvider.go
providers/gcore/gcoreProvider.go
providers/hedns/hednsProvider.go
providers/hetzner/hetznerProvider.go
providers/hexonet/domains.go
providers/hostingde/hostingdeProvider.go
providers/inwx/inwxProvider.go
providers/ns1/ns1Provider.go
providers/oracle/oracleProvider.go
providers/powerdns/dns.go
providers/providers.go
providers/route53/route53Provider.go
providers/vultr/vultrProvider.go

`DomainCreator` and `EnsureDomainExists` are misleading, because it actually creates zones, not domains.

Rename DomainCreator to the more accurate ZoneCreator

---

.circleci/config.yml

Fixes #1844 
I believe the `release` job is reusing the binaries from the `build` job which was hard coded to build a "snapshot" which is unversioned.
This PR removes `--snapshot` flag for workflows triggered by a tag push - the trigger that invokes `release`.

FIX: Release binaries don't contain semver string

---

go.mod
go.sum
main.go
pkg/diff/diff.go
providers/axfrddns/axfrddnsProvider.go

When using dnscontrol in CI/CD pipelines or changing several records/zones at once the output can be quite confusing. In order to make the output clearer, we would like to highlight the different operations in color.

NEW FEATURE: Colorize preview/push output

---

go.mod
go.sum

No relevant TransIP API endpoints or DNSControl implementations have been changed. cc: @blackshadev
See the GitHub change log:
https://github.com/transip/gotransip/releases/tag/v6.18.0

TRANSIP: Update go module to v6.18.0

---

pkg/normalize/validate.go

Verify that registrar and dns providers match if autodnssec is enabled (#2056)

---

go.mod
go.sum

No relevant TransIP API endpoints or DNSControl implementations have been changed. See the GitHub change log [transip/gotransip v6.19.0](https://github.com/transip/gotransip/releases/tag/v6.19.0). cc: @blackshadev

TRANSIP: Update go module to v6.19.0

---

commands/previewPush.go

Comparing the ace zone name should fix #2096

BUGFIX: dnscontrol complains that the zones for IDNA domains do not exist (#2096)

---

pkg/normalize/validate.go

This makes check/preview/push fail if a CNAME is pointing at itself.  That would be a loop.
This doesn't stop someone from creating a longer loop (a -> b -> c -> a) but at least it will catch the most simple case.

FEATURE: Detect simple CNAME loops

---

documentation/providers/transip.md

Fixed TransIP `creds.json` example file, it is missing a comma and is therefore an invalid JSON structure. 
The origin: https://github.com/StackExchange/dnscontrol/pull/1212

DOCS: TransIP: Fixed creds.json example

---

documentation/adding-new-rtypes.md

Added [GitBook code blocks](https://docs.gitbook.com/tour/editor/blocks/code-block) syntax to '[Creating new DNS Resource Types](https://docs.dnscontrol.org/developer-info/adding-new-rtypes)'.

DOCS: [GitBook] Added code blocks syntax

---

documentation/adding-new-rtypes.md
documentation/get-zones.md
documentation/writing-providers.md

Fixed the incorrect directory path `docs` to `documentation`.

DOCS: Fixed incorrect documentation directory path

---

build/generate/functionTypes.go

My IDE compiled an .md file to .html in the documentation folder.
The usual:
```
go fmt ./...
go generate
go mod tidy
```
started to crash inexplicably. No warning or error messages. WTF.
This change means we recover successfully from parseFrontMatter() and ID the offending file.
Hint: `generate` does not like stray .html files in the documentation folder. :/

Fix obscure 'go generate' crash.

---

build/generate/functionTypes.go
pkg/diff2/compareconfig.go
pkg/diff2/diff2.go

Fixing these...
```
build/generate/functionTypes.go:47:9: if block ends with a return statement, so drop this else and outdent its block
build/generate/functionTypes.go:48:30: error strings should not be capitalized or end with punctuation or a newline
pkg/diff2/compareconfig.go:46:6: exported type ComparableFunc should have comment or be unexported
pkg/diff2/compareconfig.go:48:6: exported type CompareConfig should have comment or be unexported
pkg/diff2/compareconfig.go:91:1: exported function NewCompareConfig should have comment or be unexported
pkg/diff2/compareconfig.go:111:1: exported method CompareConfig.VerifyCNAMEAssertions should have comment or be unexported
pkg/diff2/diff2.go:16:6: exported type Verb should have comment or be unexported
pkg/diff2/diff2.go:20:2: exported const …
```

CHORE: linting

---

pkg/normalize/validate.go

* The AutoDNSSEC validation should be a warning, not an error
* Disable the warning if the provider's name is "NONE".

BUG: AutoDNSSEC validation is too aggressive

---

pkg/normalize/validate.go
pkg/normalize/validate_test.go

Fixes https://github.com/StackExchange/dnscontrol/issues/2190

BUG: TTL consistency check should be on ResourceSet, not Label

---

documentation/SUMMARY.md

This pull request fixed the broken `LOC_BUILDER_STR({})` link on [LOC](https://docs.dnscontrol.org/language-reference/domain-modifiers/loc). https://github.com/StackExchange/dnscontrol/pull/2188 https://github.com/StackExchange/dnscontrol/pull/2183 cc: @systemcrash

DOCS: Fixed LOC_BUILDER_STR filename

---

providers/dnsimple/dnsimpleProvider.go

Fix #2157 
The dnsimple API returns
```
Content:"1 993 mail.messagingengine.com."
```
when fetching the records.
The code here I think was to make up for the lack of a `.` for the final field.  This would work if the contents were `1 993 mail.messagingengine.com. ` which would become `1 993 mail.messagingengine.com. .` but since there's no final space it becomes `1 993 mail.messagingengine.com..` (unlike `Split`, `Fields` ignores trailing delimiters).
I think this was not necessary anyways, since `SetTargetSRVPriorityString` does the same thing, but skips this extra work (and encoding error risk) of re-encode-decode by passing `"."` as a separate parameter to the next function.
This solved my reported issue, but I'm not sure if it's possible to get other SRV record formats from the API …

Don't add extra dot after dnsimple SRV record contents

---

.goreleaser.yml
documentation/writing-providers.md

Are changelogs still produced/needed?
This could potentially be automated by enforcing a 'subject' line in commit texts, that goes e.g.
thingprovider: added flibbonacci decorator
Although I don't seem to see any PR commit message text included.

Update goreleaser providers regexp

---

models/dns_test.go
models/record.go

REFACTOR: export models func downcase()

---

providers/hedns/hednsProvider.go

This fixes support for LOC records which until were erroneously indicated as supported, despite not working correctly. With this fix, the changes in https://github.com/StackExchange/dnscontrol/issues/2214 all pass correctly for the HEDNS provider.

HEDNS: Fix support for LOC records

---

providers/loopia/auditrecords.go

`Record pointing to @` test passes fine, however.

LOOPIA: Ban Null MX

---

integrationTest/integration_test.go

CC @rblenkinsopp for visibility.
Disabling the pager101 test for HEDNS.
The pager101 test adds 3 minutes to the HEDNS integration test.  pager101 is irrelevant for HEDNS because there's no paging involved (updates are one 1 record at a time, downloading the DNS records is done in one API call).

TESTING: Skip slow+useless tests for HEDNS

---

providers/loopia/convert.go

See issue #2218 
```text
=== RUN   TestDNSProviders/example.com
=== RUN   TestDNSProviders/example.com/Clean_Slate:Empty
integration_test.go:223:
records affected by deletion of subdomain *.example.com
- DELETE A *.example.com 194.9.94.85 ttl=3600
- DELETE A *.example.com 194.9.94.86 ttl=3600
integration_test.go:223:
records affected by deletion of subdomain www.example.com
- DELETE A www.example.com 194.9.94.85 ttl=3600
- DELETE A www.example.com 194.9.94.86 ttl=3600
integration_test.go:223:
- DELETE A example.com 194.9.94.85 ttl=3600
integration_test.go:223:
- DELETE A example.com 194.9.94.86 ttl=3600
integration_test.go:223:
± MODIFY NS example.com: (ns2.loopia.se. ttl=3600) -> (ns2.loopia.se. ttl=300)
integration_test.go:223:
± MODIFY NS example.com: …
```

Loopia: now passes test: 18:testByRecordSet

---

documentation/providers/dnsimple.md
providers/dnsimple/auditrecords.go

DNSimple has updated how their validators work and fixed the inability to handle whitespace in CAA target records.
I also verified that all the other audits are still required and updated their comments.

DNSimple: Remove CAA Whitespace in Target restriction

---

providers/hexonet/domains.go
providers/hexonet/records.go

Hi @tlimoncelli 
while testing we applied some minor cleanup / refactoring to our integration.
Do you mind taking over the changes?
Thanks!
Kai

HEXONET: minor refactoring

---

documentation/providers.md
documentation/providers/hetzner.md
integrationTest/providers.json
providers/hetzner/api.go
providers/hetzner/auditrecords.go
providers/hetzner/hetznerProvider.go
providers/hetzner/types.go

This PR includes a rework for the rate-limiting following API changes. The integration tests complete in about 4min now -- down from 12min. All the settings options were removed.
I restored a few TXT integration tests that were commented out in #2128, they validate the hacks that were added via https://github.com/StackExchange/dnscontrol/pull/1069 (the hacks are still needed, just tested). It might be worth adding a comment to the tests that they are useful for the HETZNER provider. WDYT?
Per the comments in https://github.com/StackExchange/dnscontrol/issues/598#issuecomment-587713630 I did not restore the zero width TXT test-case.
Let me know if you want the test changes separated into a separate PR.
I've updated the compatibility map with the latest state of the API. The tests for DS …

HETZNER: provider maintenance

---

documentation/typescript.md

Per #2263 :) This will help reduce confusion on TypeScript setup.

DOCS: add reference tag for TypeScript server to recognise the type definitions

---

documentation/providers/msdns.md

Added optional variables of psusername and pspassword
Found in source code at dnscontrol/providers/msdns/powershell.go

MSDNS: Document pssession options

---

providers/hexonet/records.go

```
$ staticcheck ./...
providers/hexonet/records.go:61:71: argument actual is overwritten before first use (SA4009)
providers/hexonet/records.go:63:2: assignment to actual
```

HEXONET: Remove duplicate code

---

commands/previewPush.go

Sadly the flag library we use doesn't support having a global flag that is also a subcommand flag.  Luckily I never wrote an example that used this feature.  
These are the only uses that work (and have been seen in examples)
```
dnscontrol preview 
dnscontrol --diff2=false preview 
dnscontrol --diff2 preview 
dnscontrol --diff2=true preview 
```

BUG: diff2 flag can not work in both places

---

documentation/providers/powerdns.md
providers/powerdns/dns.go
providers/powerdns/powerdnsProvider.go

This PR adds a option to the PowerDNS provider to set the zone kind when creating a new zone.
If this is not specified in the request, PowerDNS uses `Native`, which results in the zone not being transfered via AXFR/IXFR. `Native` is used to let the storage backend of PDNS handle the replication.
The PR does not break the default behavior, if it is not set, the zone is still created with the `Native` type.
I'm currently waiting for a second tester to test this.

POWERDNS: Add option to set the PowerDNS zone kind

---

providers/hetzner/hetznerProvider.go

As per https://github.com/StackExchange/dnscontrol/issues/491#issuecomment-1529072560 hetzner started being affected by the trailing dots on nameservers thing.
My config stopped reporting this error with the change, not sure if you wanted a specific test for this situation to be added.
cc @das7pad as currently listed hetzner maintainer

HETZNER: fix nameserver trailing dots

---

integrationTest/integration_test.go

As suggested in https://github.com/StackExchange/dnscontrol/pull/2301#pullrequestreview-1408080979 this PR is adding an integration test for checking that dnscontrol providers remove any trailing dot from nameservers as returned by the respective dns provider (https://github.com/StackExchange/dnscontrol/issues/491).
_The next time all maintainers run the tests we might see a few remaining providers fix their handling of nameservers. The test failure message points them right at the solution._
Closes https://github.com/StackExchange/dnscontrol/issues/2307

TESTING: add integration test for no trailing dot in nameservers

---

integrationTest/integration_test.go
pkg/normalize/validate.go
pkg/normalize/validate_test.go

URLFWD isn't a real record type. There's no need to maintain both a "virtual" type and an alias type when there's a single implementation.
Discussed in #2319.

NS1 Fix URLFWD implementation by being more consistent

---

providers/ns1/ns1Provider.go

Fixes https://github.com/StackExchange/dnscontrol/issues/2317
Fixes https://github.com/StackExchange/dnscontrol/issues/2319

NS1: revert #2295 (nameserver "trailing dot" issue)

---

.github/workflows/build.yml
.github/workflows/release.yml

Migrate functionality from CCI pipeline to GHA release workflow
* Change release workflow trigger from release published to push with tag filter
* Add goreleaser to GHA release pipeline

ci: add goreleaser to release pipeline

---

.github/workflows/release.yml

Release workflow had both branch and tag filters but they are not evaluated as a boolean "and" and will trigger the workflow separately.  Removed push on branch filter and fixed tag filters to trigger on semantic releases.

ci: fix release workflow trigger

---

.github/workflows/release.yml

goreleaser requires docker login before it is run if pushing docker images

ci: add docker login for goreleaser

---

.github/workflows/draft_release.yml
.github/workflows/release.yml

goreleaser is configured to create a draft release which should have the release notes [edited](https://docs.dnscontrol.org/release/release-engineering#step-3.-create-the-release-notes) before the GHA release workflow is run (as specified by the trigger `release: types: [published]`.  Consolidated logic after migrating from CCI but logic for drafting the release needs to be split out to maintain overall release workflow.

ci: split draft release logic into separate workflow

---

Dockerfile

Alpine 3.17.3 has a few vulns per Trivy scan.
```
stackexchange/dnscontrol:v3.31.5 (alpine 3.17.3)
Total: 2 (MEDIUM: 2, HIGH: 0, CRITICAL: 0)
┌────────────┬───────────────┬──────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability │ Severity │ Installed Version │ Fixed Version │                           Title                            │
├────────────┼───────────────┼──────────┼───────────────────┼───────────────┼────────────────────────────────────────────────────────────┤
│ libcrypto3 │ CVE-2023-1255 │ MEDIUM   │ 3.0.8-r3          │ 3.0.8-r4      │ Input buffer over-read in AES-XTS implementation on 64 bit │
│            │               │          │                   │               │ ARM …
```

Update Dockerfile to use Alpine 3.18

---

.goreleaser.yml

Based on this [conversation](https://github.com/StackExchange/dnscontrol/pull/2363/files#r1197045183) release the Docker images without the "v" in the versions.
_https://hub.docker.com/r/stackexchange/dnscontrol/tags?name=4.0.1_

CI: Release Docker images without the "v"

---

providers/desec/desecProvider.go

close #2346
the zones list are already loaded in provider initialize, this PR simply load the local cache to implement ListZones
https://github.com/StackExchange/dnscontrol/blob/0edffa198b0a09acdf086cb6fa7026a7aaef628c/providers/desec/protocol.go#L82-L127
```
desec.esd.cc
```

DESEC: implement ListZones

---

documentation/examples.md
documentation/providers/cloudflareapi.md
documentation/providers/desec.md
documentation/providers/gcore.md
documentation/providers/route53.md
documentation/providers/softlayer.md
documentation/providers/transip.md

Provided the `dnsconfig.js` code examples with the missing provider constants.

DOCS: Code examples missing provider constants

---

documentation/getting-started.md
documentation/providers/hexonet.md
documentation/providers/loopia.md

Only in these three places are comments used in the `dnsconfig.js` code examples. I suggest drawing one line and deleting these comments.

DOCS: Removed comments from `dnsconfig.js` code examples

---

providers/cloudflare/cloudflareProvider.go

This change allows the environment variable CLOUDFLAREAPI_DEBUG to be set to enable logging of all the Cloudflare API interactions. Modeled on GANDI_V5_DEBUG in gandi_v5Provider.go.

CLOUDFLAREAPI: Allow API debugging to be enabled via env variable

---

build/generate/dtsFile.go
build/generate/functionTypes.go
commands/types/dnscontrol.d.ts
commands/types/fetch.d.ts
commands/types/others.d.ts
documentation/functions/domain/IGNORE.md

- Fix types for `IGNORE` — it’s a function, not a constant
- Add support for copying file content into the TypeScript doc comments, which allows the `FETCH` comment to be pulled from the doc file automatically (along with any other future functions which are too complex to type using the simple options provided in the front matter today)
- Update `IGNORE_NAME_DISABLE_SAFETY_CHECK` doc comment to mark it as deprecated (e.g. VS Code will draw a line through it in the editor and not suggest it as readily in autocomplete)
- strip trailing whitespace from lines in the generated .d.ts file
- Re-generate .d.ts file

DOCS: TypeScript updates

---

.github/workflows/draft_release.yml
.goreleaser.yml

This adds the support to also push container images to GitHub Container Registry (ghcr.io)
The goreleaser code change have been briefly tested here ([minor changes to disable other builds](https://github.com/Firefishy/dnscontrol/commit/bc0c066aa18d9e1a3b4d643c5e22b22dd6f752ac)): https://github.com/Firefishy/dnscontrol/actions/runs/5153372408/jobs/9280525081 (👍 docker build/push worked, push GH release failed) and the GitHub container images are published here: https://github.com/Firefishy/dnscontrol/pkgs/container/dnscontrol

CICD: Also push container images to GitHub Container Registry (ghcr.io)

---

providers/inwx/inwxProvider.go

Sorry for the delay. Was able to root-cause and fix the failing PTR test.
Running it with today's code:
```
$ go test -v -verbose -timeout 0 -provider INWX -start 28 -end 28
=== RUN   TestDNSProviders/domain.tld
=== RUN   TestDNSProviders/domain.tld/Clean_Slate:Empty
integration_test.go:244:
- DELETE PTR 4.domain.tld foo.com. ttl=300
=== RUN   TestDNSProviders/domain.tld/28:PTR:Create_PTR_record
integration_test.go:244:
+ CREATE PTR 4.domain.tld foo.com. ttl=300
=== RUN   TestDNSProviders/domain.tld/28:PTR:Modify_PTR_record
integration_test.go:244:
± MODIFY PTR 4.domain.tld: (foo.com. ttl=300) -> (bar.com. ttl=300)
=== RUN   TestDNSProviders/domain.tld/Post_cleanup:Empty
integration_test.go:244:
- DELETE PTR 4.domain.tld bar.com. ttl=300
--- PASS: …
```

INWX: Fix PTR test failing/unexpected PTR modify operation

---

Dockerfile

Add the required runtime dependencies for running dnscontrol in a container.
* tzdata - Go time required external dependency. See: #2422
* ca-certificates - Required for HTTPS to work out-of-the-box without throwing CA errors
Fixes: #2422
Link: #2429

CHORE: Add runtime dependencies for container

---

providers/digitalocean/digitaloceanProvider.go

Added a `ListZones()` function to the Digitalocean provider to satisfy the `ZoneLister` interface.
Previous behavior
```
> dnscontrol get-zones do_provider - all
provider type do_provider:- cannot list zones to use the 'all' feature
```
After change
```
> /workspaces/Misc/dnscontrol/dnscontrol get-zones do_provider - all
$ORIGIN example.com
$TTL 300
@          1800  IN NS    ns1.digitalocean.com.
1800  IN NS    ns2.digitalocean.com.
1800  IN NS    ns3.digitalocean.com.
[...truncated...]
```

DIGITALOCEAN: Enable get-zones "all" feature (implement ListZones())

---

documentation/providers/linode.md
integrationTest/integration_test.go
providers/linode/linodeProvider.go
providers/linode/linodeProvider_test.go

This adds `0` as an allowed TTL for Linode, which is Linode's default TTL.
I've also re-ran the integration tests and changed the `not` functions to match what is currently failing/passing.
Fixes https://github.com/StackExchange/dnscontrol/issues/2440

LINODE: Add Default TTL as allowed TTL

---

commands/getZones.go

Fixing a teensy nitpick typo in the get-zones cli help
glcoud -> gcloud
```go
EXAMPLES:
...
dnscontrol get-zones --format=djs --out=draft.js glcoud GCLOUD example.com
```

dnscontrol get-zones --help typo fix

---

.github/workflows/build.yml

Enable NS1 credentials so that we can spawn CI tests with them.

NS1: Enable BYO secrets for NS1 in the CI/CD pipeline

---

README.md
documentation/getting-started.md

The old example specifies each file DNSControl might want to access, which is brittle.  It also doesn't work for the "fmt" subcommand.
The new example it shorter and works for all subcommands.

DOCS: Improved docker instructions

---

.goreleaser.yml
OWNERS
README.md
documentation/SUMMARY.md
documentation/providers.md
documentation/providers/mythicbeasts.md
integrationTest/providers.json
providers/_all/all.go
providers/mythicbeasts/auditrecords.go
providers/mythicbeasts/mythicbeastsProvider.go

This PR adds a domain provider for https://www.mythic-beasts.com/, following the guide in https://docs.dnscontrol.org/developer-info/writing-providers.
The API used is roughly:
* HTTP GET, which returns a RFC 1035 zonefile.
* HTTP PUT, which accepts an RFC 1035 zonefile, and replaces your zone with that.
This easily integrates with the declarative model of dnscontrol, and existing RFC 1035 parsing/printing functionality.
Tested:
* Passes https://docs.dnscontrol.org/developer-info/integration-tests: `ok  	github.com/StackExchange/dnscontrol/v4/integrationTest	549.708s`.
* on my own domains
References:
* DNS hosting features: https://www.mythic-beasts.com/domains
* API docs: https://www.mythic-beasts.com/support/api/dnsv2

NEW PROVIDER: Mythic Beasts DNS

---

integrationTest/integration_test.go
providers/ovh/protocol.go

FIxes #2488
DKIM, SPF, DMARC OVH native records (such as when created in the UI) couldn't be managed by dnscontrol natively because of various issue (for instance it is not possible to update such record and change their type).
This implements native handling of those records when they already exist in the zone and manage them as TXT record without changing their native types. This patch also adds a bunch of integration tests specific to OVH to make sure we don't get any regressions in the future.
To be noted that it is not possible to create such native OVH records (outside of what has been done in the integration tests).

OVH: allow native OVH records for DKIM, etc. to be managed

---

providers/msdns/powershell.go
providers/msdns/powershell_test.go

Theory: The go-powershell module we use has problems if the command doesn't start and end with whitespace.
As a quick fix, we add that whitespace.
The long-term fix would require us to fork go-powershell and add the whitespace to the Execute() function.

MSDNS: Improve PowerShell reliability

---

providers/netlify/api.go
providers/netlify/netlifyProvider.go

1. fix SRV priority
In the following case,
```
SRV('_jmap._tcp', 0, 1, 443, 'api.fastmail.com.')
```
with the `omitempty` attr, Netlify will treat priority as unset and put a default value 10 in it
Which will cause DNSControl to try to correct it on every push
```
MODIFY SRV _jmap._tcp.example.com: (10 1 443 api.fastmail.com. ttl=3600) -> (0 1 443 api.fastmail.com. ttl=3600)
```
This PR removes `omitempty` from priority
2. allow apex NS records
Netlify seems to allow changing the apex NS records now, so I remove the limitation.
(web dashboard)
(dig result)
---
All testes passed.
```
--- PASS: TestDNSProviders (628.04s)
--- PASS: TestDNSProviders/example.com (628.04s)
--- PASS: TestDNSProviders/example.com/Clean_Slate:Empty (3.40s)
--- PASS: TestDNSProviders/example.com/00:A:Create_A …
```

NETLIFY: fix SRV priority and allow apex NS records

---

documentation/providers.md
providers/cloudflare/cloudflareProvider.go
providers/cloudflare/rest.go

Add support for NAPTR records to cloudflare provider.
(#2547)

CLOUDFLAREAPI: Add NAPTR record support

---

commands/previewPush.go
documentation/SUMMARY.md
documentation/json-reports.md

We want to execute some actions after running dnscontrol. To reduce the amount of actions and improve the speed this PR adds a report option that generates a JSON file containing the Domain, the amount of performed actions and the Provider/Registrar. 
Afterwards we can parse the json and identify the domains that were changed and ignore those that kept unchanged.

NEW FEATURE: Added "push --report" flag which generates JSON report of changes made

---

pkg/normalize/validate.go
pkg/normalize/validate_test.go

Fixes https://github.com/StackExchange/dnscontrol/issues/2564

CHORE: Clean up checkRecordSetHasMultipleTTLs

---

documentation/providers/inwx.md

As requested in https://github.com/StackExchange/dnscontrol/issues/2512#issuecomment-1741285970 I have updated the documentation. Also added note regarding the new accounts feature and spelling "two-factor", which I find more accurate.

INWX: Updated docs for limit up to 2,147,483,647 domains

---

integrationTest/integration_test.go

It looks like the test was accidentally skipped via https://github.com/StackExchange/dnscontrol/pull/2535 / 6c7a920369b29320b5ae8181e7471b46e3f02696.
The integration tests pass with the HETZNER provider on this PRs revision and also when rebased onto #2575 :tada:

TESTING: un-skip TestDualProviders

---

pkg/normalize/validate.go

Problem:
IMPORT_TRANSFORM fails when a CF_TEMP_REDIRECT() record is used in the domain.
Solution:
IMPORT_TRANSFORM should only care about A and CNAME records. Silently ignore all others.

IMPORT_TRANSFORM: Be more forgiving about non-standard rtypes

---

documentation/typescript.md

Made several improvements around the TypeScript page.
**Before**
_[Live URL](https://docs.dnscontrol.org/getting-started/typescript)_
**After**
_[Preview URL](https://docs.dnscontrol.org/~/revisions/Hr8DnpmEgTCrDfYdXnQM/getting-started/typescript)_

DOCS: TypeScript improvements

---

commands/getCerts.go

By testing shell completion https://github.com/StackExchange/dnscontrol/pull/2449 I found that the command `create-domains` contains a `DEPRECATED:` prefix and `get-certs` does not.
https://github.com/StackExchange/dnscontrol/blob/5ae231030eaf32a99b80cc91abae4577d9ee4ccc/commands/createDomains.go#L15
```shell
dnscontrol
```
```diff
NAME:
dnscontrol - dnscontrol is a compiler and DSL for managing dns zones
USAGE:
dnscontrol [global options] command [command options] [arguments...]
COMMANDS:
help, h  Shows a list of commands or help for one command
main:
preview  read live configuration and identify changes to be made, without applying them
push     identify changes to be made, and perform them
debug:
check     Check and validate dnsconfig.js. Output to stdout.  Do not access providers. …
```

DOCS: Deprecated get-certs command

---

pkg/printer/printer.go

Per https://askubuntu.com/questions/322600/do-you-want-to-continuey-n-why-the-upper-case , the convention is that the uppercase character is the default.
PromptToRun() defaults to false, so let's prompt with "y/N".

Change "push -i" prompt text from "Y/n" to "y/N" to match reality

---

documentation/SUMMARY.md
providers/dnsmadeeasy/restApi.go

Fixed incorrect provider name `DNS Made Simple` instead of `DNS Made Easy` in the documentation and some code.

DNSMADEEASY: DOCS: Fix provider name from DNS Made Simple to DNS Made Easy

---

documentation/providers/inwx.md
providers/inwx/inwxProvider.go

Fixes: #2604
This makes [Nameserver.List](https://www.inwx.de/de/help/apidoc/f/ch02s15.html#nameserver.list) requests in batches of 20 until the length of zones equals that reported by the INWX api.
Please review - its been a time since i've done golang :)

INWX: Paginate through Nameserver Records

---

providers/porkbun/api.go
providers/porkbun/listzones.go

Small improvement for the Porkbun provider. Enables `all` argument for the `get-zones` subcommand, as well as `check-creds` subcommand.
Side note: My first PR for the project, did not find a "how to contribute" entry on the otherwise really good documentation (I guess I could have asked on the mailing list first 🙂), so I really appreciate the PR template mentioning a few steps (especially as someone who only has occasional contact with `go`).

PORKBUN: implement ListZones()

---

models/t_txt.go
providers/axfrddns/axfrddnsProvider.go
providers/azuredns/azureDnsProvider.go
providers/cscglobal/dns.go
providers/digitalocean/auditrecords.go
providers/domainnameshop/dns.go
providers/gcore/convert.go
providers/hetzner/types.go
providers/hexonet/records.go
providers/hostingde/types.go
providers/inwx/inwxProvider.go
providers/loopia/auditrecords.go
providers/msdns/powershell.go
providers/namedotcom/auditrecords.go
providers/namedotcom/records.go
providers/ns1/ns1Provider.go
providers/softlayer/softlayerProvider.go
providers/vultr/vultrProvider.go

In preparation for removing .TxtStrings, refactor all the providers to use .GetTargetTXTJoined() or .GetTargetTXTSegmented().

REFACTOR: providers should not directly access .TxtStrings

---

providers/ns1/auditrecords.go
providers/ns1/ns1Provider.go

* update auditrecords for succeeding tests
* multiple segments not needed anymore. This was there to cover an edge case of a user setting segments in the dnsconfig file
* strings can be longer than 255 octets, but not 0.
* update ns1 txt handling. No need for segmenting anymore, ns1 api handles this transparently.

NS1: update ns1 for new txt handling

---

documentation/providers/cloudflareapi.md

Previously it was stated that DNSControl would not create a new domain in Cloudflare unless `dnscontrol create-domains` was executed. That subcommand has now been deprecated and is part of `dnscontrol push`
**Note:** `go vet, go fmt, etc.` were not ran since this is only modifying the documentation and not the code itself.

CLOUDFLARE: Update docs WRT domain creation

---

.github/workflows/pr_test.yml

CICD: Use GHA concurrency groups to prevent tests from clobbering each other

---

commands/types/dnscontrol.d.ts
documentation/functions/record/R53_EVALUATE_TARGET_HEALTH.md

TypeScript uses `boolean` keyword, not `bool` like Go

ROUTE53: fix parameter type for R53_EVALUATE_TARGET_HEALTH

---

documentation/SUMMARY.md

This new record modifier wasn't showing up in the documentation. Is there anywhere else that needs to be updated to get this working?

ROUTE53: add R53_EVALUATE_TARGET_HEALTH to documentation summary

---

documentation/providers.md

Fixed providers with "contributor support" table.
**Before**
_https://docs.dnscontrol.org/service-providers/providers#providers-with-contributor-support_
**After**
_https://docs.dnscontrol.org/~/revisions/xp6ldzoScuGcfC9GQfye/service-providers/providers#providers-with-contributor-support_
The origin https://github.com/StackExchange/dnscontrol/pull/2626/commits/4e223aafa0fa19d2100d69d269d791558fc532fe#diff-f49f8c191a562999338f9b4e93db36244e5315e8eb6daced32c61f8eb635cfb9R80

DOCS: Fixed providers with "contributor support" table.

---

.goreleaser.yml

Added the new `Azure Private DNS` provider to the GoReleaser provider-specific changelog regexp conform https://docs.dnscontrol.org/developer-info/writing-providers#step-14-modify-the-release-regexp.

AZURE_PRIVATE_DNS: GoReleaser provider-specific changelog regexp

---

documentation/providers.md

Fixed the broken provider `ClouDNS` link in the providers table.
**Before**
_https://docs.dnscontrol.org/service-providers/providers#providers-with-contributor-support_
**After**
_https://docs.dnscontrol.org/~/revisions/IYp46WX59nYUeyg6NErx/service-providers/providers#providers-with-contributor-support_

DOCS: Fixed the broken provider `ClouDNS` link in the providers table

---

documentation/SUMMARY.md
documentation/functions/domain/R53_ALIAS.md

@jonathanbouvier [commented](https://github.com/StackExchange/dnscontrol/pull/2659#issuecomment-1833834072)
> The link to R53_EVALUATE_TARGET_HEALTH on [R53_ALIAS](https://docs.dnscontrol.org/language-reference/domain-modifiers/service-provider-specific/amazon-route-53/r53_alias) is pointing to https://github.com/StackExchange/dnscontrol/blob/master/documentation/functions/record/R53_EVALUATE_TARGET_HEALTH.md instead of https://docs.dnscontrol.org/language-reference/record-modifiers/service-provider-specific/amazon-route-53/r53_evaluate_target_health
> 
> Any ideas what might be going wrong there?
I fixed the `R53_` broken links by adding a backslash in the file names. See the preview URL:
_https://docs.dnscontrol.org/~/revisions/SMhInsWkrPeuva4GWfmr/language-reference/domain-modifiers/ser …

DOCS: Fix `R53_` broken links

---

documentation/SUMMARY.md
documentation/providers/opensrs.md

Added the missing provider OpenSRS page so that there is no 404 error and/or GitHub redirect occurs.
_https://docs.dnscontrol.org/~/revisions/zj4vNIIhrMcRjkGVoL3J/service-providers/providers/opensrs_
cc: @philhug would you, as maintainer of this provider, like to further supplement this page with the missing provider details? This includes the provider variables, the method of authorization and/or obtaining an API token. Thanks! 🙏

DOCS: Added the missing provider `OpenSRS` page

---

README.md
documentation/byo-secrets.md
documentation/release-engineering.md

Fixed the broken GitHub workflow status badge and the documentation after rename build filenames https://github.com/StackExchange/dnscontrol/pull/2593.

DOCS: Rename build filenames

---

providers/cloudflare/cloudflareProvider.go

Reset the `domainIndex` after the domain has been created at Cloudflare so that the following functions can fetch a new list of nameservers.
This fixes https://github.com/StackExchange/dnscontrol/issues/2652

CLOUDFLARE: Fixed bug: Zone not populated with records if domain was created in the same run

---

providers/_all/all.go

Discovered that by default on the master branch (and the current releases) that the AZURE_PRIVATE_DNS module wasn't getting built by default.  Adding it back to all.go so that it gets included by default.

AZURE_PRIVATE_DNS: Enable building this provider by default

---

documentation/providers.md

Fixed the broken absolute link on de [Provider](https://docs.dnscontrol.org/service-providers/providers#q-why-are-the-above-github-issues-marked-closed) > [Requested providers](https://docs.dnscontrol.org/service-providers/providers#requested-providers) section. This improvement passed the [previous review](https://github.com/StackExchange/dnscontrol/pull/2269/files#diff-f49f8c191a562999338f9b4e93db36244e5315e8eb6daced32c61f8eb635cfb9R181).
**Before**
_<https://docs.dnscontrol.org/service-providers/providers#q-why-are-the-above-github-issues-marked-closed>_
**After**
_<https://docs.dnscontrol.org/~/revisions/ZMt4acDFLrTK0XhR2xjQ/service-providers/providers#q-why-are-the-above-github-issues-marked-closed>_

DOCS: Providers: Fixed the broken absolute link

---

documentation/writing-providers.md

Removed the (by GitBook) broken GitHub links.
**Before**
_<https://docs.dnscontrol.org/developer-info/writing-providers#step-9-update-docs>_
**After**
_<https://docs.dnscontrol.org/~/revisions/pL1ZCo9rR6Pc7fd9s81a/developer-info/writing-providers#step-9-update-docs>_

DOCS: Removed the (by GitBook) broken GitHub links

---

pkg/rejectif/txt.go
providers/cscglobal/auditrecords.go
providers/digitalocean/auditrecords.go
providers/loopia/auditrecords.go
providers/msdns/auditrecords.go

Fix TXT length checking.
* CSCGLOBAL: Remove artificial 255-octet length limit on TXT records.
* DIGITALOCEAN: Remove artificial restriction on double-quotes in TXT records

CHORE: Clarify TXT string limits

---

commands/previewPush.go

If EnsureZoneExists fails for any of the configured providers, keep emitting a warning, but also register an error so that any CI/CD-driven workflow gets to know about this via the relevant message and exit code.
Fixes #2627

BUG: Register an error if EnzureZoneExists fails

---

go.mod
go.sum

The clean-up of the Go package `google/go-github` before used by Travis validate command. Addition to the previous GitHub pull request https://github.com/StackExchange/dnscontrol/pull/2707

CICD: Clean-up of Travis Go package dependency

---

commands/types/dnscontrol.d.ts

After the refactor from https://github.com/StackExchange/dnscontrol/pull/2704 the file `dnscontrol.d.ts` for the `go install` command is missing. Which is (_also_) needed for the GitHub unit tests, see [actions/runs/7158752208/job/19491197407](https://github.com/StackExchange/dnscontrol/actions/runs/7158752208/job/19491197407). This has been temporarily resolved by reintroducing the `dnscontrol.d.ts` file.
```shell
git checkout 9014c6879c46e6e96de4282f344694fbdeb65ca7 -- commands/types/dnscontrol.d.ts
```
**Why temporary?**
Because now still a local git diff will be created after running `go generate ./...` command. Which is mentioned in the documentation and/or GitHub pull request template. For now my focus was to get a working GitHub CI so that successful builds can be made.
I will have …

CICD: Fixed `go install` command

---

.github/workflows/pr_test.yml
integrationTest/integration_test.go

This should fix the build problem.
CC @cafferata

CICD: Add stringer

---

commands/types/dnscontrol.d.ts
documentation/SUMMARY.md
documentation/functions/domain/DHCID.md
integrationTest/integration_test.go
models/domain.go

DOCS: add dhcid RR docs

---

commands/types/dnscontrol.d.ts

The typescript definition file uses the _string_ type for **issuewild** in **CAA_BUILDER**, but it should be _string[]_ as noted in the [documentation](https://docs.dnscontrol.org/language-reference/domain-modifiers/caa_builder)

DOCS: Fix CAA_BUILDER  parameter types (issuewild type should be string[])

---

.github/workflows/release_draft.yml

CICD: release needs stringer

---

providers/transip/auditrecords.go

Avoid the TransIP failure https://github.com/StackExchange/dnscontrol/issues/2272#issuecomment-1856454095 by adding an audit record of a maximum of 1024 TXT record characters.

TRANSIP: Added audit record for a maximum of 1024 TXT-record characters

---

pkg/printer/printer.go

OLD:
```
$ dnscontrol preview --full --providers gandi_v5_tal --domains everythingsysadmin.com
******************** Domain: everythingsysadmin.com
----- Getting nameservers from: cloudflare_tal
----- DNS Provider: cloudflare_tal... (skipping)
----- Registrar: gandi_v5_tal...
0 corrections (gandi_v5_tal)
%
```
NEW:
```
$ dnscontrol preview --full --providers gandi_v5_tal --domains everythingsysadmin.com
******************** Domain: everythingsysadmin.com
----- Getting nameservers from: cloudflare_tal
----- DNS Provider: cloudflare_tal... (skipping)
----- Registrar: gandi_v5_tal...
0 corrections (gandi_v5_tal)
$
```

BUG: --full outputs an extra newline when skipping providers

---

.github/workflows/pr_test.yml

CICD: Revert actions/upload-artifact to 3.1.3 (from 4.0.0)

---

integrationTest/integration_test.go

OLD:
TestDNSProviders cleans out the DNS zone at the start and end of teach testgroup{}.
NEW:
TestDNSProviders cleans out the DNS zone at the start of each testgroup{}.  Thus, leaving the test records in place at the end.

CICD: clean slate at the start, not end, of each testgroup

---

go.mod
go.sum

CHORE: Bump golang.org/x/crypto from 0.16.0 to 0.17.0

---

providers/gcloud/gcloudProvider.go

fixes #2758
* GCLOUD: display all correction messages affecting same label + type in a zone

GCLOUD: display all correction messages affecting same label + type in a zone

---

.github/workflows/pr_test.yml

Trigger the GitHub Actions pull request workflow by branch name `tlim_testpr`. This fixes #2699 and saves you having to create empty (closed) pull requests.
See also:
1. The [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore) documentation.
2. The GitHub Actions workflow running action [#7414124200](https://github.com/cafferata/dnscontrol/actions/runs/7414124200) by the branch `tlim_testpr` on my GitHub fork repository.
The GitHub Actions `PR: Run all tests` workflow can be found here:
1. [StackExchange/dnscontrol/actions/workflows/pr_test.yml?query=branch:tlim_testpr](https://github.com/StackExchange/dnscontrol/actions/workflows/pr_test.yml?query=branch%3Atlim_testpr).
* …

CICD: Add GHA trigger for PR workflow of master branch

---

documentation/providers/dynadot.md

I based the Dynadot provider documentation on the Easyname docs and missed one occurrence of easyname.
Sorry about that!

DYNADOT: correct example in docs

---

providers/transip/auditrecords.go

Verified the audit records against the TransIP API.
```javascript
D(
'dnscontrol.nl',
NewRegistrar('none'),
DnsProvider(NewDnsProvider('transip', '-')),
// ALIAS: Failure
// ALIAS('LabelNotApex', 'LabelNotApex.com.')
// TXT: Failure
// TXT('TxtHasBackticks', '`')
// TXT('TxtHasBackslash', "\\")
// TXT('TxtHasTrailingSpace', ' ')
// TXT('TxtStartsOrEndsWithSpaces', ' test')
// TXT('TxtIsEmpty', '')
// TXT: Success
// TXT('TxtHasDoubleQuotes', '"test"')
// TXT('TxtHasSemicolon', ';'),
// TXT('TxtHasSingleQuotes', "'")
// TXT('TxtHasUnpairedDoubleQuotes', '" test')
// CAA: Success
// CAA('CaaTargetContainsWhitespace', 'iodef', ' mailto:info@jcid.nl ')
// CAA('CaaTargetHasSemicolon', 'issue', 'letsencrypt.org; policy=ev')
);
```
<details>
<summary>For completeness/archive purpose my testing …

TRANSIP: Audit records verified

---

providers/gcore/gcoreProvider.go

GCore DNS supports ALIAS record at apex zone level by automatic CNAME flattening: https://gcore.com/docs/dns/dns-records/specify-cname-at-root
Enable ALIAS records for GCORE provider, and transform ALIAS records into CNAME just like CLOUDFLARE provider.

GCORE: enable ALIAS records

---

integrationTest/integration_test.go

We found a bug with one provider when converting from multiple MX records to a single Null MX.  Adding integration tests to detect this situation and prevent regressions.

CICD: Add nullMX tests

---

.gitbook.yaml

Removed the GitBook configuration file. Followed up at https://github.com/StackExchange/dnscontrol/pull/2052. This folder structure is guaranteed within GitBook interface.

DOCS: [GitBook] Remove configuration file

---

.goreleaser.yml

GoReleaser has a [jsonschema](http://json-schema.org/draft/2020-12/json-schema-validation.html) file, which can be used to have better editor support.
_https://goreleaser.com/static/schema.json_

CICD: GoReleaser JSON Schema

---

documentation/release-engineering.md

* Correct the `git push` statement used in producing releases.

CICD: Bugfix: Changes introduced while tagging new releases cause git problems

---

.github/workflows/pr_check_git_status.yml

Check the `git status` with the GitHub Action [check-git-status](https://github.com/marketplace/actions/check-git-status) and if a `git diff` occurs, ~~post a comment with the same message as `.github/pull_request_template.md`~~ the pipeline will not be green/successful.
Refs: https://github.com/StackExchange/dnscontrol/pull/2704#issuecomment-1849002234 https://github.com/StackExchange/dnscontrol/pull/2712 https://github.com/StackExchange/dnscontrol/pull/2803

CICD: GitHub Action check git status

---

documentation/writing-providers.md

Fixed `Step 9` being duplicated in the step number in the `writing-providers` heading.

Docs: Fixed step number in `writing-providers`

---

integrationTest/integration_test.go
providers/desec/desecProvider.go

Fixes https://github.com/StackExchange/dnscontrol/issues/2822
* Add integration test to demonstrate the issue
* Don't create an upsert if there is nothing changing

deSEC: API rejects empty updates caused by IGNORE() of all records

---

documentation/providers/desec.md
integrationTest/integration_test.go

* Update deSEC to include the 300 updates per day per domain limit
* Remove deSEC from certain tests that would exceed limits

DOCS: Document daily update limits

---

.github/workflows/pr_test.yml

Provide the correct GitHub action contexts by using the dollar sign and curly braces, as `${{ env.TEST_RESULTS }}`.
**GitHub docs**
* _https://docs.github.com/en/actions/learn-github-actions/contexts#vars-context_
* _https://docs.github.com/en/actions/learn-github-actions/variables#using-contexts-to-access-variable-values_
Fixes https://github.com/StackExchange/dnscontrol/issues/2841

CICD: Provide the correct GitHub action contexts

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

I've add two [contact links](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) when creating an GitHub issue:
1. [Documentation](https://docs.dnscontrol.org/)
2. [Mailing list](https://groups.google.com/g/dnscontrol-discuss)
_Text is based on the [Get Involved](https://docs.dnscontrol.org/#get-involved) paragraph._
An live example can be found at: https://github.com/cafferata/dnscontrol/issues/new/choose

GitHub: Added contact links

---

.goreleaser.yml
README.md

Fixes https://github.com/StackExchange/dnscontrol/issues/2819.
Example release took place on the GitHub fork:
https://github.com/cafferata/dnscontrol/releases/tag/v4.8.0

CICD: GoReleaser release footer

---

providers/axfrddns/axfrddnsProvider.go

AXFRDDNS provider will append a `.` to TSIG key ID no matter if there's already an existing one.
If the key ID provided by user already has a dot suffix, a general `bad rdata` error will be shown without few meaningful clue for troubleshooting.

AXFRDDNS: Avoid appending dot if TSIG key ID already has a dot suffix

---

go.mod
go.sum
pkg/normalize/validate.go
pkg/normalize/validate_test.go
providers/akamaiedgedns/akamaiEdgeDnsService.go
providers/azuredns/azureDnsProvider.go
providers/azureprivatedns/azurePrivateDnsProvider.go
providers/cscglobal/dns.go
providers/desec/convert.go
providers/desec/desecProvider.go
providers/digitalocean/digitaloceanProvider.go
providers/dnsmadeeasy/types.go
providers/doh/api.go
providers/doh/dohProvider.go
providers/hexonet/records.go
providers/hostingde/hostingdeProvider.go
providers/oracle/oracleProvider.go
providers/packetframe/packetframeProvider.go
providers/rwth/api.go
providers/rwth/dns.go
providers/vultr/convert_test.go
providers/vultr/vultrProvider.go

Fixed many linting errors all related to "unused parameters".  There are still some left to fix.
CC'ing various code owners for visibility:
* pkg/normalize @tlimoncelli
* providers/akamaiedgedns @svernick
* providers/azuredns @vatsalyagoel
* providers/azureprivatedns @matthewmgamble
* providers/cscglobal @mikenz
* providers/desec @D3luxee
* providers/digitalocean @Deraen
* providers/dnsmadeeasy @vojtad
* providers/doh @mikenz
* providers/hexonet @KaiSchwarz-cnic
* providers/hostingde @juliusrickert
* providers/oracle @kallsyms
* providers/packetframe @hamptonmoore
* providers/rwth @mistererwin
* providers/vultr @pgaskin

CHORE: Resolved unused parameter warnings

---

commands/types/dnscontrol.d.ts
documentation/functions/domain/PTR.md
documentation/functions/global/REV.md
documentation/functions/global/REVCOMPAT.md
documentation/opinions.md

Documentation (style) fixes for the (open) GitHub pull request https://github.com/StackExchange/dnscontrol/pull/2879.

DOCS: `REV()` and `REVCOMPAT()`

---

.goreleaser.yml
README.md
commands/getCerts.go
documentation/get-certs.md

* Make the "get-certs" subcommand hidden.
* Warn that the code may be removed without notice.
* Unify the warning to list July 2025 as the max deadline.

DOCS: Warn that get-certs will be removed without notice

---

documentation/colors.md

dnscontrol uses fatih/color package which respects the NO_COLOR standard
https://github.com/fatih/color?tab=readme-ov-file#disableenable-color
https://no-color.org
This change touches only docs, no code, so no code testing was performed.

DOCS: Disabling colors via environment variable

---

commands/types/dnscontrol.d.ts
documentation/language-reference/domain-modifiers/LOC.md
documentation/language-reference/domain-modifiers/LOC_BUILDER_DD.md
documentation/language-reference/domain-modifiers/LOC_BUILDER_DMM_STR.md
documentation/language-reference/domain-modifiers/LOC_BUILDER_DMS_STR.md
documentation/language-reference/domain-modifiers/LOC_BUILDER_STR.md

Hey @tlimoncelli , while looking at my copy of the dnscontrol repo tonight, I noticed that my linter GHA had caught a typo.  This PR fixes it.

Fix typo: "cooordinate"

---

documentation/providers.md
providers/powerdns/powerdnsProvider.go

Simply enables DHCID records for PowerDNS, tested on 4.9.0 - works fine.

POWERDNS: Enables DHCID

---

integrationTest/integration_test.go

Fixes broken DHCID test for PowerDNS

POWERDNS: Change DHCID test value to valid base64 code

---

integrationTest/integration_test.go

Sorry @tlimoncelli - shouldn't have relied on just it being valid base64, there's a max length too.

POWERDNS: Value in test was too long

---

go.mod
go.sum

NS1: update ns1-go to 2.10.0

---

documentation/providers.md
providers/ns1/ns1Provider.go

This changeset enables correct handling of SVCB, HTTPS and TLSA records on NS1
Fixes: #2943

NS1: Add SVCB, HTTPS, TLSA support

---

documentation/providers.md
providers/bunnydns/bunnydnsProvider.go
providers/bunnydns/records.go

Bunny DNS supports CNAME flattening (dynamic resolution into A/AAAA).
Allow configuration via `ALIAS` record type.
`preview` output before;
```
ERROR: in CNAME @.example.com: cannot create CNAME record for bare domain
```
`preview` output after;
```
******************** Domain: example.com
```

BUNNY_DNS: Add support for `ALIAS`

---

documentation/providers.md
providers/ns1/ns1Provider.go

This changeset enables support for DNAME and DHCID record types in NS1.

NS1: add support for DNAME and DHCID record types

---

commands/completion-scripts/completion.zsh.gotmpl

Fixes: #2955
The #compdef directive shouldn't have double-quotes. (https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Autoloaded-files)
We need to execute the function the first time when its loaded as described by https://zsh.sourceforge.io/Doc/Release/Functions.html#Autoloading-Functions
> [If the KSH_AUTOLOAD option is not set] the function body
(with no surrounding `funcname() {...}``) is taken to be the complete contents of the file.
This form allows the file to be used directly as an executable shell script.
>
> If processing of the file results in the function being re-defined, the function itself is not re-executed. To force the shell to perform initialization and then call the function defined, the file should contain initialization code (which will be executed then …

BUG: ZSH Autocomplete does not work if installed as a file #2955

---

OWNERS
documentation/providers.md

The new AKAMAIEDGEDNS maintainer is Ed Lynes (edglynes).

AKAMAIEDGEDNS: new maintainer: Ed Lynes

---

docs/index.md

Fixed the 404 URL's for the `SPF_BUILDER()` and `CAA_BUILDER()`.

DOCS: Fixed 404 URL's on GitHub page

---

documentation/get-zones.md

Removed the old reference to `convertzone` within the '[get-zones](https://docs.dnscontrol.org/commands/get-zones)' page.

DOCS: [get-zones] Removed old reference to `convertzone`

---

go.mod
go.sum
providers/hexonet/error.go
providers/hexonet/hexonetProvider.go

Version **4.0.0** of the `rtldev-middleware-go-sdk` includes bug fixes, performance improvements, and significant restructuring. Notable changes include:
- **Bug Fixes:**
- Replaced the IDN translator.
- Improved library structure to avoid import cycles and address linter issues.
- Merged the response class with the response template and added a response translator.
- Reviewed and patched failing tests related to the response template manager.
- **Performance Improvements:**
- Deprecated the API IDN conversion.
- Integrated the GOLang IDN library with tests.
- **BREAKING CHANGES:**
- The response class has undergone significant restructuring to bring the library to the next Golang level and ensure future safety.

HEXONET: Adopt version 4.0.0 of the rtldev-middleware-go-sdk

---

providers/gcloud/gcloudProvider.go

Fixes https://github.com/StackExchange/dnscontrol/issues/2981
A makezero linter found this typo.

GCLOUD: Fix missing length in make()

---

commands/types/dnscontrol.d.ts
documentation/language-reference/domain-modifiers/CAA_BUILDER.md
pkg/js/helpers.js

The domain modifier [`CAA_BUILDER()`](https://docs.dnscontrol.org/~/revisions/zxXPLS8rJfg9iKM0hYbP/language-reference/domain-modifiers/caa_builder) with record modifier [`TTL()`](https://docs.dnscontrol.org/language-reference/record-modifiers/ttl) support.
**`dnsconfig.js` before/after**
```javascript
DEFAULTS(
DefaultTTL('1d')
)
```
```diff
D('jcid.nl',
PROVIDER_NONE,
DnsProvider(PROVIDER_TRANSIP),
CAA_BUILDER({
label: '@',
iodef: 'mailto:info@jcid.nl',
iodef_critical: true,
issue: [
'letsencrypt.org',
'sectigo.com',
],
issue_critical: true,
issuewild: 'none',
issuewild_critical: true,
+       ttl: TTL('1h'),
}),
```
```shell
dnscontrol preview --domains jcid.nl --dev
```
```shell
******************** Domain: jcid.nl
8 corrections (transip)
#1: [1/2] delete: ± MODIFY-TTL jcid.nl CAA 128 …
```

FEATURE: `CAA_BUILDER()` with `TTL()` support

---

providers/axfrddns/axfrddnsProvider.go

Hi,
In the AXFRDDNS provider, it appears we can use a key like: `hmac-sha256:MyTsIgKey:Base64EncodedSecret=`
But the key name (here `MyTsIgKey`) is not canonicalized, however it is required by the [RFC 2845](https://datatracker.ietf.org/doc/html/rfc2845#page-7).
This PR calls `CanonicalName`, which also adds a leading `.` if it is missing.

AXFRDDNS: Canonicalize key name as per RFC 2845 3.4.2

---

commands/types/dnscontrol.d.ts
documentation/language-reference/domain-modifiers/AUTODNSSEC_OFF.md
documentation/language-reference/domain-modifiers/AUTODNSSEC_ON.md

Minor improvements in the `AUTODNSSEC_*` documentation:
**Before**
1. https://docs.dnscontrol.org/language-reference/domain-modifiers/autodnssec_on
2. https://docs.dnscontrol.org/language-reference/domain-modifiers/autodnssec_off
**After**
1. https://docs.dnscontrol.org/~/revisions/FfooJaEujEGdD2tmvj2H/language-reference/domain-modifiers/autodnssec_on
2. https://docs.dnscontrol.org/~/revisions/FfooJaEujEGdD2tmvj2H/language-reference/domain-modifiers/autodnssec_off

DOCS: AUTODNSSEC_* improvements

---

commands/types/dnscontrol.d.ts
documentation/language-reference/domain-modifiers/CAA_BUILDER.md
documentation/language-reference/domain-modifiers/DMARC_BUILDER.md
documentation/language-reference/domain-modifiers/IGNORE.md
documentation/language-reference/domain-modifiers/M365_BUILDER.md
documentation/language-reference/domain-modifiers/SSHFP.md

Provide the domain modifiers code examples with a Top Level Function `D()`.
| Before                                                                                         | After                                                                                                                           |
|------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------|
| [CAA_BUILDER](https://docs.dnscontrol.org/language-reference/domain-modifiers/caa_builder)     | [CAA_BUILDER](https://docs.dnscontrol.org/~/revisions/Wsmplm3icm87Wulgh0Ed/language-reference/domain-modifiers/caa_builder)     |
| …

DOCS: Provide domain modifiers code examples with a Top Level Function D()

---

.github/workflows/pr_test.yml
.github/workflows/release_draft.yml
.goreleaser.yml

[GoReleaser v2.0.0](https://github.com/goreleaser/goreleaser/releases/tag/v2.0.0) and [GoReleaser GitHub actions v.6.0.0](https://github.com/goreleaser/goreleaser-action/releases/tag/v6.0.0) are released 🥳 
<details>
<summary>Upgrading GoReleaser v2.0.0</summary>
> If you keep up with the deprecation notices, it's likely you don't need to do anything.
>
> If you don't, that's fine too! Let's figure it out together! You can start by running the following commands:
>
> ```shell
> goreleaser check # using the latest v1
> rm -rf ./dist/
> grep -iR '\--rm-dist' .
> grep -iR '\--skip-' .
> grep -iR '\--debug' .
> ```
>
> **Extra tip**: You can also look into your last release logs if they are still there, and fix the deprecation warnings based on it.
>
> Fix any occurrences following …

BUILD: GoReleaser v2.0.0

---

models/record.go
providers/gcloud/gcloudProvider.go

Fixes the issue with updating/deleting TXT (maybe others too) record types from GCLOUD.
```
#1: + CREATE domain.com TXT "some_value" ttl=3600
FAILURE! runChange error: googleapi: Error 412: Precondition not met for 'entity.change.deletions[domain.com.][TXT]', conditionNotMet
```
Under the hood DNS had TXT resources that was not sorted and `diff2.ByRecordSet` returns changes that have sorted values so we tried to send request with proper values but sorted differently, and seems like google is picky about ordering.
Maybe it was possible to pass `compFunc` but I didnt get how to do that..
Taking the original records was way easier, and should always return proper order.
Easiest reproduction case.
Add any TXT record with entries not sorted alphabetically (manually), and do any change/delete …

GCLOUD: Fix issue on creating/deleting/updating TXT records

---

documentation/getting-started.md

Added a summary of the possible installation within the getting started installation.
See [getting-started/getting-started#id-1.-install-the-software](https://docs.dnscontrol.org/~/revisions/4HyJq7gA37dkWWpZV6au/getting-started/getting-started#id-1.-install-the-software)

DOCS: Getting started installation options summary

---

.goreleaser.yml
documentation/getting-started.md

Removed the MacPorts references from [Getting started > Overview](https://docs.dnscontrol.org/~/revisions/vsyVZNAyLKpMu56eHflN/getting-started/getting-started).
Fixes https://github.com/StackExchange/dnscontrol/issues/3021.

DOCS: MacPorts removed

---

providers/cloudflare/singleredirect.go

CLOUDFLARE: Fix bug where a $2 redirect did not match any exiting single redirect rules
CLOUDFLARE: Correct error message typo

CLOUDFLARE: Bugfix for Redirect, correct typo in error message.

---

providers/cloudflare/singleredirect.go

CLOUDFLARE: Fix another redirect bug

---

documentation/provider/cloudflareapi.md

This PR fixes 2 links in the Cloudflare API provider documentation. These were incorrectly formatted previously, and would not be rendered as links on the website.
- https://docs.dnscontrol.org/provider/cloudflareapi#old-style-vs-new-style-redirects

DOCS: Fix markdown links in Cloudflare provider docs

---

documentation/provider/gandi_v5.md
integrationTest/providers.json
providers/gandiv5/gandi_v5Provider.go

This PR handles the new default auth mechanism for GANDI_V5 API (`token`) now that the [`apikey` is officialy deprecated](https://news.gandi.net/en/2023/09/pat-jetons-acces-personnels-api-gandi/).  
The change should be transparent for existing users still using the `apikey` entry.  
Other changes to `creds.json` include:
* introducing `apiurl` setting to control then endpoint and allowing to use the sandbox endpoint
* introducing `dryrun` setting to allow DryRun use of certain API verbs (untested)
Please note that I had no success creating a domain in the sandbox environment, thus was not able to validate that everything was working as expected there. However, the API calls are (of course) properly sent to `apiurl` and the authentication works there.
(notifying maintainer: @TomOnTime …

GANDI: Adopt new Gandi v5 auth changes

---

providers/ns1/ns1Provider.go

NS1: add warning for deprecated record

---

documentation/provider/huaweicloud.md
documentation/providers.md
providers/huaweicloud/convert.go
providers/huaweicloud/huaweicloudProvider.go
providers/huaweicloud/records.go

This pr is intended to make 3 changes
- Huawei Cloud supports DNSSEC but doesn't provide a corresponding API, so I've labelled it as Unimplemented.
- Huawei Cloud has changed the link to the document, so I've updated it here.
- Fixed a potential de-duplication bug

HUAWEICLOUD: Document DNSSEC capability and improve docs, reliability

---

commands/types/dnscontrol.d.ts
documentation/SUMMARY.md
documentation/language-reference/top-level-functions/HASH.md
pkg/js/hash.go
pkg/js/js.go
pkg/js/js_test.go
pkg/js/parse_tests/051-HASH.js
pkg/js/parse_tests/051-HASH.json

Having access to SHA1 would be great when managing catalog zones:
```javascript
foo_name_suffix = HASH("sha1", "foo.name") + "zones"
D("catalog.example!int"
, REG_NONE
, DnsProvider(my_pdns_int)
, TXT("version", "2")
, PTR(foo_name_suffix, "foo.name.")
, A("primaries.ext." + foo_name_suffix, "192.168.1.1")
)
```
So this PR adds a `HASH` function to Javascript following the above example.

New Feature: HASH() adds hashing functions to dnsconfig.js language

---

.github/dependabot.yml

Remove NS1 from exception list.

DEV: Update dependabot.yml

---

documentation/provider/cloudflareapi.md

Below is a screenshot showing the new permission name:

DOCS: Update Cloudflare permission to "Single Redirect"

---

providers/cloudns/api.go

Don't print the full request URI on API error, as it contains the authentication parameters.

CLOUDNS: don't print full URL on error (#3124)

---

.goreleaser.yml

Fixes https://github.com/StackExchange/dnscontrol/issues/3129
```shell
goreleaser check
```
**Before**
```shell
• checking                                 path=.goreleaser.yml
• DEPRECATED:  snapshot.name_template  should not be used anymore, check https://goreleaser.com/deprecations#snapshotnametemplate for more info
• .goreleaser.yml                                  error=configuration is valid, but uses deprecated properties
⨯ command failed                                   error=1 out of 1 configuration file(s) have issues
```
**After**
```shell
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```

CICD: GoReleaser snapshot property deprecation

---

commands/ppreviewPush.go
commands/previewPush.go

This reverts commit 0f08087978462f52b1051dd961af5200380ad329.

Revert "FEATURE: parallel preview/push is now default (#3132)"

---

commands/ppreviewPush.go
commands/previewPush.go
documentation/json-reports.md
documentation/preview-push.md

Fixes https://github.com/StackExchange/dnscontrol/issues/3148
* --report can now be used on preview/ppreview, not just push/ppush
* The help message is changed to be more accurate. It is no longer a report of corrections that were performed, but a report of corrections.
* Docs updated

FEATURE: enable --report for preview (not just push)

---

providers/porkbun/api.go

As of December 1, 2024, Porkbun will require API hits to use `api.porkbun.com`, rather than `porkbun.com`.
Tested successfully and validated that information was obtained as expected.
https://porkbun.com/api/json/v3/documentation
> Please note that porkbun.com currently works and has historically been the correct hostname for our API. However, we will be migrating away from that hostname and the API will no function using it at some point in the future.
> 
> Deadline: 2024-12-01 00:00:00 UTC
>

PORKBUN: Update porkbun API endpoint per documentation / email

---

providers/ns1/ns1Provider.go

NS1 replaces URLFWD with REDIRECTs. The latter supports HTTPS, which is nice, but it is not a 'real' DNS Record from the configuration point of view. To create a redirect, there is a separate API Endpoint. Creating a redirect may also involve Certificate management, if a user wants HTTPS support.
However, NS1 returns names, for which there is a redirect configured in n.Zones.Get(), with a stub answers section 'NS1 MANAGED RECORD'. RRType of REDIRECT confuses dnscontrol, and entire sync fails.
This commit ignores REDIRECTs coming from NS1 API.

NS1: Ignore RRSets of type REDIRECT

---

pkg/js/helpers.js

Update M365_BUILDER to use a global match regex

M365_BUILDER: Support second level domains, fix domainGUID Generation

---

providers/oracle/oracleProvider.go

Fix for #3176
Will only warn about TTL reset to 86400 for domain own NS records, not for subdomains

ORACLE: Do not warn about TTL for sub domain NS records

---

pkg/normalize/validate.go
pkg/normalize/validate_test.go

BUG: IMPORT_TRANSFORM_STRIP not stripping CNAME targets

---

documentation/language-reference/domain-modifiers/IMPORT_TRANSFORM.md
documentation/language-reference/domain-modifiers/IMPORT_TRANSFORM_STRIP.md
pkg/normalize/validate.go

Problem:
* IMPORT_TRANSFORM/IMPORT_TRANSFORM_STRIP need to be able to skip certain records.
Solution:
* With this PR, if the metadata for a record includes "import_transform_skip" (any value), that record is skipped

feat(import_transform): skip records with import_transform_skip set

---

documentation/providers.md
providers/porkbun/auditrecords.go
providers/porkbun/porkbunProvider.go

close #3199
Testes passed
CAA with whitespace not supported.
```
=== RUN   TestDNSProviders/example.com/33:CAA:CAA_whitespace
integration_test.go:248:
± MODIFY example.com CAA (128 issuewild ";" ttl=600) -> (0 issue "letsencrypt.org; validationmethods=dns-01; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/1234" ttl=600), porkbun ID: 437665127
integration_test.go:269: Expected 0 corrections on second run, but found 1.
integration_test.go:271: UNEXPECTED #0: ± MODIFY example.com CAA (0 issue "letsencrypt.org;" ttl=600) -> (0 issue "letsencrypt.org; validationmethods=dns-01; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/1234" ttl=600), porkbun ID: 437665127
```

PORKBUN: support CAA

---

providers/digitalocean/digitaloceanProvider.go

As per #3202, I believe DigitalOcean works with concurrency

DIGITALOCEAN: Enable cmode concurrent

---

documentation/providers.md
providers/netlify/netlifyProvider.go

As per #3202, I believe Netlify works with concurrency

NETLIFY: Enable cmode concurrent

---

integrationTest/integration_test.go

Problem:
The pager101 integration test files for CNR.
Solution:
* I suspect our account has a limit in place.
* This test is safe to ignore for most providers as most don't send API results 1 page at a time.

CNR: Disable pager101 integration test

---

documentation/integration-tests.md

The CLOUDNS tests take longer than the default 10 minute timeout to run. This change adds a note to the testing instructions on how to increase or disable the timeout.

DOCS: Add instructions for increasing the timeout on integration tests

---

documentation/providers.md
providers/hetzner/api.go
providers/hetzner/hetznerProvider.go

Closes #3206 
This PR is making the Hetzner provider thread-safe and enabling the concurrency feature flag.
I've tweaked the rate-limiting to play better with concurrency by not overshooting the rate-limit reset point.
cc @tlimoncelli @willpower232

HETZNER: enable concurrency capability

---

documentation/providers.md
go.mod
providers/cloudns/api.go
providers/cloudns/cloudnsProvider.go

This enables concurrent access on CLOUDNS. Tested with my 24 zones.

CLOUDNS: enable concurrent access

---

documentation/notifications.md

The most recent release prompted me to have a look at the notifications documentation for the first time and apparently the Mattermost link is in need of an update.

DOCS: Update Mattermost docs link

---

commands/ppreviewPush.go

Issue:
while "preview --cmode=concurrent" triggers the concurrent code, "push --cmode=concurrent" does not.
Resolution:
Call the correct damn function.

BUGFIX: push not running concurrently

---

commands/ppreviewPush.go
documentation/providers.md
providers/bind/bindProvider.go

Fixes https://github.com/StackExchange/dnscontrol/issues/3252
* BIND: Enable cmode=concurrent
* BIND: Calculate the zone's filename any time it is needed rather than trying to store it for later use.
* bindProvider.zoneFileFound: Remove. This is written to but never read.
* bindProvider.zonefile: Remove. This is cached but always regenerated. Cache wasn't threadsafe.
* BIND: Implement ZoneCreator so that when BIND is your registrar (which it shouldn't be), at least you get reasonable messages.
* BIND: Improve messages around ensuring zones exist

BIND: Allow use in cmode=concurrent

---

documentation/release-engineering.md

Issue:
* The docs to update dependencies are later in the doc.
Resolution:
* Copy them to "step 0" for easier finding.

DOCS: Add dep updates steps to rel-eng

---

providers/gandiv5/gandi_v5Provider.go

Issue:
* GANDI_V5 has no rate limiting code.  This makes it fail occasionally in integration tests, which then must be run manually.  Sadly the output when it fails doesn't give much clue about error codes, etc. 
Resolution:
* Output http status code on failure so we can study this and add rate limiting.

GANDI_V5: Increase error verbosity

---

.github/workflows/pr_build.yml
.github/workflows/pr_integration_tests.yml
documentation/byo-secrets.md
documentation/integration-tests.md
integrationTest/integration_test.go

Here's some small fixes for things I noticed while doing https://github.com/StackExchange/dnscontrol/pull/3277 .
I raised these in a separate PR so they're easier to review.
Descriptions for each fix in the commit messages.

CICD: Update docs/comments after file renames

---

documentation/release-engineering.md

Release engineering docs should clarify that they
should start in "main".  Also add fmtjson instructions.
Added as requested.

DOCS: Add fmtjson and "get co main" to releng docs

---

integrationTest/integration_test.go

HEXONET: Skip unneeded test to speed up CICD

---

providers/hexonet/records.go

This PR addresses an issue where integer values parsed using strconv.ParseUint were not being checked to ensure they fit within the bounds of the target type (uint16). This could lead to incorrect conversions and potential runtime errors.
Changes:
- Added an upper bound check after parsing the priority value with strconv.ParseUint.
- Ensured that the parsed value does not exceed the maximum value of uint16 before performing the conversion.
- Handled errors appropriately if the value exceeds the maximum allowable value for uint16.

HEXONET: Add error handling for MX and SRV record priority parsing

---

providers/powerdns/dns.go
providers/powerdns/dnssec.go

At some point in the past the PowerDNS provider stopped combining the create zone and push records into a single run. One push would create the zone, and a second would be needed to then push the records. This PR finally fixes this to create and push records in one go.
master branch (current behavior):
```
$ dnscontrol preview
CONCURRENTLY gathering 0 zone(s)
SERIALLY gathering 1 zone(s)
Serially Gathering: "test.internal"
******************** Domain: test.internal
#1: Ensuring zone "test.internal" exists in "pdns"
INFO#1: Domain "test.internal" provider pdns Error: not found: http://127.0.0.1:8081/api/v1/servers/localhost/zones/test.internal.
INFO#1: Skipping registrar "none": No nameservers declared for domain "test.internal". Add {no_ns:'true'} to force
$ …
```

POWERDNS: fix preview/push of a non-existent zone

---

README.md
documentation/SUMMARY.md
documentation/provider/index.md
providers/cnr/cnrProvider.go
providers/cnr/records.go

The integration tests for DNSControl Alias records were completed successfully. 
Here's a detailed summary:
For the domain dnscontroltest2-cnr.com:
- Various ALIAS records were tested:
- An ALIAS record was created at the root.
- The ALIAS record at the root was modified.
- The ALIAS record at the root was deleted.
- An ALIAS record pointing to a non-FQDN was created and then deleted.
- An ALIAS record was created on a subdomain and then modified.
- The ALIAS record on the subdomain was deleted.
- Tests for Azure and Route53 ALIAS records were skipped because these features are not supported.
- All tests passed without any issues.

CNR: Add support for ALIAS record type

---

commands/ppreviewPush.go
models/domain.go

This PR is changing the order for creating zones to happen before any data is gathered for the zone (i.e. `driver.GetNameservers` / `driver.GetZoneRecords` calls).
Any corrections for creating zones will be displayed/executed in a separate loop before the main loop for gathering corrections kicks off. This zone-check loop is silent unless any provider has corrections.
Zones will get created on preview already to show a complete picture right away (opt-out via `--populate-on-preview=false`).
With these changes, a single `dnscontrol push` invocation is sufficient for bootstrapping a zone with HETZNER (and most other providers) :tada: 
<details>
<summary> Demo with HETZNER and two zones </summary>
```
$ dnscontrol preview
CONCURRENTLY gathering 2 zone(s)
SERIALLY gathering 0 zone(s)
Waiting …
```

FEATURE: Create zones during preview (Disable with --populate-on-preview=false)

---

integrationTest/integration_test.go
models/cloudflare_from.go
models/cloudflare_types.go
models/dns_test.go
models/rawrecords.go
models/record.go
models/t_mx.go
models/t_parse.go
models/t_srv.go
models/target.go
models/typeregister.go
models/types.go
pkg/acme/directoryStorage.go
pkg/acme/registration.go
pkg/fieldtypes/fieldtypes.go
pkg/js/parse_tests/007-importTransformTTL.json
pkg/normalize/importTransform_test.go
pkg/normalize/validate.go
pkg/normalize/validate_test.go
providers/msdns/powershell_test.go

- Use Generics to reduce code repetition
- Split out the parser for each RecordType so they can be used in multiple places
- Make CF_SINGLE_REDIRECT more like the other RecorTypes
- Create MustImportFromLegacy() for use in testing.
- More error checking
- Replace PopulateFields*() with RecordUpdateFields()
- RegisterType() -> MustRegisterType()
- Add MustCreateRecord() for unit tests
- Fix pkg/js/parse_tests/007-importTransformTTL.json (expected result was wrong!)
- Change SetTarget() to SetTargetA() where possible

Refactor: Use Go Generics for RecordConfig processing

---

pkg/zoneCache/zoneCache.go

This PR is kicking off a shared, thread-safe "zone cache" implementation for all the drivers to use instead of the various implementations out there today. The new zone cache uses Go-generics to let each driver choose their zone struct and retain type-safety. See https://github.com/StackExchange/dnscontrol/pull/3337 and the below commits for more details.
I've left out the provider changes. Let me know if you want to ship them here already:
- HETZNER driver c7789ccd886d317f98ba5a042d87a517a5f6f297 (chained onto tweaks in https://github.com/StackExchange/dnscontrol/pull/3336)
- CLOUDFLARE driver 85e796586f61690ffc39aa19eebad2b04b06662c (chained onto fixes in https://github.com/StackExchange/dnscontrol/pull/3330)

FEAT: Add ZoneCache primitive

---

providers/hetzner/api.go
providers/hetzner/hetznerProvider.go
providers/hetzner/types.go

This PR is adopting the new `ZoneCache` for the HETZNER driver.
(https://github.com/StackExchange/dnscontrol/pull/3336 plus the zone cache changes as linked in https://github.com/StackExchange/dnscontrol/pull/3337)

HETZNER: adopt ZoneCache

---

providers/cloudflare/cloudflareProvider.go
providers/cloudflare/rest.go

This PR is adopting the new `ZoneCache` for the CLOUDFLARE driver.
The integration tests are passing (CF_REDIRECT tests skipped). I've done some extra manual testing on the zone creation plus provisioning a zone in a single pass, see below.
(#3330 plus the zone cache changes as linked in https://github.com/StackExchange/dnscontrol/pull/3337)
<details>
<summary> Manual testing </summary>
```
var REG_NONE = NewRegistrar('none')
var DSP = NewDnsProvider('CLOUDFLAREAPI')
D('testing-2025-01-15-0.dev', REG_NONE, DnsProvider(DSP),
A('@', '127.0.0.1')
)
```
```
$ dnscontrol preview
******************** Domain: testing-2025-01-15-0.dev
1 correction (CLOUDFLAREAPI)
#1: Ensuring zone "testing-2025-01-15-0.dev" exists in "CLOUDFLAREAPI"
Added zone for testing-2025-01-15-0.dev to Cloudflare account: …
```

CLOUDFLARE: adopt ZoneCache

---

integrationTest/integration_test.go

CICD: Warn user if -provider does not match profiles.json:TYPE

---

providers/inwx/auditrecords.go

It has been reported that INWX now permits "." as a target in SRV records.
Remove rejectif.SrvHasNullTarget in auditrecords.go
CC @patschi
CC @rubgfx

INWX: Permit "." target for SRV records

---

documentation/provider/cloudflareapi.md
providers/cloudflare/cloudflareProvider.go

Cloudflare used to treat TTL=1 and TTL=300 as "magic".  300 is no longer magic.
Do not treat TTL=300 as special.

CLOUDFLAREAPI: No longer treat TTL=300 as special

---

providers/gcloud/gcloudProvider.go
providers/gcloud/retry.go

502 errors are retry-able after 30 seconds
Rate limit logic error: only kicks in when `if err != nil {` which I believe is reversed.
* retry 502 errors exactly once
* Check for the need to rate limit if `if err == nil {`

GCLOUD: Re-try on 502 errors

---

providers/transip/retry.go
providers/transip/transipProvider.go

Fixes https://github.com/StackExchange/dnscontrol/issues/3371
TRANSIP doesn't retry on rate limit (429) requests.
Add retry logic for all API calls.

TRANSIP: Pause when rate-limited

---

documentation/provider/cnr.md
providers/cnr/cnrProvider.go
providers/cnr/domains.go
providers/cnr/error.go
providers/cnr/nameservers.go
providers/cnr/records.go

Hey friends ;-)
* refactored the code to fix issues reported by golint
* dropped one API Request which was in place to identify a exact number of resource records available to fetch all of them in the next request. now the max limit is hardcoded with 10000 which should be fine for integration tests
* refactored EnsureZoneExists method to immediately request a dnszone creation and to deal with the result instead of prechecking and adding the zone. Again, one less api call. This should not have an impact on the run time of integration tests.
* reviewed debugmode handling and documentation
Integration Tests runtime on our end:
* originally: 325.560s
* this PR: 241.808s
Thanks!

CNR: Initial Performance improvement; golint review

---

pkg/zoneCache/zoneCache.go

:see_no_evil: Sorry, the zone cache failed to deliver it's core feature, caching of the zone listing. Oh well.
CLOUDFLARE integration tests run in 11min now, down from the 30min I mentioned in #3373.
HETZNER integration tests are down to 3min, from 8min.
I've repeated the manual testing for creating zones via preview/push as listed in #3373 for both CLOUDFLARE and HETZNER.
Closes https://github.com/StackExchange/dnscontrol/issues/3393

BUG: fetch zones once in ZoneCache

---

pkg/powershell/shell.go

5dbe5e84c914e5a6e437dba1e4116d63e6492d8f broke the PowerShell Execute() function
Fix the incorrect line.

MSDNS: Provider is failing due to lint fix gone wrong

---

commands/ppreviewPush.go

Here is a quick one-line fix for https://github.com/StackExchange/dnscontrol/issues/3399.

BUG: create zones on push regardless of --populate-on-preview=false

---

documentation/provider/index.md

The requested provider ‘Vercel DNS’ has been documented in the list of [requested providers](https://docs.dnscontrol.org/provider/index#requested-providers).
Fixes https://github.com/StackExchange/dnscontrol/issues/3379

DOCS: Provider request: Vercel DNS

---

providers/dnsmadeeasy/api.go
providers/dnsmadeeasy/dnsMadeEasyProvider.go
providers/dnsmadeeasy/restApi.go

Hi @vojtad!
While reviewing all the `ZoneCreator` implementations, I noticed that the DNSMADEEASY provider has an incomplete caching implementation for zones. The provider is populating the cache once on first access. Any zones that are created will not be readable in the same life-cycle of dnscontrol. This PR is populating the zone cache after creating a zone. Would you mind giving this a try and let me know how it goes? Thanks!
Note: I've reduced the contents of the zone cache to just the domain ID as that is what each called is using only; and what the API response from creating the zone provides too (the API response from creating the zone is similar to the response from listing, but not quite the same).
Bonus: I've also done some code cleanup from spurious nested pointers. These …

DNSMADEEASY: populate zone cache after creating zone

---

providers/cloudflare/cloudflareProvider.go

CLOUDFLAREAPI: Future-proof how ALIAS is handled

---

providers/ovh/protocol.go

Fixes #3427
Beforehand OVH refused to allow updating native DMARC records that weren't exactly `_dmarc`. This prevents updating `_dmarc` subdomains such as `_dmarc.something`. This change makes that test less strict and allows to now update DMARC records that are subdomains of the zone domain.

OVH: Bugfix: Native DMARC records rejected for subdomains

---

documentation/migrating.md

`migrating.md` is out of sync with `dnscontrol` functionality.
As per the BIND docs, `directory` and `filenameformat` are no longer hardcoded.  But as presently worded `migrating.md` implies that it is.

DOCS: Update migrating.md to match BIND's current behavior

---

documentation/language-reference/domain-modifiers/SOA.md

Using dnscontrol version 4.16.0, I get an error when using an `@` in the SOA RNAME for the example on this page:
```
2025/03/05 16:21:03 1 Validation errors:
2025/03/05 16:21:03 ERROR: in SOA @.example.com: SOA MBox must have '.' instead of '@'
exiting due to validation errors
```
As such the RNAME may not have an `@` character in it and must be fully qualified (else `$ORIGIN` is appended to it).

documentation: SOA RNAME description isn't accurate

---

pkg/js/hash.go

I note that when using `HASH("SHA1", ..)` the value and hash are printed on _stdout_:
```console
$ dnscontrol preview
Reading dnsconfig.js or equiv.
example.com.
22b77bea9d7a8cf2147bb0616aaa388b0d152013
example.
9133ab60caa1c7be379f21f1ba2968365a54bf36
```
If I use `SHA256` instead, the hashes aren't emitted (but the values are).
Looking at this code, it would appear as though two `Printf()` were forgotten. This small patch removes them.

Bug: HASH() outputs debug info

---

documentation/provider/bunny_dns.md
models/domain.go
pkg/js/helpers.js
providers/bunnydns/bunnydnsProvider.go
providers/bunnydns/convert.go
providers/bunnydns/records.go

This PR adds support for the custom Bunny DNS Redirect record. For example:
```javascript 
D("mydomain.com", REG_OVH, DnsProvider(DSP_BUNNY_DNS),
BUNNY_DNS_RDR("@", "https://redirect.com"),
BUNNY_DNS_RDR("www", "https://redirect.com"),
END);
```
will create these records in your DNS zone in Bunny:
I based this on the existing `PORKBUN_URLFWD` custom record, so hopefully these changes make sense. If a different approach is required, or whatever else, let me know! Thanks!

BUNNY_DNS: Add support for `Redirect` record

---

commands/types/dnscontrol.d.ts
documentation/release-engineering.md

The `.js` files in the `pkg/js/parse_tests` directory should be properly formatted.
Document a process for doing that.

DOCS: Add fmt for .js files to releng process

---

providers/autodns/autoDnsProvider.go

This patch resolves the `MX value does not contain 2 fields: ("smtp.google.com.")` error. This occurs when records are restored from the API (converting raw response to internal objects). Most records can be restored properly using the `RecordConfig.PopulateFromString` method but due to some quirks in AutoDNS this yields an error if tried with SRV or MX.
This resolves the issue raised with #3403 
I ran integration tests before and after, the issue also occurred when running the tests. For the sake of completeness I'm including both reports.

AUTODNS: fix error when restoring existing MX or SRV records

---

providers/cloudflare/rtypes/cfsingleredirect/from.go

The "name" assigned to CF_REDIRECTs look like `1,302,https://from/*,https://dest` which don't sort well if there are more than 10.
Make  `001,302,https://from/*,https://dest` so they sort better.

CLOUDFLARE: CF_REDIRECT "name" should be 3-digits so it sorts better

---

providers/inwx/inwxProvider.go

This changes the behavior of setting the default nameservers when creating a zone or collecting the NS set changes for an existing zone.
If the provider is a registrar and the call to INWX API endpoint 'domain.info' returns a list of nameservers, we will use those. If there is an API error (potentially authorization if using a secondary user with scoped permissions), we fall back to the previous behavior of using a static set of nameservers appropriate for the environment (live or sandbox)
fixes #3500 
BUGFIX: (INWX) use provisioned nameservers, fall back to hardcoded defaults

INWX: use provisioned nameservers, fall back to hardcoded defaults

---

commands/types/dnscontrol.d.ts
documentation/language-reference/top-level-functions/require_glob.md

From #3507 
* DOCS: mark `recursive` parameter to `require_glob` optional
tested as per Tom's suggestion in the issue. Works.

META: typescript: Mark recursive parameter of require_glob optional

---

commands/types/dnscontrol.d.ts
documentation/language-reference/domain-modifiers/IGNORE.md

There was a missing backtick in `IGNORE.md`.

DOCS: Fix typo in IGNORE.md

---

documentation/writing-providers.md

DOCS: Fix link to contributor responsibilities

---

providers/axfrddns/axfrddnsProvider.go

`ZONEMD` records are DNSSEC-like, so we'll handle them like the other DNSSEC records and simply ignore them. See https://datatracker.ietf.org/doc/html/rfc8976 for more information.
I've enabled `ZONEMD` generation on the zone used in the `AXFRDDNS_DNSSEC` integration test server, so any other PRs are likely to fail until this is merged. I have _not_ enabled it on the `AXFRDDNS` (no DNSSEC) zone, so any failures there should be unrelated to this PR.

AXFRDDNS: Ignore ZONEMD records

---

documentation/provider/index.md
providers/bunnydns/api.go
providers/bunnydns/bunnydnsProvider.go
providers/bunnydns/convert.go
providers/bunnydns/dnssec.go
providers/bunnydns/records.go

This change implements the`AUTODNSSEC` capability for Bunny DNS, based on the recently released API endpoints. I've tested proper state handling on my side and double-checked manually against the Bunny API too:
```
CONCURRENTLY gathering 0 zone(s)
SERIALLY gathering 1 zone(s)
Serially Gathering: "dnscontrol.ppmathis.com"
******************** Domain: dnscontrol.ppmathis.com
CONCURRENTLY gathering 0 zone(s)
SERIALLY gathering 1 zone(s)
Serially Gathering: "dnscontrol.ppmathis.com"
******************** Domain: dnscontrol.ppmathis.com
#1: Disable DNSSEC
SUCCESS!
CONCURRENTLY gathering 0 zone(s)
SERIALLY gathering 1 zone(s)
Serially Gathering: "dnscontrol.ppmathis.com"
******************** Domain: dnscontrol.ppmathis.com …
```

BUNNY_DNS: Support DNSSEC and fix Null MX parsing

---

commands/types/dnscontrol.d.ts
documentation/language-reference/domain-modifiers/CAA_BUILDER.md
pkg/js/helpers.js

This updates the CAA_BUILDER type definition that ends up in types-dnscontrol.d.ts to comport with the implementation - both `string[]` and `string` are allowed for `issue` and `issuewild`
The [CAA_BUILDER](https://docs.dnscontrol.org/language-reference/domain-modifiers/caa_builder#simple-example) helper function's `issue` and `issuewild` parameters can be list of strings or the special string 'none'. If the value is `'none'` the resulting CAA record will have an issue/issuewild value of `';'`.
```javascript
// @ts-check
/// <reference path="types-dnscontrol-4.18.0.d.ts" />
var REG_MY_PROVIDER = NewRegistrar('none');
var DSP_MY_PROVIDER = NewDnsProvider('none');
D(
'example.com',
REG_MY_PROVIDER,
DnsProvider(DSP_MY_PROVIDER),
CAA_BUILDER({
label: '@',
iodef: 'mailto:test@example.com', …
```

BUGFIX: types fix: CAA_BUILDER accepts string[] or string for issue

---

providers/inwx/inwxProvider.go

#3499 was an incomplete fix for #2742 and #2856 
The INWX API strips trailing dots on ALIAS RRs so the provider needs to handle this similarly to NS and CNAME. The problem manifests as an unnecessary change detected after pushing an ALIAS RR.
* INWX: fix ALIAS RR trailing dot

INWX: BUGFIX: ALIAS RRs updates are broken due to trailing dot issue

---

documentation/provider/cloudflareapi.md
documentation/provider/index.md
integrationTest/integration_test.go
providers/cloudflare/cloudflareProvider.go

Fixes https://github.com/StackExchange/dnscontrol/issues/3569
The provider blocks DS records on the apex domain.  However there are situations where Cloudflare's API would permit this.
Enable DS at the apex.  There will be times when Cloudflare's API rejects this, but we can't predict when that will be, so we won't second guess the API.  We won't do anything special with the error.
It might be possible to improve this situation when the CLOUDFLAREAPI provider supports the registrar functions.

CLOUDFLAREAPI: Enable inserting DS records at the domain apex (even if they may be rejected)

---

integrationTest/integration_test.go
providers/route53/route53Provider.go

Converting a R53_ALIAS to a CNAME (in the ROUTE53 provider) is broken.
The API calls are done in the wrong order and are thus rejected. DNS RFCs dictate that if a CNAME exists at a label, it can be the only record at that label. Therefore R53_ALIAS -> CNAME conversion must first remove the cname CNAME, then create the R53_ALIAS replacement.  If the R53_ALIAS is created first, that fails because the CNAME exists; and thus the creation of the R53_ALIAS violates the DNS rule mentioned previously.
Remove ROUTE53's attempt to reorder instructions.
The pkg/dnssort module reorders the instructions to be executed (i.e. the API calls) such that CNAME ordering and other DNS rules are obeyed.
The ROUTE53 provider was written before the pkg/dnssort module was created. The legacy code makes an attempt …

ROUTE53: BUGFIX converting alias to cname causes failure

---

providers/autodns/api.go
providers/autodns/auditrecords.go
providers/autodns/autoDnsProvider.go
providers/autodns/types.go

Best reviewed commit-by commit.
We already advertised `providers.CanGetZones`, but `ZoneLister`'s `ListZones()` wasn't implemented yet. Adding support is very simple, we just need to `POST zone/_search` without filters. I made some of the error paths more concise (`if err := …; err != nil { … }`)
This allows to create new zones. We do some error wrapping before to be able to distinguish a zone not existing from other failures, and then create the zone with dummy values, using the `POST /zone` endpoint.
Use the `GET domain/{name}` endpoint to retrieve nameserver config of a domain, and use `PUT domain/{name}` to update it. Then `GetRegistrarCorrections` can simply compare the list of nameservers retrieved on `getDomain` with the desired values, and if different, do a (sparse) request to …

AUTODNS: Enable "get-zones" (ListZones, EnsureZoneExists, GetRegistrarCorrections)

---

providers/gandiv5/gandi_v5Provider.go

Fixes https://github.com/StackExchange/dnscontrol/issues/3581
DNSControl attempts to lowercase all labels (See Opinion #4 in https://docs.dnscontrol.org/developer-info/opinions).
Sadly, the Gandi API has a bug (I consider it a bug) that to update the records at a particular label, the request must specify the label with the same case as what is stored at Gandi.   In other words, the update API does not use a case-insensitive comparison when looking up the label being updated.
Luckily we save the record as it came from the API in `.Original`.  We can use that to specify the label that Gandi expects.

GANDI_V5: BUGFIX: Uppercase labels fail to update

---

README.md

Reference: used current [documentation/provider/index.md](https://github.com/StackExchange/dnscontrol/blob/6e96b769020d7146ea35562a702007cb71f1547d/documentation/provider/index.md) as the source of truth for updating the list, reordered alphabetically.

DOCS: Update providers and registrars list to latest

---

documentation/language-reference/domain-modifiers/FRAME.md
documentation/language-reference/domain-modifiers/URL.md
documentation/language-reference/domain-modifiers/URL301.md

I've filled in some blanks after the recent fixing of the types in question.
I think I got them the right way round, I'm not sure what the `parameters` are but I thought they should at least match.
The types are mentioned in the vultr provider but I could not find any reference to redirect DNS in vultr itself and I don't have an account with them so I'm not sure if that should be mentioned here or left as is.

DOCS: document redirect types

---

documentation/provider/cnr.md

'NAMESERVER' values should be specified with a trailing dot, and, according to the documentation and the 'CNR' provider code, there are three known NS records;
https://kb.centralnicreseller.com/dns/keydns/keydns-upgrade-to-anycast

CNR: Update docs with proper Nameserver example

---

commands/types/dnscontrol.d.ts
documentation/language-reference/domain-modifiers/HTTPS.md
integrationTest/integration_test.go
models/record.go
pkg/diff2/analyze.go

[ECH (Encrypted Client Hello)](https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni) is a new-ish TLS feature that lets clients communicate with a server, without revealing the SNI (desired domain) in plaintext. To solve the bootstrapping problem (how do you encrypt data to a server without knowing its public key?), you typically need to [publish the server's public key in the DNS](https://datatracker.ietf.org/doc/html/draft-ietf-tls-svcb-ech). This effectively leaves us with 3 options:
1. Manage the DNS exclusively with DNSControl. This means that you'll have to manually generate and rotate keys for all of your servers, which is both crypographically-unwise (since key management can't be automated), and a giant pain (since you'll need to manually copy-and-paste random base64-encoded …

FEATURE: Support ignoring the `ech=` parameter in `HTTPS`/`SVCB` RR types

---

documentation/provider/digitalocean.md

The URL for creating an API token has changed, as has the naming of the token.

DIGITALOCEAN: DOCS: update instructions for creating API token

---

commands/ppreviewPush.go
pkg/notifications/bonfire.go
pkg/notifications/notifications.go
pkg/notifications/shoutrrr.go
pkg/notifications/slack.go
pkg/notifications/teams.go
pkg/notifications/telegram.go

Currently there are no errors reported from the notifications, which can make it difficult to spot configuration errors. This change logs the first error reported by any notifier for each change.

FEATURE: --notify now makes errors visible to make debugging easier

---

commands/ppreviewPush.go

Notifications are sent before a correction is made, and not at all in preview mode, despite the preview command supporting the notify flag. Fixes https://github.com/StackExchange/dnscontrol/issues/3615

BUG: Fix --notify on preview and on error

---

build/generate/featureMatrix.go
documentation/provider/index.md

Fixes: #3607
Since the anchors were automatically provided by GitBook I just needed to:
- create an inline table of contents for the generated tables
This information is also in the sidebar on the right, but having it inline seems nicer.
Should we provide links to jump back to the top?  I'm leaving it out for now.
[The preview](https://docs.dnscontrol.org/~/revisions/tqzh8eb8YmxphuX5Ufbw/provider/index) lets me jump around to the different tables with the inline links and the sidebar links.

DOCS: add links to help jump to provider table anchors

---

.linkspector.yml
documentation/advanced-features/adding-new-rtypes.md
documentation/advanced-features/writing-providers.md
documentation/index.md
documentation/provider/axfrddns.md

Ran `Linkspector` again to verify documentation links and fixed several invalid URLs.
The following result remained after the update:
```shell
npx linkspector check
```
```shell
🚫 documentation/provider/namedotcom.md, https://www.name.com/reseller/apply , 404, 71, null
💥 Error: Some hyperlinks in the specified files are invalid.
```
See:  
https://github.com/StackExchange/dnscontrol/blob/0d081ba10c2776c48f04208c99b0100a84593594/documentation/provider/namedotcom.md#L71
Fixes https://github.com/StackExchange/dnscontrol/issues/3431

DOCS: Linkspector URI fixes

---

providers/mythicbeasts/mythicbeastsProvider.go

Motivation: Speed up integration tests.
I've tested this works.
I measured the speed up for requests (as measured between curl's `time_pretransfer` and `time_total`, i.e. ignoring DNS/handshake/auth):
* Before: 1s
* After: 0.6s
40% improvement for me. Further, since I'm located ~maximally from the API server (~350ms RTT), which accounts for most the 0.6s I observe, hopefully Github Actions isn't as far, and so observes an even larger proportional speedup.
Fixes https://github.com/StackExchange/dnscontrol/issues/3628

MYTHICBEASTS: Performance improvement: Use the OAuth2 client credentials protocol

---

documentation/provider/index.md
providers/mythicbeasts/mythicbeastsProvider.go

Per https://docs.dnscontrol.org/advanced-features/concurrency-verified , this test was successful.
This is as expected, since the only mutable state is http.Client[0], which is documented as being concurrent safe[1].
0. https://github.com/StackExchange/dnscontrol/blob/1f8b7d01b6f0f184bd86cefe7d30ccc7ca6ac105/providers/mythicbeasts/mythicbeastsProvider.go#L27-L31
1. https://pkg.go.dev/net/http#hdr-Clients_and_Transports

MYTHICBEASTS: Mark as concurrent verified.

---

documentation/advanced-features/adding-new-rtypes.md
documentation/provider/index.md
go.mod
go.sum
pkg/diff2/diff2.go
pkg/txtutil/txtcode.go
pkg/txtutil/txtcombined.go
providers/capabilities.go
providers/porkbun/api.go
providers/porkbun/porkbunProvider.go

The Porkbun API frequently responds with HTTP 503. It seems like they
use this instead of 429.
The provider previously would cause the HTML response from the 503 to
leak through to the caller, causing JSON decode to fail: the provider
only checked for response codes 202 and 503. Before checking the
response code it had already read the body. If the API responded with
anything other than 202 or 503, the response body was returned as-is,
even if the response was not 200. Per the Porkbun API docs:
Any HTTP response code other than 200 is an error
But the provider was not checking this. If there is a 5xx error, the
response body contains HTML, which causes the caller to output a warning
such as
INFO#1: Domain "example.com" provider porkbun Error: failed parsing url forwarding record list from …

PORKBUN: Improve retry handling, mark as concurrent

---

go.mod
go.sum
providers/powerdns/powerdnsProvider.go

Bump go-powerdns to v0.6.7 and adjust SOAEditAPI type. This replaces #3647

chore: update go-powerdns to v0.6.7 and adjust SOAEditAPI type

---

.goreleaser.yml

Both of these features have already been removed, so it makes no sense to mention that they will be removed in the future. I noticed this in the v4.22.0 release notes, so this PR should fix this for any future releases.

DOCS: Remove get-certs and MSDNS from release notes

---

.editorconfig
documentation/advanced-features/concurrency-verified.md
providers/capabilities.go

DOCS: explain more about what `CanConcur` means.
Update `.editorconfig` to let markdown include trailing whitespace.
My text-editor obeys `.editorconfig` and when reviewing the changes to
`concurrency-verified.md` for DNSimple, I missed that the first chunk is not an
actual Markdown list and the whitespace was actually significant there.

DOCS: expand upon concurrency

---

providers/cnr/nameservers.go

> ## Before submiting a pull request
> 
> Please make sure you've run the following commands from the root directory.
> 
> go vet ./...
> go fmt ./...
> go generate ./...
> go mod tidy
Done
> ## Release changelog section
> 
> Help keep the release changelog clear by pre-naming the proper section in the GitHub pull request title.
> 
> Some examples:
> * CICD: Add required GHA permissions for goreleaser
> * DOCS: Fixed providers with "contributor support" table
> * ROUTE53: Allow R53_ALIAS records to enable target health evaluation
> 
> More examples/context can be found in the file .goreleaser.yml under the 'build' > 'changelog' key.
Done
This PR is reviewing the CNR Provider Module in direction of reported issue #3663.

CNR: nameserver corrections should be case insensitive

---

.github/pull_request_template.md

The PR template is out of date. bin/generate-all.sh should be used instead of individual commands.
Fix it.

CICD: Update PR instructions

---

providers/digitalocean/digitaloceanProvider.go

Using diff2 with ByRecord was a pretty simple change. Based on #3683 I guess switching to the new implementation makes sense.
Somewhat unrelated note, I think DocDualHost capability could be enabled, it works on the API and looks OK on the Digitalocean UI, but I don't know if there is a chance it won't really work in a real use.

DIGITALOCEAN: Use diff2 to implement digitalocean provider

---

commands/types/dnscontrol.d.ts
documentation/getting-started/getting-started.md
documentation/language-reference/top-level-functions/D.md
pkg/normalize/validate.go

As reported in https://github.com/StackExchange/dnscontrol/issues/3530 ...
- Using “@” as the apex.
- The expectation is that the empty string would work.
- Suggestion 1: The getting started doc should explain that "@" is used for the apex
- Suggestion 2: When the user specifies `""`, the error message should suggest using `"@"`.
- Suggestion 3: When the user specifies "example.com" (the apex domain), the error message should suggest using `"@"`
- Converting zones: Doing the first “push” is nervous-making.  How to migrate a zone safely?
- The docs should suggest some testing methods to calm fears.
- The docs should remind people that "get-zones" isn't perfect, but produces "a good first draft" you can edit.
- Suggest trying iterations of `preview` and editing dnsconfig.js until no …

DOCS: Warn that "" should be "@" in error messages & docs. Update docs to suggest safer onboarding process.

---

integrationTest/integration_test.go
integrationTest/profiles.json
pkg/diff/diff2compat.go
pkg/js/helpers.js
providers/akamaiedgedns/akamaiEdgeDnsProvider.go
providers/capabilities.go
providers/capability_string.go
providers/cloudns/cloudnsProvider.go
providers/cnr/cnrProvider.go
providers/cscglobal/cscglobalProvider.go
providers/desec/desecProvider.go
providers/digitalocean/digitaloceanProvider.go
providers/dnsimple/dnsimpleProvider.go
providers/dnsmadeeasy/dnsMadeEasyProvider.go
providers/domainnameshop/domainnameshopProvider.go
providers/exoscale/exoscaleProvider.go
providers/hetzner/hetznerProvider.go
providers/hexonet/hexonetProvider.go
providers/hostingde/hostingdeProvider.go
providers/linode/linodeProvider.go
providers/loopia/loopiaProvider.go
providers/namecheap/namecheapProvider.go
providers/namedotcom/namedotcomProvider.go
providers/netcup/netcupProvider.go
providers/netlify/netlifyProvider.go
providers/oracle/oracleProvider.go
providers/packetframe/packetframeProvider.go
providers/providers.go
providers/rwth/rwthProvider.go
providers/softlayer/softlayerProvider.go

IGNORE() is unreliable for providers that haven't adopted the diff2 library.
A few years ago we replaced the diffing engine ("diff") with a new one that handled IGNORE() and many features much better.  Most of the providers were rewritten to use the new library.  Since rewriting the provider was such a burden (and in some cases the maintainer of the provider had disappeared), I created a backwards compatibility mode called diff.NewCompat().  While it had the benefit of only requiring 2-3 lines of code changes, it doesn't implement IGNORE() reliably in all cases.  Other, newer, features also don't work.
1. Add a new capability called `CanOnlyDiff1Features` to mark which providers have not been upgraded yet. It is not automatically generated, thus we should be careful when converting …

Warn if IGNORE() is unreliable for this provider

---

go.mod
go.sum
providers/gcore/gcoreProvider.go

Update GCore SDK `CreateZone` calls to use the latest calling signature after SDK update.
Supersedes #3706

GCORE: update create zone call signature from latest SDK

---

documentation/provider/porkbun.md
integrationTest/profiles.json
providers/porkbun/api.go
providers/porkbun/porkbunProvider.go

The Porkbun provider can now configure the API retry mechanism by setting max_attempts and/or max_duration in the credentials configuration. This aims to help users who have many domains configured and run in to Porkbun API limits with the current retry mechanism.
The max_attempts setting controls how many attempts (in total, not retries) will be made for each domain. The default is 5.
The max_duration allows the retry mechanism to keep retrying up to this duration, for each domain.
The current behaviour is to do exponential backoff between 1 second and 10 seconds, with 5 retries (6 total attempts), with jitter of +/-100ms (max, it will vary). The jitter means the provider will often retry sooner than 1 second, which the Porkbun API doesn't like. To counter this, the minimum retry time is …

PORKBUN: Configurable retry parameters

---

pkg/normalize/validate.go

This pull request adds support for the `issuemail` `CAA` tag introduced in [RFC 9495](https://datatracker.ietf.org/doc/html/rfc9495)

FEATURE: Support RFC 9495 issuemail tag in CAA records

---

providers/gandiv5/gandi_v5Provider.go

GANDI_V5: Increase API timeouts

---

commands/types/dnscontrol.d.ts
documentation/language-reference/domain-modifiers/CAA.md
documentation/language-reference/domain-modifiers/CAA_BUILDER.md
models/t_caa.go
pkg/js/helpers.js
pkg/normalize/validate.go

This PR completes the work of #3762 as requested in #3662
CAABuilder now supports `issuemail` and `issuevmc` tags

CAA: Support issuemail / issuevmc tag in CAA builder
